Night Owl:
  modes:
    dark:
      primary-color: "#7E57C2"
      accent-color: "#7E57C2"
      primary-background-color: "#011627"
      secondary-background-color: "#0B253A"
      card-background-color: "#0B2942"
      primary-text-color: "#D6DEEB"
      secondary-text-color: "#89A4BB"
      disabled-text-color: "#5F7E97"
      divider-color: "#122D42"
      app-header-background-color: "#011627"
      app-header-text-color: "#D6DEEB"
      sidebar-background-color: "#011627"
      sidebar-text-color: "#89A4BB"
      sidebar-selected-background-color: "#1D3B53"
      sidebar-selected-text-color: "#D6DEEB"
      state-active-color: "#82AAFF"
      state-inactive-color: "#5F7E97"
      state-unavailable-color: "#EF5350"
      success-color: "#9CCC65"
      warning-color: "#C5E478"
      error-color: "#EF5350"
