// @bun
// packages/vault-notes/src/check.ts
import { spawnSync } from "child_process";
import { access, readFile as readFile3 } from "fs/promises";
import { homedir } from "os";
import path4 from "path";

// packages/vault-notes/src/resources-index.ts
import path from "path";
var RESOURCES_FINDING_IDS = [
  "resources-contract-invalid",
  "resources-route-missing",
  "resources-index-missing",
  "resources-block-invalid",
  "resources-entry-missing",
  "resources-entry-stale",
  "resources-entry-foreign",
  "resources-entry-duplicate"
];
var DEFAULT_INDEX_FILE = "resources.md";
var CONTRACT_FILE = "schemas/frontmatter-contract.json";
var GENERATED = { name: "generated", start: "<!-- project-resources:generated:start -->", end: "<!-- project-resources:generated:end -->" };
var SHARED = { name: "shared", start: "<!-- project-resources:shared:start -->", end: "<!-- project-resources:shared:end -->" };
var GENERATED_NOTICE = "<!-- Generated by vault-notes resources from each note's frontmatter. Regeneration replaces this block; curate shared notes above. -->";
var EMPTY_BLOCK = "_No project-owned reference or decision notes yet._";
var HISTORICAL_STATUSES = new Set(["archived", "superseded"]);
function readResourcesPolicy(contract) {
  const raw = contract.projectResources;
  if (raw === undefined)
    return { state: "inactive", indexFile: DEFAULT_INDEX_FILE };
  if (typeof raw !== "object" || raw === null || Array.isArray(raw))
    return { state: "invalid", reason: "it must be an object" };
  const unknownKey = Object.keys(raw).find((key) => key !== "indexFile");
  if (unknownKey !== undefined)
    return { state: "invalid", reason: `remove unknown key '${unknownKey}'` };
  const { indexFile } = raw;
  if (typeof indexFile !== "string" || !/^[a-z0-9][a-z0-9._-]*\.md$/.test(indexFile)) {
    return { state: "invalid", reason: "'indexFile' must be a lowercase Markdown file name such as 'resources.md'" };
  }
  if (Object.hasOwn(contract.routing.projectFiles, indexFile)) {
    return { state: "invalid", reason: `'indexFile' must not be the project packet file '${indexFile}'` };
  }
  return { state: "active", indexFile };
}
function resourcesFindings(notes, contract) {
  const policy = readResourcesPolicy(contract);
  if (policy.state === "inactive")
    return [];
  if (policy.state === "invalid") {
    return [
      {
        id: "resources-contract-invalid",
        file: CONTRACT_FILE,
        message: `fix 'projectResources': ${policy.reason}`,
        detail: { field: "projectResources" }
      }
    ];
  }
  return projectsOf(notes).flatMap((project) => analyseProject(notes, project, policy.indexFile).findings);
}
function projectsOf(notes) {
  return [...new Set(notes.flatMap((note) => note.placement.project === null ? [] : [note.placement.project]))].sort();
}
function proposeResources(notes, projects, indexFile, updated) {
  return projects.map((project) => {
    const analysis = analyseProject(notes, project, indexFile);
    const { content, state } = proposeContent(analysis, updated);
    return {
      project,
      indexPath: analysis.indexPath,
      notes: analysis.owned.map((note) => note.relativePath),
      folderMaps: analysis.maps.map((note) => note.relativePath),
      state,
      content,
      findings: analysis.findings
    };
  });
}
function analyseProject(notes, project, indexFile) {
  const inProject = notes.filter((note) => note.placement.project === project);
  const indexNote = inProject.find((note) => note.placement.projectPath === indexFile);
  const analysis = {
    project,
    indexPath: `projects/${project}/${indexFile}`,
    readme: inProject.find((note) => note.placement.projectRole === "packet" && note.placement.projectPath === "README.md"),
    owned: inProject.filter((note) => note.placement.projectRole === "note" && note !== indexNote),
    maps: inProject.filter((note) => note.placement.projectRole === "folder-map"),
    index: indexNote === undefined ? null : parseIndex(indexNote.content),
    findings: []
  };
  analysis.findings = [...routeFindings(analysis, indexFile), ...indexFindings(analysis)];
  return analysis;
}
function routeFindings({ project, readme }, indexFile) {
  if (readme !== undefined && localTargets(visibleMarkdown(readme.content)).some((target) => target === indexFile))
    return [];
  return [
    {
      id: "resources-route-missing",
      file: `projects/${project}/README.md`,
      message: `link the Resources Index from this README, for example '- [Resources index](${indexFile})'`,
      detail: { project, target: indexFile }
    }
  ];
}
function indexFindings(analysis) {
  const { project, indexPath, index } = analysis;
  const regenerate = `regenerate with 'vault-notes resources --project ${project}'`;
  if (index === null) {
    return [{ id: "resources-index-missing", file: indexPath, message: `create this Resources Index; ${regenerate}`, detail: { project } }];
  }
  if (index.invalid !== null || index.generated === null) {
    const reason = index.invalid ?? `add the generated block: one '${GENERATED.start}' line followed by one '${GENERATED.end}' line`;
    return [{ id: "resources-block-invalid", file: indexPath, message: `${reason}; ${regenerate}`, detail: { project } }];
  }
  return entryFindings(analysis, index.lines.slice(index.generated.start + 1, index.generated.end), regenerate);
}
function entryFindings(analysis, blockLines, regenerate) {
  const { project, indexPath } = analysis;
  const expected = new Set([...analysis.owned, ...analysis.maps].map((note) => note.placement.projectPath ?? note.relativePath));
  const seen = new Set;
  const findings = [];
  const add = (id, message, detail) => findings.push({ id, file: indexPath, message: `${message}; ${regenerate}`, detail: { project, ...detail } });
  for (const target of blockLines.flatMap(entryTarget)) {
    const projectPath = resolveInProject(target);
    if (projectPath === null) {
      add("resources-entry-foreign", `move the entry '${target}' to the shared block: the generated block lists only notes this project owns`, { target });
    } else if (!expected.has(projectPath)) {
      add("resources-entry-stale", `remove the entry '${target}': it is not a reference or decision note or folder map this project owns`, { target });
    } else if (seen.has(projectPath)) {
      add("resources-entry-duplicate", `list '${projectPath}' once in the generated block`, { target });
    }
    if (projectPath !== null)
      seen.add(projectPath);
  }
  for (const projectPath of expected) {
    if (!seen.has(projectPath))
      add("resources-entry-missing", `add the entry for '${projectPath}'`, { path: projectPath });
  }
  return findings;
}
function parseIndex(content) {
  const lines = content.split(`
`);
  const generated = findBlock(lines, GENERATED);
  const shared = findBlock(lines, SHARED);
  const separate = !(isBlock(generated) && isBlock(shared) && overlaps(generated, shared));
  const invalid = [generated, shared].find((parse) => typeof parse === "string") ?? (separate ? null : "keep the shared and generated blocks separate: neither block may contain the other's markers");
  return { lines, generated: isBlock(generated) ? generated : null, invalid };
}
function findBlock(lines, markers) {
  const starts = lines.flatMap((line, index) => line.trim() === markers.start ? [index] : []);
  const ends = lines.flatMap((line, index) => line.trim() === markers.end ? [index] : []);
  if (starts.length === 0 && ends.length === 0)
    return null;
  const [start] = starts;
  const [end] = ends;
  if (starts.length !== 1 || ends.length !== 1 || start === undefined || end === undefined || end < start) {
    return `keep exactly one '${markers.start}' line followed by one '${markers.end}' line in the ${markers.name} block`;
  }
  return { start, end };
}
function isBlock(value) {
  return typeof value === "object" && value !== null;
}
function overlaps(left, right) {
  return left.start < right.end && right.start < left.end;
}
function entryTarget(line) {
  const target = /^\s*[-*+]\s+\[(?:\\.|[^\]\\])*\]\(([^)]*)\)/.exec(line)?.[1];
  return target === undefined ? [] : [linkPath(target)];
}
function visibleMarkdown(content) {
  let fence = null;
  const lines = [];
  for (const line of content.replace(/<!--[\s\S]*?-->/g, "").split(`
`)) {
    const opener = /^ {0,3}(`{3,}|~{3,})/.exec(line)?.[1];
    if (fence === null && opener !== undefined)
      fence = opener;
    else if (fence !== null && opener !== undefined && opener[0] === fence[0] && opener.length >= fence.length && line.trim() === opener)
      fence = null;
    else if (fence === null)
      lines.push(line);
  }
  return lines.join(`
`);
}
function localTargets(content) {
  return [...content.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)].flatMap((match) => {
    const resolved = resolveInProject(linkPath(match[1] ?? ""));
    return resolved === null ? [] : [resolved];
  });
}
function linkPath(raw) {
  const trimmed = raw.trim();
  if (trimmed.startsWith("<"))
    return trimmed.slice(1, trimmed.indexOf(">") < 0 ? undefined : trimmed.indexOf(">"));
  return trimmed.split(/\s+/, 1)[0] ?? "";
}
function resolveInProject(target) {
  if (target === "" || /^[a-z][a-z0-9+.-]*:|^[#/]/i.test(target))
    return null;
  const withoutFragment = target.split("#", 1)[0] ?? "";
  const normalised = path.posix.normalize(safeDecode(withoutFragment));
  if (normalised === "." || normalised === ".." || normalised.startsWith("../") || normalised.startsWith("/"))
    return null;
  return normalised;
}
function safeDecode(value) {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}
function proposeContent(analysis, updated) {
  const body = renderGeneratedBody(analysis.owned, analysis.maps);
  const { index } = analysis;
  if (index === null)
    return { content: renderNewIndex(analysis, body, updated), state: "create" };
  if (index.invalid !== null)
    return { content: null, state: "blocked" };
  const current = index.lines.join(`
`);
  const content = index.generated === null ? appendGeneratedBlock(current, body) : replaceBlock(index.lines, index.generated, body);
  return { content, state: content === current ? "current" : "update" };
}
function replaceBlock(lines, block, body) {
  return [...lines.slice(0, block.start + 1), ...body, ...lines.slice(block.end)].join(`
`);
}
function appendGeneratedBlock(content, body) {
  const base = content.endsWith(`
`) ? content : `${content}
`;
  return `${base}
## Project-owned notes

${[GENERATED.start, ...body, GENERATED.end].join(`
`)}
`;
}
function renderGeneratedBody(owned, maps) {
  if (owned.length === 0 && maps.length === 0)
    return [GENERATED_NOTICE, "", EMPTY_BLOCK];
  const groups = new Map;
  if (maps.length > 0)
    groups.set("Folder maps", maps);
  const folders = [...new Set(owned.map((note) => note.placement.projectFolder ?? ""))].sort();
  for (const folder of folders) {
    groups.set(folder === "" ? "Project root" : folder, owned.filter((note) => (note.placement.projectFolder ?? "") === folder));
  }
  const lines = [GENERATED_NOTICE];
  for (const [heading, notes] of groups)
    lines.push("", `### ${heading}`, "", ...notes.map(renderEntry));
  return lines;
}
function renderEntry(note) {
  const projectPath = note.placement.projectPath ?? note.relativePath;
  const title = frontmatterText(note, "title") || path.posix.basename(projectPath, ".md");
  const status = frontmatterText(note, "status");
  const summary = frontmatterText(note, "summary");
  const mark = HISTORICAL_STATUSES.has(status) ? ` _(${status})_` : "";
  return `- [${title.replace(/[[\]\\]/g, "\\$&")}](${encodePath(projectPath)})${mark}${summary === "" ? "" : `: ${summary}`}`;
}
function frontmatterText(note, field) {
  const value = note.frontmatter?.[field];
  if (typeof value !== "string")
    return "";
  let text = value.replace(/\s+/g, " ").trim();
  for (let previous = "";previous !== text; ) {
    previous = text;
    text = text.replace(/!?\[([^\]]*)\]\(([^)]*)\)/g, "$1");
  }
  return text.replaceAll("](", "] (");
}
function encodePath(projectPath) {
  return projectPath.split("/").map((segment) => encodeURIComponent(segment).replace(/[()]/g, (character) => `%${character.charCodeAt(0).toString(16).toUpperCase()}`)).join("/");
}
function renderNewIndex(analysis, body, updated) {
  const name = (analysis.readme === undefined ? "" : frontmatterText(analysis.readme, "title")) || analysis.project;
  return [
    "---",
    `title: ${JSON.stringify(`${name} resources`)}`,
    "type: reference",
    "status: active",
    `updated: ${updated}`,
    `summary: ${JSON.stringify(`Resources Index for ${name}: every reference and decision note the project owns, plus curated shared resources.`)}`,
    "related:",
    "  - README.md",
    "---",
    "",
    `# ${name} resources`,
    "",
    "Back to the [project packet](README.md).",
    "",
    "## Shared resources",
    "",
    "Notes owned elsewhere appear here only by explicit, curated association. Regeneration never adds or removes them.",
    "",
    SHARED.start,
    SHARED.end,
    "",
    "## Project-owned notes",
    "",
    GENERATED.start,
    ...body,
    GENERATED.end,
    ""
  ].join(`
`);
}

// packages/vault-notes/src/vault-catalogue.ts
import { readdir, readFile as readFile2 } from "fs/promises";
import path3 from "path";

// packages/vault-notes/src/vault-contract.ts
import { readFile } from "fs/promises";
import path2 from "path";
async function loadContract(root) {
  const source = await readFile(path2.join(root, "schemas", "frontmatter-contract.json"), "utf8");
  return JSON.parse(source);
}
function isEmptyValue(value) {
  if (value === null || value === undefined || value === "")
    return true;
  if (Array.isArray(value))
    return value.length === 0;
  if (typeof value === "object")
    return Object.keys(value).length === 0;
  return false;
}

// packages/vault-notes/src/vault-catalogue.ts
var ARTIFACT_FOLDERS = ["specs", "tickets", "proofs"];
async function openCatalogue(root) {
  const contract = await loadContract(root);
  return {
    contract,
    async notes(include = () => true) {
      const notes = [];
      for (const file of placeNotes(root, await walkNotes(root, contract), contract)) {
        if (include(file.placement))
          notes.push(await readNote(file));
      }
      return notes;
    },
    async notesWithFilenamePolicy() {
      const [noteFiles, policyFiles] = await Promise.all([walkNotes(root, contract), walkFilenamePolicy(root, contract)]);
      return {
        notes: await Promise.all(placeNotes(root, noteFiles, contract).map(readNote)),
        filenamePolicyPaths: policyFiles.map((absolutePath) => toVaultPath(root, absolutePath))
      };
    }
  };
}
function walkNotes(root, contract) {
  return collectMarkdownFiles(root, (relativePath, name) => isIgnoredNotePath(relativePath, name, contract));
}
function walkFilenamePolicy(root, contract) {
  return collectMarkdownFiles(root, (_relativePath, name, isDirectory) => isDirectory && contract.markdownFilenames.ignoredDirectories.includes(name));
}
function placeNotes(root, files, contract) {
  return files.map((absolutePath) => {
    const relativePath = toVaultPath(root, absolutePath);
    return { absolutePath, relativePath, placement: placeNote(relativePath, contract) };
  });
}
function isIgnoredNotePath(relativePath, name, contract) {
  const firstSegment = relativePath.split(path3.sep)[0];
  return name === ".git" || contract.ignored.includes(name) || contract.ignored.includes(firstSegment ?? "");
}
function toVaultPath(root, absolutePath) {
  return path3.relative(root, absolutePath).split(path3.sep).join("/");
}
async function collectMarkdownFiles(root, shouldSkip) {
  const found = [];
  async function visit(directory) {
    const entries = await readdir(directory, { withFileTypes: true });
    for (const entry of entries) {
      const absolutePath = path3.join(directory, entry.name);
      const relativePath = path3.relative(root, absolutePath);
      if (shouldSkip(relativePath, entry.name, entry.isDirectory())) {
        continue;
      }
      if (entry.isDirectory()) {
        await visit(absolutePath);
      } else if (entry.isFile() && entry.name.endsWith(".md")) {
        found.push(absolutePath);
      }
    }
  }
  await visit(root);
  return found.sort();
}
function placeNote(relativePath, contract) {
  const segments = relativePath.split("/");
  const family = relativePath.includes("/") ? segments[0] ?? null : null;
  const project = segments[0] === "projects" && segments.length >= 3 ? segments[1] ?? null : null;
  const folder = project !== null && segments.length >= 4 ? segments[2] : undefined;
  const artifactFolder = ARTIFACT_FOLDERS.find((name) => name === folder) ?? null;
  const projectSegments = project === null ? null : segments.slice(2);
  return {
    family,
    project,
    artifactFolder,
    projectPath: projectSegments?.join("/") ?? null,
    projectFolder: projectSegments?.slice(0, -1).join("/") ?? null,
    get projectRole() {
      return projectSegments === null ? null : projectRoleFor(projectSegments, artifactFolder, contract);
    },
    get isIndex() {
      return relativePath === "README.md" || Object.keys(contract.routing.familyReadmes).some((name) => relativePath === `${name}/README.md`);
    },
    get expectedTypes() {
      return routeTypes(relativePath, segments, artifactFolder, contract);
    }
  };
}
function projectRoleFor(projectSegments, artifactFolder, contract) {
  const filename = projectSegments.at(-1) ?? "";
  if (projectSegments.length === 1)
    return Object.hasOwn(contract.routing.projectFiles, filename) ? "packet" : "note";
  const isReadme = filename === "README.md";
  if (artifactFolder === null) {
    if (isReadme)
      return "folder-map";
    const folder = projectSegments[0] ?? "";
    const { projectDirectories, projectLocalTypes } = contract.routing;
    const directoryType = Object.hasOwn(projectDirectories, folder) ? projectDirectories[folder] : undefined;
    return directoryType === undefined || projectLocalTypes.includes(directoryType) ? "note" : "routed";
  }
  return isReadme && projectSegments.length === 2 ? "folder-map" : "artifact";
}
function routeTypes(relativePath, segments, artifactFolder, contract) {
  const repositoryTypes = repositoryTypesForPath(relativePath, contract);
  if (repositoryTypes)
    return repositoryTypes;
  const family = segments[0];
  const filename = segments.at(-1);
  if (!family || !filename)
    return [];
  if (segments.length === 2 && filename === "README.md") {
    const type2 = contract.routing.familyReadmes[family];
    return type2 ? [type2] : [];
  }
  if (family === "projects" && segments.length >= 3) {
    return projectTypesForPath(segments, filename, artifactFolder, contract);
  }
  const type = contract.routing.familyNotes[family];
  return type ? [type] : [];
}
function repositoryTypesForPath(relativePath, contract) {
  const repositoryFileType = contract.routing.repositoryFiles[relativePath];
  if (repositoryFileType) {
    return [repositoryFileType];
  }
  for (const [prefix, type] of Object.entries(contract.routing.repositoryPrefixes)) {
    if (relativePath.startsWith(prefix))
      return [type];
  }
  return relativePath === "README.md" ? [contract.routing.rootReadme] : undefined;
}
function projectTypesForPath(segments, filename, artifactFolder, contract) {
  if (segments.length === 4 && filename === "README.md" && artifactFolder)
    return ["reference"];
  if (filename === "README.md" && segments.length > 3)
    return contract.routing.projectLocalTypes;
  const packetType = contract.routing.projectFiles[filename];
  if (packetType)
    return [packetType];
  const directoryType = contract.routing.projectDirectories[segments[2] ?? ""];
  return directoryType ? [directoryType] : contract.routing.projectLocalTypes;
}
async function readNote({ absolutePath, relativePath, placement }) {
  const content = await readFile2(absolutePath, "utf8");
  const note = { absolutePath, relativePath, content, placement };
  const match = content.match(/^---\s*\n([\s\S]*?)\n---(?:\s*\n|$)/);
  if (!match?.[1]) {
    return { ...note, frontmatter: null };
  }
  try {
    const parsed = Bun.YAML.parse(match[1]);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return { ...note, frontmatter: null, frontmatterError: "frontmatter must be a YAML object" };
    }
    return { ...note, frontmatter: parsed };
  } catch (error) {
    return { ...note, frontmatter: null, frontmatterError: error instanceof Error ? error.message : String(error) };
  }
}

// packages/vault-notes/src/check.ts
var VAULT_FINDING_IDS = [
  "frontmatter-invalid-yaml",
  "frontmatter-missing",
  "required-field-missing",
  "type-required-field-missing",
  "type-unknown",
  "status-invalid",
  "path-unrouted",
  "type-path-mismatch",
  "optional-field-empty",
  "forbidden-field-present",
  "field-shape-invalid",
  "summary-too-long",
  "body-secret-shaped-value",
  "identity-duplicate",
  "link-missing-target",
  "filename-uppercase",
  "ticket-placement-invalid",
  "ticket-spec-invalid",
  "artifact-map-missing",
  ...RESOURCES_FINDING_IDS
];
var DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
async function checkVault(root, options = {}) {
  const canonicalRoot = path4.resolve(options.canonicalRoot ?? root);
  const catalogue = await openCatalogue(root);
  const { contract } = catalogue;
  const { notes, filenamePolicyPaths } = await catalogue.notesWithFilenamePolicy();
  const issues = validateMarkdownFilenames(filenamePolicyPaths, contract);
  for (const note of notes) {
    issues.push(...validateFrontmatter(note, contract));
    issues.push(...validateBodySecrets(note, contract));
    issues.push(...await validateLinks(note, root, canonicalRoot));
  }
  issues.push(...validateUniqueIdentities(notes, contract));
  issues.push(...validateTicketOwnership(notes));
  issues.push(...validateArtifactMaps(notes));
  issues.push(...resourcesFindings(notes, contract));
  return issues;
}
function validateArtifactMaps(notes) {
  const paths = new Set(notes.map((note) => note.relativePath));
  const missing = new Set;
  for (const { placement } of notes) {
    if (!placement.artifactFolder)
      continue;
    const map = `projects/${placement.project}/${placement.artifactFolder}/README.md`;
    if (!paths.has(map))
      missing.add(map);
  }
  return [...missing].map((file) => ({
    file,
    id: "artifact-map-missing",
    message: "create this stable folder map from templates/project/folder-map.md"
  }));
}
function validateTicketOwnership(notes) {
  const byPath = new Map(notes.map((note) => [note.absolutePath, note]));
  const issues = [];
  for (const note of notes) {
    if (note.frontmatter?.type !== "project-ticket")
      continue;
    const parts = note.relativePath.split("/");
    const specPath = note.frontmatter.spec_path;
    const spec = typeof specPath === "string" ? byPath.get(path4.resolve(path4.dirname(note.absolutePath), specPath)) : undefined;
    const specParts = spec?.relativePath.split("/");
    const validSpec = spec?.frontmatter?.type === "project-spec" && specParts?.length === 4 && specParts[0] === "projects" && specParts[1] === parts[1] && specParts[2] === "specs";
    if (!validSpec)
      issues.push({
        file: note.relativePath,
        id: "ticket-spec-invalid",
        message: "set spec_path to an existing project-spec in this project's specs folder"
      });
    if (parts.length !== 5 || parts[0] !== "projects" || parts[2] !== "tickets" || validSpec && parts[3] !== path4.basename(spec.relativePath, ".md")) {
      issues.push({
        file: note.relativePath,
        id: "ticket-placement-invalid",
        message: "move this ticket to tickets/<owning-spec-slug>/<ticket-slug>.md and preserve its identities"
      });
    }
  }
  return issues;
}
function validateMarkdownFilenames(files, contract) {
  const allowlist = new Set(contract.markdownFilenames.uppercaseBasenameAllowlist);
  return files.flatMap((file) => {
    const basename = path4.posix.basename(file);
    if (!/[A-Z]/.test(basename) || allowlist.has(basename))
      return [];
    return [{
      file,
      id: "filename-uppercase",
      message: `rename Markdown filename to '${basename.toLowerCase()}'; uppercase is reserved for ${Array.from(allowlist).map((value) => `'${value}'`).join(", ")}`
    }];
  });
}
function validateBodySecrets(note, contract) {
  const lines = note.content.split(`
`);
  const frontmatterEnd = lines[0]?.trim() === "---" ? lines.findIndex((line, index) => index > 0 && line.trim() === "---") : -1;
  const labels = contract.forbiddenFields.map((field) => field.split("_").map(escapeRegExp).join("[ _-]?")).sort((left, right) => right.length - left.length).join("|");
  const secretAssignment = new RegExp("\\b(?:" + labels + ")\\b\\s*(?:[:=]|\\bis\\b)\\s*[\"'`]?[^\\s\"'`]{12,}", "i");
  const issues = [];
  for (let index = frontmatterEnd + 1;index < lines.length; index += 1) {
    if (!secretAssignment.test(lines[index] ?? ""))
      continue;
    issues.push({
      file: note.relativePath,
      id: "body-secret-shaped-value",
      message: `remove secret-shaped value from note body at line ${index + 1}; ` + "keep the value with its source owner and retain only a reference"
    });
  }
  return issues;
}
function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function validateFrontmatter(note, contract) {
  const issues = [];
  const add = (id, message, repair) => issues.push({ file: note.relativePath, id, message, ...repair ?? {} });
  if (note.frontmatterError) {
    add("frontmatter-invalid-yaml", `fix invalid YAML frontmatter: ${note.frontmatterError}`);
    return issues;
  }
  if (!note.frontmatter) {
    add("frontmatter-missing", "add YAML frontmatter bounded by --- lines");
    return issues;
  }
  const metadata = note.frontmatter;
  const type = typeof metadata.type === "string" ? metadata.type : "";
  validateRequiredFields(metadata, type, contract, add);
  validateTypeStatus(metadata, type, contract, add);
  validatePathRoute(note.placement.expectedTypes, type, add);
  validateEmptyAndForbiddenFields(metadata, contract, add);
  validateFieldShapes(metadata, contract, (field, message) => issues.push({
    file: note.relativePath,
    id: "field-shape-invalid",
    message,
    detail: { field }
  }));
  if (typeof metadata.summary === "string" && metadata.summary.length > contract.summaryMaxLength) {
    add("summary-too-long", `shorten 'summary' to ${contract.summaryMaxLength} characters or fewer`);
  }
  return issues;
}
function validateRequiredFields(metadata, type, contract, add) {
  for (const field of contract.required) {
    if (isEmptyValue(metadata[field])) {
      add("required-field-missing", `add required frontmatter field '${field}'`);
    }
  }
  for (const field of contract.requiredByType[type] ?? []) {
    if (isEmptyValue(metadata[field])) {
      add("type-required-field-missing", `add required ${type} field '${field}'`);
    }
  }
}
function validateTypeStatus(metadata, type, contract, add) {
  const allowedStatuses = contract.statusesByType[type];
  if (type && !allowedStatuses) {
    add("type-unknown", `replace unknown type '${type}' with a contract type`);
  } else if (allowedStatuses && typeof metadata.status === "string" && !allowedStatuses.includes(metadata.status)) {
    add("status-invalid", `use a valid status for '${type}': ${allowedStatuses.map((value) => `'${value}'`).join(", ")}`);
  }
}
function validatePathRoute(expectedTypes, type, add) {
  if (expectedTypes.length === 0) {
    add("path-unrouted", "move this note into a routed family or add an approved routing contract");
  } else if (type && !expectedTypes.includes(type)) {
    add("type-path-mismatch", `change type to ${expectedTypes.map((value) => `'${value}'`).join(" or ")} for this path`);
  }
}
function validateEmptyAndForbiddenFields(metadata, contract, add) {
  for (const field of contract.optional) {
    if (field in metadata && isEmptyValue(metadata[field])) {
      add("optional-field-empty", `remove empty optional field '${field}'`, {
        repairId: "remove-empty-optional-field",
        detail: { field }
      });
    }
  }
  for (const field of contract.forbiddenFields) {
    if (field in metadata) {
      add("forbidden-field-present", `remove forbidden secret-bearing field '${field}'`);
    }
  }
}
var FIELD_SHAPE_RULES = {
  "non-empty-string": {
    holds: (value) => typeof value === "string" && value.trim() !== "",
    wording: "a non-empty string"
  },
  date: {
    holds: (value) => typeof value === "string" && DATE_PATTERN.test(value),
    wording: "YYYY-MM-DD"
  },
  "non-empty-string-list": {
    holds: (value) => Array.isArray(value) && value.length > 0 && value.every((entry) => typeof entry === "string" && entry.trim() !== ""),
    wording: "a non-empty list of strings"
  },
  "non-empty-string-map": {
    holds: (value) => Boolean(value) && typeof value === "object" && !Array.isArray(value) && Object.keys(value).length > 0 && Object.entries(value).every(([key, entry]) => key.trim() !== "" && typeof entry === "string" && entry.trim() !== ""),
    wording: "a non-empty string map"
  }
};
function validateFieldShapes(metadata, contract, add) {
  for (const [field, shape] of Object.entries(contract.fieldShapes)) {
    if (!(field in metadata) || isEmptyValue(metadata[field]))
      continue;
    const rule = Object.hasOwn(FIELD_SHAPE_RULES, shape) ? FIELD_SHAPE_RULES[shape] : FIELD_SHAPE_RULES["non-empty-string-map"];
    if (!rule.holds(metadata[field]))
      add(field, `format '${field}' as ${rule.wording}`);
  }
}
function validateUniqueIdentities(notes, contract) {
  const seen = new Map;
  const issues = [];
  for (const note of notes) {
    for (const field of contract.identityFields) {
      issues.push(...validateIdentity(note, field, seen));
    }
  }
  return issues;
}
function validateIdentity(note, field, seen) {
  const value = note.frontmatter?.[field];
  if (typeof value !== "string" || value.trim() === "")
    return [];
  if (field === "task_identity" && value === "historical" && note.frontmatter?.type === "project-ticket") {
    if (note.frontmatter.status === "superseded")
      return [];
    if (note.frontmatter.status === "adopted") {
      return [{
        file: note.relativePath,
        id: "field-shape-invalid",
        message: "replace 'historical' task_identity with a real Task identity for adopted project-ticket",
        detail: { field: "task_identity" }
      }];
    }
  }
  const key = `${field}:${value}`;
  const existing = seen.get(key);
  if (!existing) {
    seen.set(key, note.relativePath);
    return [];
  }
  return [{
    file: note.relativePath,
    id: "identity-duplicate",
    message: `replace duplicate ${field} '${value}'; first used by '${existing}'`
  }];
}
async function validateLinks(note, root, canonicalRoot) {
  const issues = [];
  const matches = note.content.matchAll(/\[[^\]]*\]\(([^)]+)\)/g);
  for (const match of matches) {
    const rawTarget = match[1]?.trim();
    if (!rawTarget || /^(?:https?:|mailto:|qmd:|#)/.test(rawTarget))
      continue;
    const target = rawTarget.split("#", 1)[0];
    if (!target)
      continue;
    const decodedTarget = decodeURIComponent(target);
    if (await linkTargetFound(path4.dirname(note.absolutePath), decodedTarget, root, canonicalRoot))
      continue;
    issues.push({
      file: note.relativePath,
      id: "link-missing-target",
      message: `repair missing local link '${rawTarget}'`
    });
  }
  return issues;
}
async function linkTargetFound(noteDirectory, decodedTarget, root, canonicalRoot) {
  const resolved = path4.resolve(noteDirectory, decodedTarget);
  if (await exists(resolved))
    return true;
  if (canonicalRoot === path4.resolve(root))
    return false;
  const canonicalDirectory = path4.resolve(canonicalRoot, path4.relative(root, noteDirectory));
  const canonicalTarget = path4.resolve(canonicalDirectory, decodedTarget);
  if (escapesRoot(root, resolved)) {
    return exists(canonicalTarget);
  }
  return await exists(canonicalTarget) && isGitIgnored(canonicalRoot, path4.relative(canonicalRoot, canonicalTarget));
}
async function exists(file) {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}
function isGitIgnored(canonicalRoot, relativePath) {
  const result = spawnSync("git", ["check-ignore", "-q", "--", relativePath], {
    cwd: canonicalRoot,
    shell: false
  });
  return result.status === 0;
}
function escapesRoot(root, resolved) {
  const relative = path4.relative(path4.resolve(root), resolved);
  return relative.startsWith("..") || path4.isAbsolute(relative);
}
function parseRoot(args) {
  const value = args[args.indexOf("--root") + 1];
  return args.includes("--root") && value ? path4.resolve(value) : process.cwd();
}
async function resolveCanonicalRoot(args, env, root) {
  const flagIndex = args.indexOf("--canonical-root");
  const flag = flagIndex >= 0 ? args[flagIndex + 1] : undefined;
  if (flag)
    return path4.resolve(flag);
  if (env.VAULT_CANONICAL_ROOT)
    return path4.resolve(env.VAULT_CANONICAL_ROOT);
  const configHome = env.XDG_CONFIG_HOME ?? path4.join(env.HOME ?? homedir(), ".config");
  try {
    const config = JSON.parse(await readFile3(path4.join(configHome, "my-second-brain-playground", "vault.json"), "utf8"));
    if (config.schemaVersion === 1 && typeof config.vault === "string" && path4.isAbsolute(config.vault)) {
      return config.vault;
    }
  } catch {}
  return path4.resolve(root);
}
function toJsonResult(issues) {
  return {
    schema_version: 1,
    findings: issues.map((issue) => ({
      id: issue.id,
      file: issue.file,
      message: issue.message,
      repair_id: issue.repairId ?? null,
      ...issue.detail ? { detail: issue.detail } : {}
    }))
  };
}
async function runCheck(args, env) {
  const root = parseRoot(args);
  const issues = await checkVault(root, { canonicalRoot: await resolveCanonicalRoot(args, env, root) });
  if (args.includes("--json")) {
    console.log(JSON.stringify(toJsonResult(issues)));
    if (issues.length > 0)
      process.exitCode = 1;
  } else if (issues.length === 0) {
    console.log("Vault check passed.");
  } else {
    for (const issue of issues)
      console.error(`${issue.file}: ${issue.message}`);
    console.error(`
${issues.length} issue${issues.length === 1 ? "" : "s"} found.`);
    process.exitCode = 1;
  }
}

// packages/vault-notes/src/contract.ts
import { randomUUID } from "crypto";
var CONTRACT_VERSION = "2.0.0";
var LEGACY_OUTCOMES = {
  "vault-notes.check": [
    {
      id: "check.passed",
      exitCode: 0,
      trigger: "No governed note has a finding.",
      human: "stdout: Vault check passed.",
      machine: 'stdout: {"schema_version":1,"findings":[]}'
    },
    {
      id: "check.findings",
      exitCode: 1,
      trigger: "One or more governed notes have a finding.",
      human: "stderr: one '<file>: <message>' line per finding, a blank line, then '<n> issue(s) found.'",
      machine: "stdout: {schema_version:1, findings:[{id, file, message, repair_id, detail?}]}"
    },
    {
      id: "check.unreadable",
      exitCode: 1,
      trigger: "schemas/frontmatter-contract.json or a note cannot be read, or a local link holds a malformed % escape (inherited URIError).",
      human: "stderr: the uncaught runtime error; no result",
      machine: "stderr: the uncaught runtime error; stdout empty"
    }
  ],
  "vault-notes.list": [
    {
      id: "list.listed",
      exitCode: 0,
      trigger: "Every selected note has title, type, status and summary.",
      human: "stdout: path, then indented title (type, status) and summary per note; or 'No notes found.'",
      machine: "stdout: {schemaVersion:1, ok:true, notes:[{path, title, type, status, summary}]}"
    },
    {
      id: "list.help",
      exitCode: 0,
      trigger: "--help or -h appears anywhere in the arguments.",
      human: "stdout: the legacy list usage text",
      machine: "stdout: the legacy list usage text"
    },
    {
      id: "list.invalid-usage",
      exitCode: 1,
      trigger: "An unknown argument, a repeated or valueless option, or an unknown family.",
      human: "stderr: INVALID_USAGE: <next action>",
      machine: "stdout: {schemaVersion:1, ok:false, code:'INVALID_USAGE', nextAction, files:[]}"
    },
    {
      id: "list.invalid-notes",
      exitCode: 1,
      trigger: "A selected note lacks title, type, status or summary.",
      human: "stderr: INVALID_NOTES: <next action>, then one file per line",
      machine: "stdout: {schemaVersion:1, ok:false, code:'INVALID_NOTES', nextAction, files}"
    },
    {
      id: "list.failed",
      exitCode: 1,
      trigger: "The vault root or its contract cannot be read.",
      human: "stderr: LIST_FAILED: <next action>",
      machine: "stdout: {schemaVersion:1, ok:false, code:'LIST_FAILED', nextAction, files:[]}"
    }
  ],
  "vault-notes.inventory": [
    {
      id: "inventory.counted",
      exitCode: 0,
      trigger: "Every governed note is counted by family, type and status.",
      human: "stdout: 'Vault notes: <n>' then By family, By type and By status sections",
      machine: "stdout: pretty-printed {total, byFamily, byType, byStatus}"
    },
    {
      id: "inventory.unreadable",
      exitCode: 1,
      trigger: "schemas/frontmatter-contract.json or a note cannot be read.",
      human: "stderr: the uncaught runtime error; no result",
      machine: "stderr: the uncaught runtime error; stdout empty"
    }
  ]
};
var COMMANDS = [
  {
    commandIdentity: "vault-notes.dispatch",
    effectClass: "inspect",
    route: [],
    summary: "Refuse a missing, unknown or malformed command selection."
  },
  {
    commandIdentity: "vault-notes.help",
    effectClass: "inspect",
    route: ["--help"],
    summary: "Show usage, commands and options."
  },
  {
    commandIdentity: "vault-notes.discovery",
    effectClass: "inspect",
    route: ["--discover"],
    summary: "Describe the contract, commands and effect exclusions."
  },
  {
    commandIdentity: "vault-notes.command-discovery",
    effectClass: "inspect",
    route: ["--discover-command"],
    summary: "Describe the possible outcomes of one command."
  },
  {
    commandIdentity: "vault-notes.check",
    effectClass: "inspect",
    route: ["check"],
    summary: "Validate governed notes: frontmatter, routing, identities, body secrets, local links, tickets and folder maps."
  },
  {
    commandIdentity: "vault-notes.list",
    effectClass: "inspect",
    route: ["list"],
    summary: "List current notes from their metadata, optionally for one family."
  },
  {
    commandIdentity: "vault-notes.inventory",
    effectClass: "inspect",
    route: ["inventory"],
    summary: "Count governed notes by family, type and status."
  },
  {
    commandIdentity: "vault-notes.resources",
    effectClass: "inspect",
    route: ["resources"],
    summary: "Propose each project's complete Resources Index and report its findings; writes nothing."
  }
];
var AVAILABLE_PATHS = COMMANDS.map((command) => command.commandIdentity).filter((identity) => identity !== "vault-notes.dispatch").sort();
var STATIONS = {
  usage: {
    causeCode: "USAGE_INVALID_INVOCATION",
    outcome: "refused",
    failureClass: "usage",
    exitCode: 2,
    trigger: "The arguments name no supported command, or an option is unknown, repeated, combined or lacks its value.",
    repairAction: "Choose check, list, inventory, resources, --help, --discover or --discover-command COMMAND_IDENTITY with its listed options and retry.",
    guidance: { nextAction: "Run vault-notes --help and choose a listed command." }
  },
  optionInvalid: {
    causeCode: "SCHEMA_INVALID_INPUT",
    outcome: "refused",
    failureClass: "schema",
    exitCode: 4,
    trigger: "resources: --project is not a lowercase project slug, or --updated is not a real YYYY-MM-DD date.",
    repairAction: "Pass --project as a folder name under projects/ and --updated as YYYY-MM-DD, then retry.",
    guidance: { nextAction: "Correct the option value and retry." }
  },
  contractMissing: {
    causeCode: "DOMAIN_VAULT_NOT_FOUND",
    outcome: "refused",
    failureClass: "domain",
    exitCode: 3,
    trigger: "resources: the selected root has no schemas/frontmatter-contract.json, so it is not a vault root.",
    repairAction: "Pass --root as a vault checkout or Vault Steward candidate root, then retry.",
    guidance: { nextAction: "Select the vault root with --root and retry." }
  },
  projectUnknown: {
    causeCode: "DOMAIN_PRECONDITION_UNMET",
    outcome: "refused",
    failureClass: "domain",
    exitCode: 3,
    trigger: "resources: a --project names no folder of notes under projects/.",
    repairAction: "Name existing project folders with --project, or omit it to propose every project, then retry.",
    guidance: { nextAction: "List projects with vault-notes list --family projects and retry." }
  },
  contractInvalid: {
    causeCode: "SCHEMA_CONFIG_INVALID",
    outcome: "refused",
    failureClass: "schema",
    exitCode: 4,
    trigger: 'resources: schemas/frontmatter-contract.json is not JSON, or its projectResources key is not {"indexFile": "<name>.md"}.',
    repairAction: "Repair schemas/frontmatter-contract.json through a Vault Steward candidate, then retry.",
    guidance: { nextAction: "Read the message for the contract problem and repair it." }
  },
  inspectionFailed: {
    causeCode: "INTERNAL_PREPARATION",
    outcome: "refused",
    failureClass: "internal",
    exitCode: 1,
    trigger: "resources: a vault folder or note cannot be read, or the inspection stopped unexpectedly.",
    repairAction: "Restore read access to the named path, or inspect the runtime error, then retry.",
    guidance: { nextAction: "Read the message for the failing path and retry after repairing it." }
  },
  serialization: {
    causeCode: "INTERNAL_RESULT_SERIALIZATION",
    outcome: "failed",
    failureClass: "internal",
    exitCode: 1,
    trigger: "The result cannot be serialized, or the serialized value fails envelope validation.",
    repairAction: "Inspect the serialization failure before retrying.",
    guidance: { nextAction: "Inspect the runtime and retry the command." }
  },
  emission: {
    causeCode: "INTERNAL_RESULT_EMISSION",
    outcome: "failed",
    failureClass: "internal",
    exitCode: 1,
    trigger: "stdout cannot be written. Machine mode then emits no envelope and nothing on stderr; human mode prints this repair on stderr.",
    repairAction: "Inspect the output stream before retrying.",
    guidance: { nextAction: "Inspect the output stream and retry the command." }
  }
};
var INSPECT_EFFECTS = { completed: [], inventoryComplete: true, remaining: [], uncertain: [] };
function envelope(message, result) {
  return { envelopeVersion: 2, contractVersion: CONTRACT_VERSION, message, availablePaths: AVAILABLE_PATHS, result };
}
function success(commandIdentity, data, message, nextAction) {
  return envelope(message, {
    runId: randomUUID(),
    commandIdentity,
    outcome: "success",
    effectClass: "inspect",
    transactionState: "unchanged",
    causeCode: "SUCCESS_UNCHANGED",
    failureClass: null,
    exitCode: 0,
    data,
    retryable: false,
    repairAction: null,
    effects: INSPECT_EFFECTS,
    nextAction
  });
}
function stationResult(commandIdentity, key, message) {
  const station = STATIONS[key];
  return envelope(message, {
    runId: randomUUID(),
    commandIdentity,
    outcome: station.outcome,
    effectClass: "inspect",
    transactionState: "unchanged",
    causeCode: station.causeCode,
    failureClass: station.failureClass,
    exitCode: station.exitCode,
    data: null,
    retryable: false,
    repairAction: station.repairAction,
    effects: INSPECT_EFFECTS,
    ...station.guidance
  });
}
var IDENTITIES = COMMANDS.map((command) => command.commandIdentity);
var ENVELOPE_KEYS = ["availablePaths", "contractVersion", "envelopeVersion", "message", "result"];
var RESULT_KEYS = [
  "causeCode",
  "commandIdentity",
  "data",
  "effectClass",
  "effects",
  "exitCode",
  "failureClass",
  "nextAction",
  "outcome",
  "repairAction",
  "retryable",
  "runId",
  "transactionState"
];
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function nonblank(value) {
  return typeof value === "string" && value.trim() !== "";
}
function sameKeys(value, keys) {
  return JSON.stringify(Object.keys(value).sort()) === JSON.stringify([...keys].sort());
}
function envelopeHolds(value) {
  if (!sameKeys(value, ENVELOPE_KEYS) || value.envelopeVersion !== 2 || value.contractVersion !== CONTRACT_VERSION)
    return false;
  return nonblank(value.message) && JSON.stringify(value.availablePaths) === JSON.stringify(AVAILABLE_PATHS);
}
function baseHolds(result) {
  if (!sameKeys(result, RESULT_KEYS) || !nonblank(result.runId) || !nonblank(result.nextAction))
    return false;
  if (!IDENTITIES.includes(String(result.commandIdentity)) || result.retryable !== false)
    return false;
  if (result.effectClass !== "inspect" || result.transactionState !== "unchanged")
    return false;
  return JSON.stringify(result.effects) === JSON.stringify(INSPECT_EFFECTS);
}
function armHolds(result) {
  if (result.outcome === "success") {
    return result.causeCode === "SUCCESS_UNCHANGED" && result.failureClass === null && result.exitCode === 0 && result.repairAction === null;
  }
  const station = Object.values(STATIONS).find((entry) => entry.causeCode === result.causeCode);
  if (station === undefined || result.data !== null || result.repairAction !== station.repairAction)
    return false;
  return result.outcome === station.outcome && result.failureClass === station.failureClass && result.exitCode === station.exitCode;
}
function serializeEnvelope(value) {
  try {
    const text = JSON.stringify(value);
    if (typeof text !== "string")
      return null;
    const parsed = JSON.parse(text);
    if (!isRecord(parsed) || !envelopeHolds(parsed) || !isRecord(parsed.result))
      return null;
    return baseHolds(parsed.result) && armHolds(parsed.result) ? `${text}
` : null;
  } catch {
    return null;
  }
}
function discoveryData() {
  return {
    contractVersion: CONTRACT_VERSION,
    generationConventionVersion: CONTRACT_VERSION,
    profile: "simple",
    commands: COMMANDS,
    exitMeanings: { "0": "success", "1": "internal", "2": "usage", "3": "domain", "4": "schema", "75": "transient" },
    signalExits: { "130": "SIGINT", "143": "SIGTERM" },
    effectExclusions: [
      "Never writes, moves or deletes a vault note, schema, script or configuration file.",
      "Never creates a Git commit, branch or worktree, and never runs Vault Steward.",
      "Never contacts a network service; check reads the canonical checkout's .gitignore through git check-ignore only."
    ]
  };
}
var LEGACY_OUTPUT_CONTRACT = {
  kind: "legacy",
  envelope: false,
  exitMeanings: { "0": "success", "1": "findings, refusal or failure; read the outcomes" }
};
var RESOURCES_STATIONS = [
  "usage",
  "optionInvalid",
  "contractMissing",
  "contractInvalid",
  "projectUnknown",
  "inspectionFailed",
  "serialization",
  "emission"
];
var RESOURCES_CONTRACT_KEY = {
  file: "schemas/frontmatter-contract.json",
  key: "projectResources",
  shape: { indexFile: "resources.md" },
  absent: "Resources rules are inactive: check output is unchanged, and resources proposes with indexFile resources.md.",
  invalid: "Any other value, including an unknown key, is a resources-contract-invalid finding and a SCHEMA_CONFIG_INVALID refusal."
};
function resourcesDiscovery() {
  return {
    command: COMMANDS.find((entry) => entry.commandIdentity === "vault-notes.resources"),
    semantics: "possible-stations",
    outputContract: { kind: "contract-core", envelope: true, contractVersion: CONTRACT_VERSION },
    stations: [
      {
        causeCode: "SUCCESS_UNCHANGED",
        outcome: "success",
        failureClass: null,
        exitCode: 0,
        trigger: "Every selected project has a proposal: create, update, current or blocked (markers to repair by hand)."
      },
      ...RESOURCES_STATIONS.map((key) => {
        const { causeCode, outcome, failureClass, exitCode, trigger } = STATIONS[key];
        return { causeCode, outcome, failureClass, exitCode, trigger };
      })
    ],
    findingIds: RESOURCES_FINDING_IDS,
    contractKey: RESOURCES_CONTRACT_KEY
  };
}
function commandDiscovery(commandIdentity) {
  if (commandIdentity === "vault-notes.resources")
    return resourcesDiscovery();
  return {
    command: COMMANDS.find((entry) => entry.commandIdentity === commandIdentity),
    semantics: "possible-outcomes",
    outputContract: LEGACY_OUTPUT_CONTRACT,
    outcomes: LEGACY_OUTCOMES[commandIdentity],
    ...commandIdentity === "vault-notes.check" ? { findingIds: VAULT_FINDING_IDS } : {}
  };
}
function isCommandIdentity(value) {
  return value === "vault-notes.check" || value === "vault-notes.list" || value === "vault-notes.inventory" || value === "vault-notes.resources";
}

// packages/vault-notes/src/inventory.ts
import path5 from "path";
async function inventoryVault(root) {
  const notes = await (await openCatalogue(root)).notes();
  const inventory = {
    total: notes.length,
    byFamily: {},
    byType: {},
    byStatus: {}
  };
  for (const note of notes) {
    increment(inventory.byFamily, note.placement.family ?? "root");
    if (typeof note.frontmatter?.type === "string")
      increment(inventory.byType, note.frontmatter.type);
    if (typeof note.frontmatter?.status === "string")
      increment(inventory.byStatus, note.frontmatter.status);
  }
  return inventory;
}
function increment(counts, key) {
  counts[key] = (counts[key] ?? 0) + 1;
}
function renderSection(title, counts) {
  return [
    title,
    ...Object.entries(counts).sort(([left], [right]) => left.localeCompare(right)).map(([key, count]) => `  ${key}: ${count}`)
  ];
}
function renderInventory(inventory) {
  return [
    `Vault notes: ${inventory.total}`,
    "",
    ...renderSection("By family", inventory.byFamily),
    "",
    ...renderSection("By type", inventory.byType),
    "",
    ...renderSection("By status", inventory.byStatus)
  ].join(`
`);
}
function parseRoot2(args) {
  const value = args[args.indexOf("--root") + 1];
  return args.includes("--root") && value ? path5.resolve(value) : process.cwd();
}
async function runInventory(args) {
  const inventory = await inventoryVault(parseRoot2(args));
  console.log(args.includes("--json") ? JSON.stringify(inventory, null, 2) : renderInventory(inventory));
}

// packages/vault-notes/src/list.ts
import path6 from "path";
var usage = `List current vault notes from their metadata. This command writes nothing.

Usage: bun run list [--family <name>] [--root <path>] [--json]

Examples:
  bun run list --family products
  bun run list --family projects --json

Family indexes are navigation, not a complete catalog. New notes appear here
without an index edit. Paths are relative to the selected vault root.`;

class ListingError extends Error {
  code;
  nextAction;
  files;
  constructor(code, nextAction, files = []) {
    super(code);
    this.code = code;
    this.nextAction = nextAction;
    this.files = files;
  }
}
function parse(args) {
  const options = { root: process.cwd() };
  const seen = new Set;
  for (let index = 0;index < args.length; index++) {
    const flag = args[index];
    if (flag === "--json")
      continue;
    if (flag !== "--root" && flag !== "--family") {
      throw new ListingError("INVALID_USAGE", "Run bun run list --help for supported arguments.");
    }
    const value = args[++index];
    if (!value || value.startsWith("--") || seen.has(flag)) {
      throw new ListingError("INVALID_USAGE", `Provide ${flag} once with a value.`);
    }
    seen.add(flag);
    if (flag === "--root")
      options.root = path6.resolve(value);
    else
      options.family = value;
  }
  return options;
}
async function listNotes(root, family) {
  const catalogue = await openCatalogue(root);
  const families = catalogue.contract.routing.familyReadmes;
  if (family && !Object.hasOwn(families, family)) {
    throw new ListingError("INVALID_USAGE", `Choose a family: ${Object.keys(families).join(", ")}.`);
  }
  const notes = [];
  const invalid = [];
  for (const note of await catalogue.notes((placement) => (!family || placement.family === family) && !placement.isIndex)) {
    const { title, type, status, summary } = note.frontmatter ?? {};
    if (typeof title !== "string" || !title.trim() || typeof type !== "string" || !type.trim() || typeof status !== "string" || !status.trim() || typeof summary !== "string" || !summary.trim()) {
      invalid.push(note.relativePath);
      continue;
    }
    notes.push({ path: note.relativePath, title, type, status, summary });
  }
  if (invalid.length) {
    throw new ListingError("INVALID_NOTES", "Run bun run check and repair the named files before relying on a complete listing.", invalid);
  }
  return notes;
}
async function runList(args) {
  if (args.includes("--help") || args.includes("-h")) {
    console.log(usage);
    return;
  }
  const json = args.includes("--json");
  try {
    const { root, family } = parse(args);
    const notes = await listNotes(root, family);
    if (json)
      console.log(JSON.stringify({ schemaVersion: 1, ok: true, notes }));
    else
      console.log(notes.length ? notes.map((note) => `${note.path}
  ${note.title} (${note.type}, ${note.status})
  ${note.summary}`).join(`

`) : "No notes found.");
  } catch (error) {
    const failure = error instanceof ListingError ? error : new ListingError("LIST_FAILED", "Confirm the vault root is readable and contains schemas/frontmatter-contract.json, then run bun run check.");
    if (json)
      console.log(JSON.stringify({ schemaVersion: 1, ok: false, code: failure.code, nextAction: failure.nextAction, files: failure.files }));
    else
      console.error(`${failure.code}: ${failure.nextAction}${failure.files.length ? `
${failure.files.join(`
`)}` : ""}`);
    process.exitCode = 1;
  }
}

// packages/vault-notes/src/resources-command.ts
import path7 from "path";
var IDENTITY = "vault-notes.resources";
var NEXT_ACTION = "Write each create or update proposal's content inside a Vault Steward candidate, then run vault-notes check there.";

class Refusal extends Error {
  station;
  constructor(station, message) {
    super(message);
    this.station = station;
  }
}
function refuse(station, message) {
  return { envelope: stationResult(IDENTITY, station, message), human: "" };
}
async function runResources(args, cwd, today) {
  try {
    const options = parseOptions(args, cwd, today);
    const catalogue = await openVault(options.root);
    return await propose(catalogue, options);
  } catch (error) {
    if (error instanceof Refusal)
      return refuse(error.station, error.message);
    const reason = error instanceof Error ? error.message : String(error);
    return refuse("inspectionFailed", `The vault could not be inspected: ${reason}.`);
  }
}
function parseOptions(args, cwd, today) {
  const values = readOptionValues(args.filter((arg) => arg !== "--json"));
  if (new Set(values.projects).size !== values.projects.length)
    throw new Refusal("usage", "Name each --project once.");
  const badProject = values.projects.find((project) => !/^[a-z0-9][a-z0-9-]*$/.test(project));
  if (badProject !== undefined)
    throw new Refusal("optionInvalid", `--project '${badProject}' is not a lowercase project slug.`);
  const updated = values.updated ?? today;
  if (!isCalendarDate(updated))
    throw new Refusal("optionInvalid", `--updated '${updated}' is not a real YYYY-MM-DD date.`);
  return { root: path7.resolve(cwd, values.root ?? "."), projects: values.projects, updated };
}
var OPTION_KEYS = new Map([
  ["--project", "projects"],
  ["--root", "root"],
  ["--updated", "updated"]
]);
function readOptionValues(args) {
  const values = { projects: [] };
  for (let index = 0;index < args.length; index += 2) {
    const [name, value] = [String(args[index]), args[index + 1]];
    if (value === undefined || value.startsWith("--"))
      throw new Refusal("usage", `${name} needs a value.`);
    const key = OPTION_KEYS.get(name);
    if (key === undefined)
      throw new Refusal("usage", `resources does not accept '${name}'.`);
    if (key === "projects")
      values.projects.push(value);
    else if (values[key] !== undefined)
      throw new Refusal("usage", `${name} is given more than once.`);
    else
      values[key] = value;
  }
  return values;
}
function isCalendarDate(value) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value))
    return false;
  const date = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(date.getTime()) && date.toISOString().startsWith(value);
}
async function openVault(root) {
  try {
    return await openCatalogue(root);
  } catch (error) {
    if (error instanceof SyntaxError) {
      throw new Refusal("contractInvalid", `schemas/frontmatter-contract.json is not valid JSON: ${error.message}.`);
    }
    if (error.code === "ENOENT") {
      throw new Refusal("contractMissing", `${root} has no schemas/frontmatter-contract.json.`);
    }
    throw error;
  }
}
async function propose(catalogue, options) {
  const policy = readResourcesPolicy(catalogue.contract);
  if (policy.state === "invalid")
    throw new Refusal("contractInvalid", `projectResources is invalid: ${policy.reason}.`);
  const notes = await catalogue.notes((placement) => placement.project !== null);
  const known = projectsOf(notes);
  const unknown = options.projects.filter((project) => !known.includes(project));
  if (unknown.length > 0)
    throw new Refusal("projectUnknown", `No notes under projects/ for: ${unknown.join(", ")}.`);
  const selected = options.projects.length > 0 ? options.projects : known;
  const proposals = proposeResources(notes, selected, policy.indexFile, options.updated);
  const data = { active: policy.state === "active", indexFile: policy.indexFile, updated: options.updated, projects: proposals };
  const message = `Proposed ${proposals.length} Resources Index${proposals.length === 1 ? "" : "es"}; nothing was written.`;
  return { envelope: success(IDENTITY, data, message, NEXT_ACTION), human: renderHuman(data) };
}
function renderHuman(data) {
  const rules = data.active ? "active" : "inactive until the contract declares projectResources";
  const lines = [`Resources Index proposals (${data.indexFile}; check rules ${rules}):`];
  for (const proposal of data.projects) {
    const counts = `${proposal.notes.length} notes, ${proposal.folderMaps.length} folder maps`;
    lines.push(`${proposal.indexPath}: ${proposal.state} (${counts}, ${proposal.findings.length} findings)`);
    for (const finding of proposal.findings)
      lines.push(`  ${finding.id} ${finding.file}: ${finding.message}`);
  }
  lines.push("", "Content is in --json output: result.data.projects[].content. Nothing was written.");
  return lines.join(`
`);
}

// packages/vault-notes/src/main.ts
var LEGACY_RUNNERS = new Map([
  ["check", (args) => runCheck(args, process.env)],
  ["list", runList],
  ["inventory", runInventory]
]);
var USAGE = [
  "Usage:",
  "  vault-notes check [--root PATH] [--canonical-root PATH] [--json]",
  "  vault-notes list [--family NAME] [--root PATH] [--json] [--help]",
  "  vault-notes inventory [--root PATH] [--json]",
  "  vault-notes resources [--project SLUG]... [--root PATH] [--updated YYYY-MM-DD] [--json]",
  "  vault-notes --help [--json] | --discover [--json] | --discover-command COMMAND_IDENTITY [--json]"
];
var OPTIONS = [
  { name: "--root", valueName: "PATH", summary: "Vault root to inspect; default the current directory." },
  {
    name: "--canonical-root",
    valueName: "PATH",
    summary: "check only: canonical checkout for escaping or gitignored link targets; else VAULT_CANONICAL_ROOT, else vault.json."
  },
  { name: "--family", valueName: "NAME", summary: "list only: one family from the vault contract." },
  { name: "--project", valueName: "SLUG", summary: "resources only: a project folder under projects/; repeatable; default every project." },
  {
    name: "--updated",
    valueName: "YYYY-MM-DD",
    summary: "resources only: the 'updated' date of a newly created index; default today. Existing indexes keep theirs."
  },
  { name: "--json", valueName: null, summary: "Machine output: legacy JSON for check, list and inventory; one 2.0 envelope otherwise." },
  { name: "--discover", valueName: null, summary: "Describe the contract, commands and effect exclusions." },
  { name: "--discover-command", valueName: "COMMAND_IDENTITY", summary: "Describe one command's possible outcomes." },
  { name: "--help", valueName: null, summary: "Show this help." }
];
var HUMAN_HELP = [
  "Inspect vault notes. Every command is read-only.",
  "",
  ...USAGE,
  "",
  "check, list and inventory keep the vault's legacy output byte-for-byte and emit no",
  "Contract Core 2.0 envelope; resources, help and discovery do. resources proposes each",
  "project's complete Resources Index (resources.md) and its findings; it writes nothing.",
  "",
  "Options:",
  ...OPTIONS.map((option) => `  ${option.name}${option.valueName === null ? "" : ` ${option.valueName}`}  ${option.summary}`),
  "",
  "Examples:",
  "  vault-notes check --root ~/code/my-second-brain-playground",
  "  vault-notes list --family projects --json",
  "  vault-notes resources --project my-second-brain --root ~/code/my-second-brain-playground --json",
  "  vault-notes --discover-command vault-notes.check --json"
].join(`
`);

class UsageError extends Error {
}
function selectControl(args) {
  const rest = args.filter((arg) => arg !== "--json");
  const [first, second, ...extra] = rest;
  if (extra.length === 0 && second === undefined && (first === "--help" || first === "-h"))
    return { kind: "help" };
  if (extra.length === 0 && second === undefined && first === "--discover")
    return { kind: "discover" };
  if (extra.length === 0 && first === "--discover-command" && second !== undefined)
    return { kind: "discover-command", selector: second };
  throw new UsageError(first === undefined ? "Choose a command." : "Choose a supported command.");
}
function control(selection) {
  if (selection.kind === "help") {
    const data2 = {
      summary: "Inspect-only vault notes: check, list, inventory and resources.",
      usage: USAGE.slice(1).map((line) => line.trim()),
      commands: COMMANDS,
      options: OPTIONS
    };
    return { envelope: success("vault-notes.help", data2, "Show help.", "Choose a command from the usage lines."), human: HUMAN_HELP };
  }
  if (selection.kind === "discover") {
    const human2 = "Commands: check (inspect, legacy output), list (inspect, legacy output), inventory (inspect, legacy output), resources (inspect, 2.0)";
    return { envelope: success("vault-notes.discovery", discoveryData(), "Describe commands.", "Choose a command to run."), human: human2 };
  }
  const { selector } = selection;
  if (!isCommandIdentity(selector))
    throw new UsageError("--discover-command needs a listed command identity.");
  const data = commandDiscovery(selector);
  const rows = "stations" in data ? data.stations.map((row) => `${row.causeCode}/exit ${row.exitCode}`) : data.outcomes.map((row) => `${row.id}/exit ${row.exitCode}`);
  const human = `${selector}: ${rows.join(", ")}`;
  return {
    envelope: success("vault-notes.command-discovery", data, `Describe ${selector}.`, "Read the outcomes; discovery reports no live state."),
    human
  };
}
function controlIdentity(args) {
  if (args.includes("--help") || args.includes("-h"))
    return "vault-notes.help";
  if (args.includes("--discover"))
    return "vault-notes.discovery";
  if (args.includes("--discover-command"))
    return "vault-notes.command-discovery";
  return "vault-notes.dispatch";
}
function write(text, json) {
  try {
    process.stdout.write(text);
    return null;
  } catch {
    if (!json)
      process.stderr.write(`${STATIONS.emission.trigger} Repair: ${STATIONS.emission.repairAction}
`);
    return 1;
  }
}
function emitMachine(output) {
  const text = serializeEnvelope(output.envelope);
  if (text !== null)
    return write(text, true) ?? output.envelope.result.exitCode;
  const fallback = serializeEnvelope(stationResult(output.envelope.result.commandIdentity, "serialization", STATIONS.serialization.trigger));
  return fallback === null ? 1 : write(fallback, true) ?? 1;
}
function emit(output, json) {
  if (json)
    return emitMachine(output);
  const { exitCode, repairAction } = output.envelope.result;
  if (exitCode !== 0) {
    process.stderr.write(`${output.envelope.message} Repair: ${String(repairAction)}
`);
    return exitCode;
  }
  return write(`${output.human}
`, false) ?? exitCode;
}
function runControl(args) {
  const json = args.includes("--json");
  let output;
  try {
    output = control(selectControl(args));
  } catch (error) {
    const message = error instanceof UsageError ? error.message : "The command failed unexpectedly before producing a result.";
    output = { envelope: stationResult(controlIdentity(args), error instanceof UsageError ? "usage" : "serialization", message), human: "" };
  }
  return emit(output, json);
}
function localDate(now = new Date) {
  const pad = (value) => String(value).padStart(2, "0");
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
}
async function dispatch(argv) {
  const [command, ...rest] = argv;
  const legacy = LEGACY_RUNNERS.get(command ?? "");
  if (legacy)
    return legacy(rest);
  const control2 = ["--help", "-h", "--discover", "--discover-command"];
  if (command === "resources" && !rest.some((arg) => control2.includes(arg))) {
    process.exitCode = emit(await runResources(rest, process.cwd(), localDate()), rest.includes("--json"));
    return;
  }
  process.exitCode = runControl(command === "resources" ? rest : argv);
}
await dispatch(process.argv.slice(2));
