import { describe, expect, test } from "bun:test"
import { emitMachine, encodeFallbackEnvelope, inspectFallbackEncoding, internalFailureEnvelope, routeRawArgv } from "../../src/cli.ts"
import { CAUSE, COMMANDS, discovery, EXIT, MachineEnvelopeSchema, STATIONS } from "../../src/command-contract.ts"
import type { ExecutionFacts } from "../../src/model.ts"
import { parseFaults } from "../../src/runtime.ts"
import { EXPECTED_COMMAND_IDENTITIES as IDENTITIES } from "../helpers/command-identity-oracle.ts"
const STATION_IDENTITIES = IDENTITIES
function facts(overrides: Partial<ExecutionFacts>): ExecutionFacts { return { commandIdentity: "repair-lab.apply", runIdentity: "run-test", domainOutcome: "success", effectClass: "repository-local", transactionState: "completed", completedEffectIds: ["effect.update-index", "effect.write-journal"], remainingEffectIds: [], stationLabel: "repair-lab.authorized-apply", guidance: { kind: "next-action", target: "repair-lab inspect" }, ...overrides } }
function valid(): Record<string, unknown> { return { envelopeVersion: 2, contractVersion: "2.0.0", message: "ok", availablePaths: ["repair-lab.help", "repair-lab.status"], result: { runId: "run-x", commandIdentity: "repair-lab.status", outcome: "success", failureClass: null, causeCode: "SUCCESS_UNCHANGED", effectClass: "inspect", transactionState: "unchanged", retryable: false, nextAction: "repair-lab inspect", repairAction: null, data: { a: 1 }, effects: { completed: [], remaining: [], uncertain: [], inventoryComplete: true }, exitCode: 0 } } }

describe("discovery and exit map", () => {
	test("discovery is the exact accepted DiscoveryData shape", () => { const document = discovery(); expect(Object.keys(document).sort()).toEqual(["commands", "contractVersion", "effectExclusions", "exitMeanings", "generationConventionVersion", "profile", "signalExits"]); expect(document.contractVersion).toBe("2.0.0"); expect(document.generationConventionVersion).toBe("2.0.0"); expect(document.profile).toBe("complex"); expect(document.commands.map((command) => command.commandIdentity)).toEqual([...IDENTITIES]); expect(document.exitMeanings).toEqual({ "0": "success", "1": "internal", "2": "usage", "3": "domain", "4": "schema", "75": "transient" }); expect(document.signalExits).toEqual({ "130": "SIGINT", "143": "SIGTERM" }); expect(document.effectExclusions).toEqual(["diagnostic file and journal maintenance"]) })
	test("the exit map is the contract's numeric mapping", () => { expect(EXIT).toEqual({ success: 0, internal: 1, usage: 2, domain: 3, schema: 4, transient: 75 }) })
	test("every cause code carries its class prefix", () => { for (const [code, failureClass] of Object.entries(CAUSE)) if (failureClass !== null) expect(code.startsWith(`${failureClass.toUpperCase()}_`)).toBe(true) })
	test("COMMANDS derive discovery from the same owner", () => { expect(COMMANDS.map((command) => command.commandIdentity)).toEqual([...IDENTITIES]) })
	test("declares the existing non-command dispatch identity for observed-is-declared validation", () => { expect(COMMANDS.find((command) => command.commandIdentity === "repair-lab.dispatch")).toEqual({ commandIdentity: "repair-lab.dispatch", route: [], effectClass: "inspect", summary: "Refuse missing or incompatible command selection" }) })
})

describe("MachineEnvelopeSchema", () => {
	test("accepts a valid strict 2.0 envelope and rejects an extra key", () => { expect(MachineEnvelopeSchema.safeParse(valid()).success).toBe(true); expect(MachineEnvelopeSchema.safeParse({ ...valid(), extra: true }).success).toBe(false) })
	test("accepts null as successful JsonValue data", () => { expect(MachineEnvelopeSchema.safeParse({ ...valid(), result: { ...(valid().result as Record<string, unknown>), data: null } }).success).toBe(true) })
	test("rejects success with a failure class", () => { expect(MachineEnvelopeSchema.safeParse({ ...valid(), result: { ...(valid().result as Record<string, unknown>), failureClass: "domain" } }).success).toBe(false) })
	test("rejects a cause code whose class disagrees", () => { expect(MachineEnvelopeSchema.safeParse({ ...valid(), result: { ...(valid().result as Record<string, unknown>), outcome: "refused", failureClass: "domain", causeCode: "USAGE_INVALID_INVOCATION", data: null, repairAction: "repair" } }).success).toBe(false) })
	test("rejects both nextAction and handoff", () => { expect(MachineEnvelopeSchema.safeParse({ ...valid(), result: { ...(valid().result as Record<string, unknown>), handoff: { owner: "operator", reason: "r", inspect: ["repair-lab inspect"] } } }).success).toBe(false) })
	test("rejects missing guidance", () => { const result = { ...(valid().result as Record<string, unknown>) }; delete result.nextAction; expect(MachineEnvelopeSchema.safeParse({ ...valid(), result }).success).toBe(false) })
	test("rejects an unresolved success and a retryable unknown result", () => { expect(MachineEnvelopeSchema.safeParse({ ...valid(), result: { ...(valid().result as Record<string, unknown>), transactionState: "unknown" } }).success).toBe(false); expect(MachineEnvelopeSchema.safeParse({ ...valid(), result: { ...(valid().result as Record<string, unknown>), outcome: "failed", effectClass: "repository-local", transactionState: "unknown", causeCode: "INTERNAL_RESULT_UNKNOWN", failureClass: "internal", exitCode: 1, data: null, retryable: true, retryDelayMilliseconds: 25, repairAction: "inspect", effects: { completed: [], remaining: [], uncertain: ["effect.one"], inventoryComplete: true }, handoff: { owner: "operator", reason: "r", inspect: ["repair-lab inspect"] } } }).success).toBe(false) })
	test("rejects a non-string message and a bad enum member", () => { expect(MachineEnvelopeSchema.safeParse({ ...valid(), message: 42 }).success).toBe(false); expect(MachineEnvelopeSchema.safeParse({ ...valid(), result: { ...(valid().result as Record<string, unknown>), outcome: "maybe" } }).success).toBe(false) })
	test("closes command identities and cause codes over the declared 2.0 vocabulary", () => {
		expect(MachineEnvelopeSchema.safeParse({ ...valid(), result: { ...(valid().result as Record<string, unknown>), commandIdentity: "repair-lab.future" } }).success).toBe(false)
		expect(MachineEnvelopeSchema.safeParse({ ...valid(), result: { ...(valid().result as Record<string, unknown>), outcome: "refused", failureClass: "usage", causeCode: "USAGE_FUTURE", exitCode: 2, data: null, repairAction: "repair" } }).success).toBe(false)
		for (const commandIdentity of IDENTITIES) expect(MachineEnvelopeSchema.safeParse({ ...valid(), result: { ...(valid().result as Record<string, unknown>), commandIdentity } }).success).toBe(true)
	})
})

describe("raw argv routing", () => { test("identity is derived before strict parsing", () => { expect(routeRawArgv(["status", "--bogus", "--json"]).identity).toBe("repair-lab.status"); expect(routeRawArgv(["--discover", "--bogus", "--json"]).identity).toBe("repair-lab.discovery"); expect(routeRawArgv(["apply", "--preview", "--bogus"]).identity).toBe("repair-lab.preview"); expect(routeRawArgv(["recover", "--bogus"]).identity).toBe("repair-lab.recover"); expect(routeRawArgv(["repair", "--apply", "--retry-once"]).identity).toBe("repair-lab.repair-retry"); expect(routeRawArgv(["inspect", "--include-diagnostics"]).identity).toBe("repair-lab.inspect-diagnostics"); expect(routeRawArgv(["--json"]).identity).toBe("repair-lab.dispatch") }) })
describe("fault channel", () => { test("one domain fault plus one egress fault compose; duplicates and two of a kind are rejected", () => { expect(parseFaults(undefined)).toEqual({ domain: null, egress: null }); expect(parseFaults("throw-internal+egress-non-json:cycle")).toEqual({ domain: "throw-internal", egress: { kind: "egress-non-json", variant: "cycle" } }); expect(parseFaults("halt-before-effect:effect.update-index")).toEqual({ domain: { kind: "halt-before-effect", effectId: "effect.update-index" }, egress: null }); expect(parseFaults("throw-internal+silent-no-op")).toBeNull(); expect(parseFaults("egress-non-json:cycle+egress-schema-invalid:extra-key")).toBeNull(); expect(parseFaults("throw-internal+throw-internal")).toBeNull(); expect(parseFaults("nope")).toBeNull() }) })

describe("C0 fallback builder", () => {
	const ADMITTED: Array<[ExecutionFacts["domainOutcome"], ExecutionFacts["transactionState"], string, string]> = [["refused", "unchanged", "INTERNAL_PREPARATION", "refused"], ["failed", "unchanged", "INTERNAL_RESULT_UNCHANGED", "failed"], ["success", "unchanged", "INTERNAL_RESULT_UNCHANGED", "failed"], ["success", "completed", "INTERNAL_RESULT_COMPLETED", "failed"], ["failed", "completed", "INTERNAL_RESULT_COMPLETED", "failed"], ["failed", "partially-completed", "INTERNAL_RESULT_PARTIAL", "failed"], ["failed", "unknown", "INTERNAL_RESULT_UNKNOWN", "failed"], ["unknown", "unknown", "INTERNAL_RESULT_UNKNOWN", "failed"]]
	test("every admitted case validates, keeps the transaction state and maps to the accepted cause", () => { for (const [domainOutcome, transactionState, cause, outcome] of ADMITTED) { const envelope = internalFailureEnvelope(facts({ domainOutcome, transactionState, completedEffectIds: transactionState === "completed" || transactionState === "partially-completed" ? ["effect.update-index"] : [], remainingEffectIds: transactionState === "partially-completed" ? ["effect.write-journal"] : [] }), ["issue"]); expect(envelope).not.toBeNull(); if (envelope === null) throw new Error("admitted fallback was lost"); expect(MachineEnvelopeSchema.safeParse(envelope).success).toBe(true); expect(String(envelope.result.causeCode)).toBe(cause); expect(String(envelope.result.outcome)).toBe(outcome); expect(String(envelope.result.transactionState)).toBe(transactionState) } })
	test("inadmissible fact combinations terminate instead of normalizing to another state", () => { expect(internalFailureEnvelope(facts({ domainOutcome: "refused", transactionState: "completed" }), ["issue"])).toBeNull(); expect(internalFailureEnvelope(facts({ domainOutcome: "failed", effectClass: "inspect", transactionState: "completed" }), ["issue"])).toBeNull(); expect(internalFailureEnvelope(facts({ domainOutcome: "failed", transactionState: "partially-completed", completedEffectIds: ["effect.update-index"], remainingEffectIds: [] }), ["issue"])).toBeNull() })
	test("the production fallback encoder accepts depth 8 at its guard and rejects depth 9", () => { const envelope = internalFailureEnvelope(facts({ domainOutcome: "failed", transactionState: "unchanged", completedEffectIds: [], remainingEffectIds: [] }), ["issue"]); expect(envelope).not.toBeNull(); if (envelope === null) throw new Error("fallback missing"); const nested = (depth: number): unknown => depth === 0 ? "leaf" : { value: nested(depth - 1) }; expect(inspectFallbackEncoding(nested(8))).toEqual({ ok: false, reason: "schema" }); expect(inspectFallbackEncoding(nested(9))).toEqual({ ok: false, reason: "depth-or-json" }); expect(encodeFallbackEnvelope(envelope)).not.toBeNull() })
	test("completed facts with a non-JSON candidate yield completed, never unchanged; refused facts stay refused", () => { const out: string[] = []; const io = { stdout: (text: string) => out.push(text), stderr: () => {} }; const cyclic: Record<string, unknown> = { ...valid() }; cyclic.self = cyclic; expect(emitMachine(cyclic, facts({}), io)).toBe(1); const result = (JSON.parse(out[0] as string) as { result: Record<string, unknown> }).result; expect(result.transactionState).toBe("completed"); expect(result.causeCode).toBe("INTERNAL_RESULT_COMPLETED"); out.length = 0; expect(emitMachine({ ...valid(), message: 5 }, facts({ domainOutcome: "refused", transactionState: "unchanged", completedEffectIds: [], remainingEffectIds: [] }), io)).toBe(1); const refused = (JSON.parse(out[0] as string) as { result: Record<string, unknown> }).result; expect(refused.outcome).toBe("refused"); expect(refused.causeCode).toBe("INTERNAL_PREPARATION") })
	test("a valid candidate is written once with the exit of its failure class", () => { const out: string[] = []; expect(emitMachine(valid(), facts({}), { stdout: (text) => out.push(text), stderr: () => {} })).toBe(0); expect(out).toHaveLength(1); expect(out[0]?.endsWith("\n")).toBe(true) })
})
describe("STATIONS enumeration", () => { test("declares every command route and the accepted non-command dispatch refusal", () => { expect([...new Set(STATIONS.map((row) => row.commandIdentity as string))].sort()).toEqual([...STATION_IDENTITIES].sort()); expect(STATIONS.length).toBeGreaterThan(0) }) })
