/**
 * Rendering: derived artifacts to TypeScript source text.
 *
 * These functions return strings. They never write a file, create a directory
 * or compute a manifest  -  the generation pipeline that replaces the complete
 * Generated Artifact Set as one unit owns all of that. Keeping rendering pure
 * is what lets the same bytes be produced in isolation for drift verification
 * and compared without touching a working tree.
 *
 * Determinism is a contract, not an accident: every collection is emitted in a
 * sorted order and every object literal has a fixed key order, so rendering the
 * same IR twice produces byte-identical text.
 */
import type { CommandFacadeContract } from '@side-quest/cli-command-facade'
import { pascal } from './emit-derivation.ts'
import type { SemanticExpectationRow } from './emit-expectations.ts'
import type { DerivedStation } from './emit-stations.ts'
import type { SpecificationIr } from './ir.ts'

/** A generated file: its consumer-relative path and its complete contents. */
export interface RenderedModule {
	readonly path: string
	readonly contents: string
}

/**
 * The header every generated artifact carries.
 *
 * A Generated Artifact Set is a disposable projection. The header says so in
 * the file itself, so a maintainer who opens one is told to repair the
 * specification rather than the output.
 */
function header(
	ir: SpecificationIr,
	digest: string,
	conventions: readonly string[] = [],
): string {
	return [
		'// Generated by the Agent-Native State Machine Generator. Do not edit.',
		'//',
		'// This file is one artifact of a disposable Generated Artifact Set derived',
		`// from the Admitted State-Machine Specification for ${ir.specMeta.product}.`,
		'// Edit the specification and regenerate; a hand edit is Generated Artifact',
		'// Drift and will be refused.',
		'//',
		`// specification digest: ${digest}`,
		`// input schema version: ${ir.specMeta.inputSchemaVersion}`,
		// Derivation conventions are stated, never hidden. A reader must be able
		// to tell an admitted meaning from one the generator inferred, and each
		// line here is an open item for stage-5 admission.
		...(conventions.length === 0
			? []
			: [
					'//',
					'// Derivation conventions (inferred, not admitted; pending stage-5',
					'// product-owner admission):',
					...conventions.map((line) => `//   - ${line}`),
				]),
		'',
	].join('\n')
}

/** JSON string literal with double quotes normalized to the repo's single. */
function lit(value: string): string {
	return JSON.stringify(value)
}

/**
 * Renders the Branch Station Catalog module.
 *
 * Emits `contract_id` only; the legacy `data.contract` branch is never
 * produced. The station array is emitted as
 * `const satisfies readonly BranchStation[]` so the facade's own types judge
 * the emission at compile time rather than at review time, and `STATION_IDS`
 * as a const tuple so consumers get compile-time scenario exhaustiveness.
 */
export function renderStationCatalog(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly stations: readonly DerivedStation[]
	/** Consumer-relative catalog path; one station-array export per file. */
	readonly catalogPath: string
	/** Exported symbol prefix, e.g. `vaultGit`. */
	readonly symbolPrefix: string
	/** Screaming-case prefix for the id tuple, e.g. `VAULT_GIT`. */
	readonly constantPrefix: string
	/** The consumer's discovery projection function to import. */
	readonly discoveryImport: { readonly symbol: string; readonly from: string }
	/** Inferred bindings named in the header. */
	readonly conventions?: readonly string[]
}): RenderedModule {
	const {
		ir,
		digest,
		stations,
		catalogPath,
		symbolPrefix,
		constantPrefix,
		discoveryImport,
		conventions = [],
	} = input
	const sorted = [...stations].sort((a, b) =>
		a.station.id.localeCompare(b.station.id),
	)

	const lines: string[] = [
		header(ir, digest, conventions),
		'import {',
		'\ttype BranchStation,',
		'\ttype BranchStationEvidence,',
		'\tfindBranchStationCatalogDrift,',
		'\tprojectStationMap,',
		"} from '@side-quest/cli-command-facade'",
		`import { ${discoveryImport.symbol} } from ${lit(discoveryImport.from)}`,
		'',
		`const CATALOG_PATH = ${lit(catalogPath)}`,
		'',
		'/** Stable Branch Station ids. Spread into `satisfies Record<StationId, ...>`',
		' * to get compile-time scenario exhaustiveness. */',
		`export const ${constantPrefix}_STATION_IDS = [`,
		...sorted.map((derived) => `\t${lit(derived.station.id)},`),
		'] as const',
		'',
		`export type ${pascal(symbolPrefix)}StationId =`,
		`\t(typeof ${constantPrefix}_STATION_IDS)[number]`,
		'',
		'/** Package-owned Branch Station Catalog. */',
		`export const ${symbolPrefix}BranchStationCatalog = [`,
		...sorted.map((derived) => renderStation(derived)),
		'] as const satisfies readonly BranchStation[]',
		'',
		'/** Find catalog drift against live command discovery. */',
		`export function find${pascal(symbolPrefix)}BranchStationCatalogDrift(`,
		'\tevidence: readonly BranchStationEvidence[] = [],',
		') {',
		'\treturn findBranchStationCatalogDrift({',
		`\t\tdiscovery: ${discoveryImport.symbol}(),`,
		`\t\tcatalog: ${symbolPrefix}BranchStationCatalog,`,
		'\t\tevidence,',
		'\t\tpath: CATALOG_PATH,',
		'\t})',
		'}',
		'',
		'/** Project the Station Map for this package. */',
		`export function project${pascal(symbolPrefix)}StationMap(`,
		'\tevidence: readonly BranchStationEvidence[] = [],',
		') {',
		'\treturn projectStationMap({',
		`\t\tdiscovery: ${discoveryImport.symbol}(),`,
		`\t\tcatalog: ${symbolPrefix}BranchStationCatalog,`,
		'\t\tevidence,',
		'\t\tpath: CATALOG_PATH,',
		'\t})',
		'}',
		'',
	]

	return { path: catalogPath, contents: lines.join('\n') }
}

/** One station literal, keys in a fixed order so rendering is deterministic. */
function renderStation(derived: DerivedStation): string {
	const s = derived.station
	const parts = [
		`\t\tid: ${lit(s.id)},`,
		`\t\tcommand: ${lit(s.command)},`,
		`\t\tclassification: ${lit(s.classification)},`,
		`\t\tintent: ${lit(s.intent)},`,
		`\t\ttrigger: ${lit(s.trigger)},`,
	]
	if (s.expectedExitCode !== undefined) {
		parts.push(`\t\texpectedExitCode: ${s.expectedExitCode},`)
	}
	if (s.expectedEnvelopeStatus !== undefined) {
		parts.push(`\t\texpectedEnvelopeStatus: ${lit(s.expectedEnvelopeStatus)},`)
	}
	if (s.expectedResultContractId !== undefined) {
		parts.push(
			`\t\texpectedResultContractId: ${lit(s.expectedResultContractId)},`,
		)
	}
	if (s.expectedErrorCode !== undefined) {
		parts.push(`\t\texpectedErrorCode: ${lit(s.expectedErrorCode)},`)
	}
	if (s.expectedActionId !== undefined) {
		parts.push(`\t\texpectedActionId: ${lit(s.expectedActionId)},`)
	}
	if (s.expectedContinuationId !== undefined) {
		parts.push(`\t\texpectedContinuationId: ${lit(s.expectedContinuationId)},`)
	}
	parts.push(`\t\tmutationExpectation: ${lit(s.mutationExpectation)},`)
	return ['\t{', ...parts, '\t},'].join('\n')
}

/**
 * Renders the Command Surface Contract module.
 *
 * The record is emitted `as const satisfies Record<string, CommandFacadeContract>`
 * so the facade's type is the judge of the emission.
 */
export function renderCommandContracts(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly contracts: Readonly<Record<string, CommandFacadeContract>>
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	const { ir, digest, contracts, path, symbolPrefix, conventions = [] } = input
	const commands = Object.keys(contracts).sort()

	const lines: string[] = [
		header(ir, digest, conventions),
		"import type { CommandFacadeContract } from '@side-quest/cli-command-facade'",
		'',
		"/** The single generated static owner of this product's public CLI meaning. */",
		`export const ${symbolPrefix}CommandContracts = {`,
		...commands.map((command) =>
			renderContract(command, contracts[command] as CommandFacadeContract),
		),
		'} as const satisfies Record<string, CommandFacadeContract>',
		'',
		`export type ${pascal(symbolPrefix)}Command =`,
		`\tkeyof typeof ${symbolPrefix}CommandContracts`,
		'',
	]

	return { path, contents: lines.join('\n') }
}

function renderContract(
	command: string,
	contract: CommandFacadeContract,
): string {
	const flagKeys = Object.keys(contract.flags).sort()
	const exitKeys = Object.keys(contract.exitCodes).sort()
	const parts = [
		`\t\tscript: ${lit(contract.script)},`,
		`\t\tsummary: ${lit(contract.summary)},`,
		`\t\tusage: [${contract.usage.map(lit).join(', ')}],`,
		`\t\tjson: ${contract.json},`,
		`\t\taudience: ${lit(contract.audience)},`,
		`\t\tmutation: ${lit(contract.mutation)},`,
	]
	if (contract.sideEffects) {
		parts.push(
			`\t\tsideEffects: [${contract.sideEffects.map(lit).join(', ')}],`,
		)
	}
	if (contract.executionModes) {
		parts.push(
			`\t\texecutionModes: [${contract.executionModes.map(lit).join(', ')}],`,
		)
	}
	if (contract.outputModes) {
		parts.push(
			`\t\toutputModes: [${contract.outputModes.map(lit).join(', ')}],`,
		)
	}
	if (contract.resultContract) {
		const rc = contract.resultContract
		parts.push(
			`\t\tresultContract: { id: ${lit(rc.id)}, schema_version: ${
				typeof rc.schema_version === 'string'
					? lit(rc.schema_version)
					: rc.schema_version
			} },`,
		)
	}
	parts.push(
		'\t\tflags: {',
		...flagKeys.map((flag) => `\t\t\t${lit(flag)}: { type: 'boolean' },`),
		'\t\t},',
		'\t\texitCodes: {',
		...exitKeys.map(
			(code) =>
				`\t\t\t${lit(code)}: ${lit(contract.exitCodes[code] as string)},`,
		),
		'\t\t},',
	)
	return [`\t${lit(command)}: {`, ...parts, '\t},'].join('\n')
}

/**
 * Renders the generator-owned semantic expectation table.
 *
 * The table is a separate module from the catalog on purpose: it joins to
 * stations on `expectedActionId` and must never be mistaken for facade
 * surface. Emitting it beside the catalog would invite exactly that.
 */
export function renderExpectationTable(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly rows: readonly SemanticExpectationRow[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	const { ir, digest, rows, path, symbolPrefix, conventions = [] } = input
	const sorted = [...rows].sort((a, b) =>
		a.stationId.localeCompare(b.stationId),
	)

	const lines: string[] = [
		header(ir, digest, conventions),
		'/**',
		' * Generator-owned semantic expectations, joined to Branch Stations on the',
		" * facade's existing `expectedActionId` string. These meanings are",
		" * deliberately absent from the facade's own types.",
		' */',
		`export const ${symbolPrefix}SemanticExpectations = [`,
		...sorted.map((row) => renderRow(row)),
		'] as const',
		'',
	]

	return { path, contents: lines.join('\n') }
}

function renderRow(row: SemanticExpectationRow): string {
	const parts = [
		`\t\tstationId: ${lit(row.stationId)},`,
		`\t\texpectedActionId: ${lit(row.expectedActionId)},`,
		`\t\tstate: ${lit(row.state)},`,
		`\t\tcause: ${lit(row.cause)},`,
	]
	if (row.blocker !== undefined) parts.push(`\t\tblocker: ${lit(row.blocker)},`)
	parts.push(
		`\t\tauthority: ${lit(row.authority)},`,
		`\t\tretrySafety: ${lit(row.retrySafety)},`,
		`\t\tprojectionCompleteness: ${lit(row.projectionCompleteness)},`,
		`\t\tnextSafeAction: ${lit(row.nextSafeAction)},`,
	)
	if (row.stopScope !== undefined) {
		parts.push(`\t\tstopScope: ${lit(row.stopScope)},`)
	}
	return ['\t{', ...parts, '\t},'].join('\n')
}
