/**
 * Rendering: derived artifacts to TypeScript source text.
 *
 * These functions return strings. They never write a file, create a directory
 * or compute a manifest  -  the generation pipeline that replaces the complete
 * Generated Artifact Set as one unit owns all of that. Keeping rendering pure
 * is what lets the same bytes be produced in isolation for drift verification
 * and compared without touching a working tree.
 *
 * Determinism is a contract, not an accident: every collection is emitted in a
 * sorted order and every object literal has a fixed key order, so rendering the
 * same IR twice produces byte-identical text.
 */
import type { CommandFacadeContract } from '@side-quest/cli-command-facade'
import { type DerivedStation, sortStations } from './branch-stations.ts'
import { compareCodepoints } from './canonical.ts'
import type { DerivedContextualRendering } from './contextual-renderings.ts'
import { pascal } from './derivation-facts.ts'
import type { SemanticExpectationRow } from './expectations.ts'
import type {
	CapabilityAvailability,
	ObservationBudget,
	PauseMode,
	PositionalRoute,
	RootBranch,
	RoutingRow,
	RoutingTable,
	SpecificationIr,
} from './ir.ts'

/** A generated file: its consumer-relative path and its complete contents. */
export interface RenderedModule {
	readonly path: string
	readonly contents: string
}

/**
 * The header every generated artifact carries.
 *
 * A Generated Artifact Set is a disposable projection. The header says so in
 * the file itself, so a maintainer who opens one is told to repair the
 * specification rather than the output.
 */
function header(
	ir: SpecificationIr,
	digest: string,
	conventions: readonly string[] = [],
): string {
	return [
		'// Generated by the Agent-Native State Machine Generator. Do not edit.',
		'//',
		'// This file is one artifact of a disposable Generated Artifact Set derived',
		`// from the Admitted State-Machine Specification for ${ir.specMeta.product}.`,
		'// Edit the specification and regenerate; a hand edit is Generated Artifact',
		'// Drift and will be refused.',
		'//',
		`// specification digest: ${digest}`,
		`// input schema version: ${ir.specMeta.inputSchemaVersion}`,
		// Derivation conventions are stated, never hidden. A reader must be able
		// to tell an admitted meaning from one the generator inferred, and each
		// line here is an open item for stage-5 admission.
		...(conventions.length === 0
			? []
			: [
					'//',
					'// Derivation conventions (inferred, not admitted; pending stage-5',
					'// product-owner admission):',
					...conventions.map((line) => `//   - ${line}`),
				]),
		'',
	].join('\n')
}

/** JSON string literal with double quotes normalized to the repo's single. */
function lit(value: string): string {
	return JSON.stringify(value)
}

/**
 * Renders the Branch Station Catalog module.
 *
 * Emits `contract_id` only; the legacy `data.contract` branch is never
 * produced. The station array is emitted as
 * `const satisfies readonly BranchStation[]` so the facade's own types judge
 * the emission at compile time rather than at review time, and `STATION_IDS`
 * as a const tuple so consumers get compile-time scenario exhaustiveness.
 */
export function renderStationCatalog(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly stations: readonly DerivedStation[]
	/** Consumer-relative catalog path; one station-array export per file. */
	readonly catalogPath: string
	/** Exported symbol prefix, e.g. `vaultGit`. */
	readonly symbolPrefix: string
	/** Screaming-case prefix for the id tuple, e.g. `VAULT_GIT`. */
	readonly constantPrefix: string
	/** The consumer's discovery projection function to import. */
	readonly discoveryImport: { readonly symbol: string; readonly from: string }
	/** Inferred bindings named in the header. */
	readonly conventions?: readonly string[]
}): RenderedModule {
	const {
		ir,
		digest,
		stations,
		catalogPath,
		symbolPrefix,
		constantPrefix,
		discoveryImport,
		conventions = [],
	} = input
	const sorted = sortStations(stations)

	const lines: string[] = [
		header(ir, digest, conventions),
		'import {',
		'\ttype BranchStation,',
		'\ttype BranchStationEvidence,',
		'\tfindBranchStationCatalogDrift,',
		'\tprojectStationMap,',
		"} from '@side-quest/cli-command-facade'",
		`import { ${discoveryImport.symbol} } from ${lit(discoveryImport.from)}`,
		'',
		`const CATALOG_PATH = ${lit(catalogPath)}`,
		'',
		'/** Stable Branch Station ids. Spread into `satisfies Record<StationId, ...>`',
		' * to get compile-time scenario exhaustiveness. */',
		`export const ${constantPrefix}_STATION_IDS = [`,
		...sorted.map((derived) => `\t${lit(derived.station.id)},`),
		'] as const',
		'',
		`export type ${pascal(symbolPrefix)}StationId =`,
		`\t(typeof ${constantPrefix}_STATION_IDS)[number]`,
		'',
		'/** Package-owned Branch Station Catalog. */',
		`export const ${symbolPrefix}BranchStationCatalog = [`,
		...sorted.map((derived) => renderStation(derived)),
		'] as const satisfies readonly BranchStation[]',
		'',
		'/** Find catalog drift against live command discovery. */',
		`export function find${pascal(symbolPrefix)}BranchStationCatalogDrift(`,
		'\tevidence: readonly BranchStationEvidence[] = [],',
		') {',
		'\treturn findBranchStationCatalogDrift({',
		`\t\tdiscovery: ${discoveryImport.symbol}(),`,
		`\t\tcatalog: ${symbolPrefix}BranchStationCatalog,`,
		'\t\tevidence,',
		'\t\tpath: CATALOG_PATH,',
		'\t})',
		'}',
		'',
		'/** Project the Station Map for this package. */',
		`export function project${pascal(symbolPrefix)}StationMap(`,
		'\tevidence: readonly BranchStationEvidence[] = [],',
		') {',
		'\treturn projectStationMap({',
		`\t\tdiscovery: ${discoveryImport.symbol}(),`,
		`\t\tcatalog: ${symbolPrefix}BranchStationCatalog,`,
		'\t\tevidence,',
		'\t\tpath: CATALOG_PATH,',
		'\t})',
		'}',
		'',
	]

	return { path: catalogPath, contents: lines.join('\n') }
}

/** One station literal, keys in a fixed order so rendering is deterministic. */
function renderStation(derived: DerivedStation): string {
	const s = derived.station
	const parts = [
		`\t\tid: ${lit(s.id)},`,
		`\t\tcommand: ${lit(s.command)},`,
		`\t\tclassification: ${lit(s.classification)},`,
		`\t\tintent: ${lit(s.intent)},`,
		`\t\ttrigger: ${lit(s.trigger)},`,
	]
	if (s.expectedExitCode !== undefined) {
		parts.push(`\t\texpectedExitCode: ${s.expectedExitCode},`)
	}
	if (s.expectedEnvelopeStatus !== undefined) {
		parts.push(`\t\texpectedEnvelopeStatus: ${lit(s.expectedEnvelopeStatus)},`)
	}
	if (s.expectedResultContractId !== undefined) {
		parts.push(
			`\t\texpectedResultContractId: ${lit(s.expectedResultContractId)},`,
		)
	}
	if (s.expectedErrorCode !== undefined) {
		parts.push(`\t\texpectedErrorCode: ${lit(s.expectedErrorCode)},`)
	}
	if (s.expectedActionId !== undefined) {
		parts.push(`\t\texpectedActionId: ${lit(s.expectedActionId)},`)
	}
	if (s.expectedContinuationId !== undefined) {
		parts.push(`\t\texpectedContinuationId: ${lit(s.expectedContinuationId)},`)
	}
	parts.push(`\t\tmutationExpectation: ${lit(s.mutationExpectation)},`)
	return ['\t{', ...parts, '\t},'].join('\n')
}

/**
 * Renders the Command Surface Contract module.
 *
 * The record is emitted `as const satisfies Record<string, CommandFacadeContract>`
 * so the facade's type is the judge of the emission.
 */
export function renderCommandContracts(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly contracts: Readonly<Record<string, CommandFacadeContract>>
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	const { ir, digest, contracts, path, symbolPrefix, conventions = [] } = input
	const commands = Object.keys(contracts).sort()

	const lines: string[] = [
		header(ir, digest, conventions),
		"import type { CommandFacadeContract } from '@side-quest/cli-command-facade'",
		'',
		"/** The single generated static owner of this product's public CLI meaning. */",
		`export const ${symbolPrefix}CommandContracts = {`,
		...commands.map((command) =>
			renderContract(command, contracts[command] as CommandFacadeContract),
		),
		'} as const satisfies Record<string, CommandFacadeContract>',
		'',
		`export type ${pascal(symbolPrefix)}Command =`,
		`\tkeyof typeof ${symbolPrefix}CommandContracts`,
		'',
	]

	return { path, contents: lines.join('\n') }
}

function renderContract(
	command: string,
	contract: CommandFacadeContract,
): string {
	const flagKeys = Object.keys(contract.flags).sort()
	const exitKeys = Object.keys(contract.exitCodes).sort()
	const parts = [
		`\t\tscript: ${lit(contract.script)},`,
		`\t\tsummary: ${lit(contract.summary)},`,
		`\t\tusage: [${contract.usage.map(lit).join(', ')}],`,
		`\t\tjson: ${contract.json},`,
		`\t\taudience: ${lit(contract.audience)},`,
		`\t\tmutation: ${lit(contract.mutation)},`,
	]
	if (contract.sideEffects) {
		parts.push(
			`\t\tsideEffects: [${contract.sideEffects.map(lit).join(', ')}],`,
		)
	}
	if (contract.executionModes) {
		parts.push(
			`\t\texecutionModes: [${contract.executionModes.map(lit).join(', ')}],`,
		)
	}
	if (contract.outputModes) {
		parts.push(
			`\t\toutputModes: [${contract.outputModes.map(lit).join(', ')}],`,
		)
	}
	if (contract.resultContract) {
		const rc = contract.resultContract
		parts.push(
			`\t\tresultContract: { id: ${lit(rc.id)}, schema_version: ${
				typeof rc.schema_version === 'string'
					? lit(rc.schema_version)
					: rc.schema_version
			} },`,
		)
	}
	parts.push(
		'\t\tflags: {',
		...flagKeys.map((flag) => `\t\t\t${lit(flag)}: { type: 'boolean' },`),
		'\t\t},',
		'\t\texitCodes: {',
		...exitKeys.map(
			(code) =>
				`\t\t\t${lit(code)}: ${lit(contract.exitCodes[code] as string)},`,
		),
		'\t\t},',
	)
	return [`\t${lit(command)}: {`, ...parts, '\t},'].join('\n')
}

/**
 * Renders the generator-owned semantic expectation table.
 *
 * The table is a separate module from the catalog on purpose: it joins to
 * stations on `expectedActionId` and must never be mistaken for facade
 * surface. Emitting it beside the catalog would invite exactly that.
 */
/**
 * Renders the Contextual Rendering resolution table.
 *
 * A rendering with one declared target carries `resolved`; one with several
 * carries only `candidates`, so a consumer that cannot supply context has no
 * single answer to take and fails closed rather than choosing the first. The
 * table is a compatibility surface, never a second action vocabulary, and is
 * never persisted as authority.
 */
export function renderContextualRenderings(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly renderings: readonly DerivedContextualRendering[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	const { ir, digest, renderings, path, symbolPrefix, conventions = [] } = input
	const sorted = [...renderings].sort((a, b) =>
		compareCodepoints(a.rendering, b.rendering),
	)

	const lines: string[] = [
		header(ir, digest, conventions),
		'/**',
		' * Public compatibility identifiers and the canonical action ids they',
		' * resolve to. A rendering resolves to exactly one canonical id only',
		' * when its context is supplied: an entry carrying `candidates` without',
		' * `resolved` has more than one, and selecting among them needs context',
		' * this table does not hold. Ambiguity fails closed; it never picks.',
		' *',
		' * Never a second action vocabulary, and never persisted as authority:',
		' * durable writes store canonical ids only.',
		' */',
		`export const ${symbolPrefix}ContextualRenderings = {`,
		...sorted.map((entry) => renderRendering(entry)),
		'} as const',
		'',
	]

	return { path, contents: lines.join('\n') }
}

function renderRendering(entry: DerivedContextualRendering): string {
	const parts = [`\t\tcandidates: [${entry.candidates.map(lit).join(', ')}],`]
	if (entry.resolved !== undefined) {
		parts.push(`\t\tresolved: ${lit(entry.resolved)},`)
	}
	return [`\t${lit(entry.rendering)}: {`, ...parts, '\t},'].join('\n')
}

/**
 * Renders the declared observation budgets.
 *
 * The bounds are the candidate's and the meaning is ADR 0002's: expiry
 * anchors to one Attempt, a new Attempt gets a fresh bound, and neither
 * polling nor a heartbeat renews one. Only the declared numbers, the Wake
 * Route and the missed-deadline cause are emitted; the never-renews rule
 * itself stays generator-owned in `observation-budgets.ts`, because a
 * consumer that could restate it could also restate it wrongly.
 *
 * A Wake Route carries no Authority and never renews an expiry. It says only
 * where a waiting caller learns that observing again may be useful.
 */
export function renderObservationBudgets(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly observations: readonly ObservationBudget[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	const {
		ir,
		digest,
		observations,
		path,
		symbolPrefix,
		conventions = [],
	} = input
	const sorted = [...observations].sort((a, b) =>
		compareCodepoints(a.name, b.name),
	)

	const lines: string[] = [
		header(ir, digest, conventions),
		'/**',
		' * Declared observation budgets: when observing again is useful, and',
		" * when an Attempt's observation no longer supports a safe State",
		' * Projection.',
		' *',
		' * `attemptExpiryMs` is a per-Attempt bound. A new Attempt gets a fresh',
		' * bound; polling never renews one, and a heartbeat is not a renewal.',
		' * `wakeRoute` carries no Authority: it names where a waiting caller',
		' * learns that observation may usefully be repeated.',
		' */',
		`export const ${symbolPrefix}ObservationBudgets = {`,
		...sorted.map((entry) => renderObservation(entry)),
		'} as const',
		'',
	]

	return { path, contents: lines.join('\n') }
}

function renderObservation(entry: ObservationBudget): string {
	const parts = [
		`\t\tpollAfterMs: ${entry.pollAfterMs},`,
		`\t\tattemptExpiryMs: ${entry.attemptExpiryMs},`,
	]
	if (entry.wakeRoute !== undefined) {
		parts.push(`\t\twakeRoute: ${lit(entry.wakeRoute)},`)
	}
	if (entry.missedDeadlineCause !== undefined) {
		parts.push(`\t\tmissedDeadlineCause: ${lit(entry.missedDeadlineCause)},`)
	}
	return [`\t${lit(entry.name)}: {`, ...parts, '\t},'].join('\n')
}

/**
 * Renders the declared root branches.
 *
 * A root branch is a public branch the front door owns rather than any one
 * command: root help, an unknown command, and the crash path. It is
 * deliberately NOT emitted as a Branch Station. The facade's station grammar
 * is `<command>.<branch>` and its hard invariants require a station's command
 * to appear in discovery, so publishing one would mean inventing a
 * pseudo-command that no discovery declares - an invented binding, which is
 * exactly what this generator refuses to do elsewhere.
 *
 * Each branch carries the exit it rides and the product's own word for what
 * that exit means. Two branches may share an exit (a refusal and the crash
 * path both ride 1) but never the same meaning on the same exit, which
 * compile validation holds: that is what makes a declared exit-1 meaning
 * distinct rather than one word for two branches.
 */
export function renderRootBranches(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly rootBranches: readonly RootBranch[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	const {
		ir,
		digest,
		rootBranches,
		path,
		symbolPrefix,
		conventions = [],
	} = input
	const sorted = [...rootBranches].sort((a, b) =>
		compareCodepoints(a.name, b.name),
	)

	const lines: string[] = [
		header(ir, digest, conventions),
		'/**',
		' * Public branches the front door owns rather than any one command.',
		' *',
		' * Not Branch Stations: a station names the command that owns it, and',
		' * these are reached before any command is selected. `exitCode` is the',
		" * exit the branch rides and `meaning` is the product's declared word",
		' * for it, so two branches on one exit stay tellable apart.',
		' */',
		`export const ${symbolPrefix}RootBranches = {`,
		...sorted.map((entry) => renderRootBranch(entry)),
		'} as const',
		'',
	]

	return { path, contents: lines.join('\n') }
}

function renderRootBranch(entry: RootBranch): string {
	const parts = [
		`\t\texitCode: ${lit(entry.exitCode)},`,
		`\t\tmeaning: ${lit(entry.meaning)},`,
	]
	// Emitted only where declared: a root branch that names no action has no
	// Next Safe Action, which is not the same as naming the terminal one.
	if (entry.action !== undefined) {
		parts.push(`\t\taction: ${lit(entry.action)},`)
	}
	return [`\t${lit(entry.name)}: {`, ...parts, '\t},'].join('\n')
}

/**
 * Renders the declared positional routes.
 *
 * A positional route says which canonical action a positional token selects
 * for one command, and which action bare invocation of that command selects.
 * These are command-surface parsing facts, so they are emitted beside the
 * Command Surface Contract rather than inside it: the facade's contract type
 * has no field for token-to-action routing. Its `alias` field carries a
 * command plus default arguments, which is command aliasing and a different
 * meaning; reusing it would publish one binding under another's name.
 *
 * Every emitted target is a canonical action id, checked at compile against
 * the action catalog. The token is the public spelling and never a second
 * action vocabulary.
 */
export function renderPositionalRoutes(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly routes: readonly PositionalRoute[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	const { ir, digest, routes, path, symbolPrefix, conventions = [] } = input
	const sorted = [...routes].sort((a, b) =>
		compareCodepoints(a.command, b.command),
	)

	const lines: string[] = [
		header(ir, digest, conventions),
		'/**',
		' * Which canonical action a positional token selects, per command.',
		' *',
		' * `bareInvocationTarget` is the action bare invocation of that command selects.',
		' * A token this table does not cover selects nothing rather than',
		' * falling through to a default.',
		' */',
		`export const ${symbolPrefix}PositionalRoutes = {`,
		...sorted.map((entry) => renderPositionalRoute(entry)),
		'} as const',
		'',
	]

	return { path, contents: lines.join('\n') }
}

function renderPositionalRoute(entry: PositionalRoute): string {
	const positionals = Object.keys(entry.positionals)
		.sort(compareCodepoints)
		.map(
			(token) => `\t\t\t${lit(token)}: ${lit(entry.positionals[token] ?? '')},`,
		)
	const parts = ['\t\tpositionals: {', ...positionals, '\t\t},']
	if (entry.bareInvocationTarget !== undefined) {
		parts.push(`\t\tbareInvocationTarget: ${lit(entry.bareInvocationTarget)},`)
	}
	return [`\t${lit(entry.command)}: {`, ...parts, '\t},'].join('\n')
}

/**
 * Renders the declared fact-to-branch selection tables.
 *
 * A `fact_branch` table says which Branch Station an observed fact reaches.
 * That is a different claim from what the station's Next Safe Action then is,
 * which `station_action` binds separately: reaching a branch never says what
 * to do about it, and collapsing the two would silently replace a branch with
 * an action.
 *
 * Every emitted target is checked against the derived station catalog by
 * `branch-stations.ts`, so a table published here selects a station that
 * genuinely exists. A key no row covers selects nothing rather than falling
 * through to a default: the table is exhaustive over its declared
 * discriminants or it refuses at compile.
 */
export function renderFactBranchRouting(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly tables: readonly RoutingTable[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	return renderRoutingModule({
		...input,
		exportName: 'FactBranchRouting',
		jsdocLines: [
			' * Which Branch Station an observed fact reaches.',
			' *',
			' * Each row carries a complete key over the declared discriminants and',
			' * the one station it selects. A key no row covers selects nothing;',
			' * there is no default and no best match. Reaching a station says which',
			" * branch happened, never what that branch's Next Safe Action is.",
		],
		renderTable: renderFactBranchTable,
	})
}

function renderFactBranchTable(table: RoutingTable): string {
	const rows = table.rows.map((row) => {
		const key = renderRoutingRowKey(row)
		return `\t\t\t{ key: { ${key} }, station: ${lit(row.target)} },`
	})
	return renderRoutingTableEntry(table, rows)
}

/**
 * Renders the declared action-routing tables.
 *
 * A Finding-plus-evidence table (ADR 0005) states which canonical action a
 * complete key selects, with the retry posture that route takes and, where a
 * route is human-owned, the handoff kind it names. The whole point is that
 * every complete key selects exactly one action: a key the table does not
 * cover selects nothing, and compile validation refuses a table claiming
 * complete coverage that leaves a combination unrouted.
 *
 * Emitted as declared data, not as a second action owner. The table says
 * which canonical action a Finding routes to; the one Projection Composer
 * still selects the public State Projection.
 */
export function renderActionRouting(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly tables: readonly RoutingTable[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	return renderRoutingModule({
		...input,
		exportName: 'ActionRouting',
		jsdocLines: [
			' * Which canonical action a complete key selects.',
			' *',
			' * Every row carries a complete key over the declared discriminants.',
			' * A key no row covers selects nothing: there is no default and no',
			' * best match. `retrySafety` is the posture that route takes and',
			' * `humanKind` names the handoff a human-owned route needs.',
		],
		renderTable: renderActionRoutingTable,
	})
}

function renderActionRoutingTable(table: RoutingTable): string {
	const rows = table.rows.map((row) => {
		const key = renderRoutingRowKey(row)
		const parts = [
			`\t\t\t\tkey: { ${key} },`,
			`\t\t\t\taction: ${lit(row.target)},`,
		]
		if (row.retrySafety !== undefined) {
			parts.push(`\t\t\t\tretrySafety: ${lit(row.retrySafety)},`)
		}
		if (row.humanKind !== undefined) {
			parts.push(`\t\t\t\thumanKind: ${lit(row.humanKind)},`)
		}
		return ['\t\t\t{', ...parts, '\t\t\t},'].join('\n')
	})
	return renderRoutingTableEntry(table, rows)
}

/**
 * Shared module-wrapping for a routing table export: sorted table order,
 * a fixed leading JSDoc block, and the `export const ... = { ... } as const`
 * shell that every routing renderer assembles the same way.
 */
function renderRoutingModule(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly tables: readonly RoutingTable[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
	readonly exportName: string
	readonly jsdocLines: readonly string[]
	readonly renderTable: (table: RoutingTable) => string
}): RenderedModule {
	const {
		ir,
		digest,
		tables,
		path,
		symbolPrefix,
		conventions = [],
		exportName,
		jsdocLines,
		renderTable,
	} = input
	const sorted = [...tables].sort((a, b) => compareCodepoints(a.name, b.name))

	const lines: string[] = [
		header(ir, digest, conventions),
		'/**',
		...jsdocLines,
		' */',
		`export const ${symbolPrefix}${exportName} = {`,
		...sorted.map(renderTable),
		'} as const',
		'',
	]

	return { path, contents: lines.join('\n') }
}

/** A routing row's complete key, rendered in codepoint-sorted field order. */
function renderRoutingRowKey(row: RoutingRow): string {
	return Object.keys(row.key)
		.sort(compareCodepoints)
		.map((field) => `${lit(field)}: ${lit(row.key[field] ?? '')}`)
		.join(', ')
}

/**
 * Shared row-block wrapping for one routing table: the discriminants block
 * every routing table carries, wrapped around a caller-supplied, already
 * rendered `rows` block whose row shape differs per routing kind.
 */
function renderRoutingTableEntry(
	table: RoutingTable,
	rows: readonly string[],
): string {
	const discriminants = Object.keys(table.discriminants)
		.sort(compareCodepoints)
		.map(
			(field) =>
				`\t\t\t${lit(field)}: [${(table.discriminants[field] ?? [])
					.map(lit)
					.join(', ')}],`,
		)
	return [
		`\t${lit(table.name)}: {`,
		'\t\tdiscriminants: {',
		...discriminants,
		'\t\t},',
		`\t\trequiresCompleteCoverage: ${table.requiresCompleteCoverage ? 'true' : 'false'},`,
		'\t\trows: [',
		...rows,
		'\t\t],',
		'\t},',
	].join('\n')
}

/**
 * Renders the declared capability gates and the routing each one takes.
 *
 * Carries no current value, by design. Whether a capability is installed is
 * runtime evidence: a Handwritten Liveness Evidence Provider observes it
 * against the declared `availabilityEvidence` Extension Point and supplies
 * the value, and the generated selector below reads that value as
 * independent evidence. The specification declares only what is true either
 * way, which is why both routes are present rather than one being
 * conditional on an authored boolean.
 *
 * The selector routes; it does not decide. Capability Availability is an
 * installed-surface fact and never Authority: an available capability grants
 * no permission, so the available route is emitted only where the product
 * declared one. An unavailable capability names its blocker and its
 * operator-owned escalation, which compile validation holds to `needs_human`.
 * The one Projection Composer still selects the public State Projection, so
 * this adds no second action owner.
 */
export function renderCapabilityGates(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly capabilities: readonly CapabilityAvailability[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	const {
		ir,
		digest,
		capabilities,
		path,
		symbolPrefix,
		conventions = [],
	} = input
	const sorted = [...capabilities].sort((a, b) =>
		compareCodepoints(a.name, b.name),
	)
	const typePrefix = pascal(symbolPrefix)

	const lines: string[] = [
		header(ir, digest, conventions),
		'/**',
		' * Declared capabilities and where each routes.',
		' *',
		' * No installed value is carried here. `availabilityEvidence` names the',
		' * Extension Point whose Liveness Evidence Provider observes whether the',
		' * capability is installed; that observation is made at runtime and',
		' * stays outside this Generated Artifact Set.',
		' *',
		' * Capability Availability is never Authority. An available capability',
		' * grants no permission, and an unavailable one routes to its declared',
		' * operator-owned escalation rather than the surface going quiet.',
		' */',
		`export const ${symbolPrefix}CapabilityGates = {`,
		...sorted.map((entry) => renderCapabilityGate(entry)),
		'} as const',
		'',
		`export type ${typePrefix}CapabilityName = keyof typeof ${symbolPrefix}CapabilityGates`,
		'',
		'/**',
		' * Observed capability evidence, supplied by a Liveness Evidence',
		' * Provider. Never authored in a specification and never persisted as',
		' * Authority.',
		' */',
		`export interface ${typePrefix}CapabilityEvidence {`,
		'	readonly installed: boolean',
		'}',
		'',
		'/**',
		' * Routes one declared capability under observed evidence.',
		' *',
		' * Evidence in, route out. This selects no State Projection and names',
		' * no Next Safe Action of its own beyond the routes the specification',
		' * declared: the one Projection Composer consumes this as independent',
		' * evidence and remains the sole action owner.',
		' */',
		`export function select${typePrefix}CapabilityRoute(`,
		`	capability: ${typePrefix}CapabilityName,`,
		`	evidence: ${typePrefix}CapabilityEvidence,`,
		'): {',
		'	readonly available: boolean',
		'	readonly blocker?: string',
		'	readonly action?: string',
		'} {',
		`	const gate = ${symbolPrefix}CapabilityGates[capability]`,
		'	if (evidence.installed) {',
		'		return {',
		'			available: true,',
		"			...('availableAction' in gate",
		'				? { action: gate.availableAction }',
		'				: {}),',
		'		}',
		'	}',
		'	return {',
		'		available: false,',
		'		blocker: gate.unavailableBlocker,',
		'		action: gate.unavailableAction,',
		'	}',
		'}',
		'',
	]

	return { path, contents: lines.join('\n') }
}

function renderCapabilityGate(entry: CapabilityAvailability): string {
	const parts = [
		`\t\tavailabilityEvidence: ${lit(entry.availabilityEvidence)},`,
	]
	// Emitted only where the product declared a route for the available case.
	// Most capabilities simply permit the work their command already does,
	// and an absent route is not the terminal action.
	if (entry.availableAction !== undefined) {
		parts.push(`\t\tavailableAction: ${lit(entry.availableAction)},`)
	}
	parts.push(
		`\t\tunavailableBlocker: ${lit(entry.unavailableBlocker)},`,
		`\t\tunavailableAction: ${lit(entry.unavailableAction)},`,
	)
	return [`\t${lit(entry.name)}: {`, ...parts, '\t},'].join('\n')
}

/**
 * Renders the declared Pause Modes.
 *
 * A Pause Mode is an externally owned gate that suspends otherwise permitted
 * work until its owner releases it, and its release is a human-owned act. The
 * emitted route says who owns the gate, which blocker an active Pause
 * reports, and which action requests release - never an action that clears
 * the Pause itself, which compile validation holds by requiring the release
 * action to be human-owned.
 *
 * A Pause is not an Authority denial and not a disabled feature: the work is
 * permitted and is waiting on a person.
 */
export function renderPauseModes(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly pauseModes: readonly PauseMode[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	const { ir, digest, pauseModes, path, symbolPrefix, conventions = [] } = input
	const sorted = [...pauseModes].sort((a, b) =>
		compareCodepoints(a.name, b.name),
	)

	const lines: string[] = [
		header(ir, digest, conventions),
		'/**',
		' * Externally owned gates that suspend otherwise permitted work.',
		' *',
		' * `releaseAction` REQUESTS release; it never performs it. Releasing a',
		" * Pause is the owner's own act, which is why the declared action is",
		' * human-owned. An active Pause is not an Authority denial: the work is',
		' * permitted and is waiting on a person.',
		' */',
		`export const ${symbolPrefix}PauseModes = {`,
		...sorted.map((entry) => renderPauseMode(entry)),
		'} as const',
		'',
	]

	return { path, contents: lines.join('\n') }
}

function renderPauseMode(entry: PauseMode): string {
	return [
		`\t${lit(entry.name)}: {`,
		`\t\towner: ${lit(entry.owner)},`,
		`\t\tactiveBlocker: ${lit(entry.activeBlocker)},`,
		`\t\treleaseAction: ${lit(entry.releaseAction)},`,
		'\t},',
	].join('\n')
}

export function renderExpectationTable(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly rows: readonly SemanticExpectationRow[]
	readonly path: string
	readonly symbolPrefix: string
	readonly conventions?: readonly string[]
}): RenderedModule {
	const { ir, digest, rows, path, symbolPrefix, conventions = [] } = input
	const sorted = [...rows].sort((a, b) =>
		compareCodepoints(a.stationId, b.stationId),
	)

	const lines: string[] = [
		header(ir, digest, conventions),
		'/**',
		' * Generator-owned semantic expectations, joined to Branch Stations on the',
		" * facade's existing `expectedActionId` string. These meanings are",
		" * deliberately absent from the facade's own types.",
		' */',
		`export const ${symbolPrefix}SemanticExpectations = [`,
		...sorted.map((row) => renderRow(row)),
		'] as const',
		'',
	]

	return { path, contents: lines.join('\n') }
}

/** Row fields every rendered State Projection variant shares. */
export function renderProjectionCoreFields(
	row: SemanticExpectationRow,
): string[] {
	const parts = [
		`\t\tauthority: ${lit(row.authority)},`,
		`\t\tretrySafety: ${lit(row.retrySafety)},`,
		`\t\tprojectionCompleteness: ${lit(row.projectionCompleteness)},`,
		`\t\tnextSafeAction: ${lit(row.nextSafeAction)},`,
	]
	if (row.stopScope !== undefined) {
		parts.push(`\t\tstopScope: ${lit(row.stopScope)},`)
	}
	return parts
}

function renderRow(row: SemanticExpectationRow): string {
	const parts = [
		`\t\tstationId: ${lit(row.stationId)},`,
		`\t\texpectedActionId: ${lit(row.expectedActionId)},`,
		`\t\tstate: ${lit(row.state)},`,
		`\t\texitMeaning: ${lit(row.exitMeaning)},`,
	]
	if (row.blocker !== undefined) parts.push(`\t\tblocker: ${lit(row.blocker)},`)
	parts.push(...renderProjectionCoreFields(row))
	// Emitted only where the candidate declared the column for this station.
	// An omitted column is the absence of a declaration, which is why it is
	// not rendered as a value: `changed_state` declares `unknown` for the
	// case a caller cannot tell, so a rendered default would be a claim.
	if (row.changedState !== undefined) {
		parts.push(`\t\tchangedState: ${lit(row.changedState)},`)
	}
	if (row.channel !== undefined) {
		parts.push(`\t\tchannel: ${lit(row.channel)},`)
	}
	// Omitted where the specification does not settle every ADR 0006
	// conjunct. A rendered `false` would be a decided negative.
	if (row.retryable !== undefined) {
		parts.push(`\t\tretryable: ${row.retryable ? 'true' : 'false'},`)
	}
	return ['\t{', ...parts, '\t},'].join('\n')
}
