export {
	COMMAND_FACADE_AUDIENCES,
	COMMAND_FACADE_BASELINE_EXIT_CODES,
	COMMAND_FACADE_CAPABILITY_ROLES,
	COMMAND_FACADE_EXECUTION_MODES,
	COMMAND_FACADE_INTERACTIVITY,
	COMMAND_FACADE_OUTPUT_MODES,
	COMMAND_FACADE_SIDE_EFFECTS,
	type CommandDiscoveryActionAffordance,
	type CommandDiscoveryActionAffordances,
	type CommandDiscoveryAugment,
	type CommandDiscoveryCommand,
	type CommandDiscoveryFlag,
	type CommandDiscoveryResultContract,
	type CommandDiscoveryRoute,
	type CommandDiscoveryTree,
	type CommandFacadeActionAffordance,
	type CommandFacadeActionAffordances,
	type CommandFacadeAlias,
	type CommandFacadeAudience,
	type CommandFacadeCapabilityRole,
	type CommandFacadeContract,
	type CommandFacadeEnvVar,
	type CommandFacadeExecutionMode,
	type CommandFacadeFlag,
	type CommandFacadeInteractivity,
	type CommandFacadeMetadataDrift,
	type CommandFacadeOutputMode,
	type CommandFacadePreviewExemption,
	type CommandFacadeResultContract,
	type CommandFacadeSideEffect,
	type CommandResultData,
	type CommandResultPayload,
	type ProjectCommandDiscoveryTreeOptions,
	createCommandResultData,
} from "./command-contract";
export {
	findCommandDiscoveryTreeDrift,
	projectCommandDiscoveryActionAffordances,
	projectCommandDiscoveryFlag,
	projectCommandDiscoveryResultContract,
	projectCommandDiscoveryTree,
} from "./command-discovery";

export {
	CLI_WRITER_CONTRACT_EXIT_CODE,
	CliWriterContractError,
	type CliJsonEnvelopeRuntime,
	type CliWriter,
	type CliWriterContractEvent,
	writeJson,
	writeJsonEnvelope,
} from "./cli-writer";
export { CLI_DIAGNOSTIC_FLAGS } from "./cli-diagnostics";
export {
	CliUsageError,
	composeAliasArgv,
	formatEnumFlagError,
	helpRequested,
	parseEnumFlag,
	projectUsageToRoute,
	projectUsagesToRoute,
	renderCommandUsage,
	requireValue,
	usageError,
} from "./usage";
export { matchSensitiveEnvVarName } from "./runtime-text-safety";

export {
	CliRuntimeContractError,
	AGENT_HINT_ACTIONS,
	DIAGNOSTIC_TRAIL_SURFACE_KINDS,
	RUNTIME_ERROR_RECOVERABILITIES,
	RUNTIME_ERROR_SEVERITIES,
	type AgentHint,
	type AgentHintAction,
	type AgentHintActionForRecoverability,
	type AgentHintForRecoverability,
	type CliRuntimeErrorBuilderInput,
	type CliRuntimeErrorEnvelope,
	type CliRuntimeSuccessEnvelope,
	type CliStructuredRuntimeErrorBuilderInput,
	type CliUsageRuntimeErrorBuilderInput,
	type DiagnosticTrailReference,
	type DiagnosticTrailSurfaceKind,
	type RuntimeActionGuidance,
	type RuntimeContinuationConstraint,
	type RuntimeContinuationGuidance,
	type RuntimeErrorRecoverability,
	type RuntimeErrorSeverity,
	type RuntimeRecoveryChoice,
	type StructuredRuntimeError,
	createCliRuntimeError,
	createCliRepairStateRuntimeError,
	createCliRuntimeErrorEnvelope,
	createCliRetryRuntimeError,
	createCliRuntimeSuccessEnvelope,
	createCliUsageRuntimeError,
	validateAgentHint,
	validateStructuredRuntimeError,
} from "./runtime-envelope";

export {
	defineCommandFacadeContract,
	findCommandFacadeMetadataDrift,
	parseCommandFacadeContract,
	type CommandFacadeContractValidationOptions,
	type ParseCommandFacadeContractResult,
} from "./command-metadata";
