import type { StationId } from "../../src/command-contract.ts"

// B1 exhaustiveness specimen (CDS-BC-1): one explicit arm per declared station makes any widening of the finite
// StationId union observable to the compiler through the never-typed default. The arms enumerate the sealed
// production vocabulary in declaration order; they assert nothing about station semantics.
type CandidateStationId = StationId

// fallow-ignore-next-line complexity -- this specimen intentionally enumerates every sealed vocabulary arm.
function _exhaustivelyNameStation(stationId: CandidateStationId): string {
	switch (stationId) {
		case '["repair-lab.status","success","SUCCESS_UNCHANGED"]':
			return stationId
		case '["repair-lab.inspect","success","SUCCESS_UNCHANGED"]':
			return stationId
		case '["repair-lab.preview","success","SUCCESS_UNCHANGED"]':
			return stationId
		case '["repair-lab.apply","success","SUCCESS_COMPLETED"]':
			return stationId
		case '["repair-lab.apply","refused","DOMAIN_PRECONDITION_UNMET"]':
			return stationId
		case '["repair-lab.apply","failed","INTERNAL_EFFECT_OUTCOME_UNKNOWN"]':
			return stationId
		case '["repair-lab.apply","refused","DOMAIN_AUTHORITY_REQUIRED"]':
			return stationId
		case '["repair-lab.repair","refused","DOMAIN_PRECONDITION_UNMET"]':
			return stationId
		case '["repair-lab.repair","success","SUCCESS_COMPLETED"]':
			return stationId
		case '["repair-lab.repair-retry","success","SUCCESS_COMPLETED"]':
			return stationId
		case '["repair-lab.recover","failed","DOMAIN_RECOVERY_HANDOFF_REQUIRED"]':
			return stationId
		case '["repair-lab.inspect","refused","DOMAIN_PRECONDITION_UNMET"]':
			return stationId
		case '["repair-lab.inspect-diagnostics","success","SUCCESS_UNCHANGED"]':
			return stationId
		case '["repair-lab.help","success","SUCCESS_UNCHANGED"]':
			return stationId
		case '["repair-lab.discovery","success","SUCCESS_UNCHANGED"]':
			return stationId
		case '["repair-lab.help","refused","USAGE_UNKNOWN_COMMAND"]':
			return stationId
		case '["repair-lab.help","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.dispatch","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.dispatch","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.status","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.discovery","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.inspect","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.preview","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.apply","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.repair","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.recover","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.inspect","refused","SCHEMA_INVALID_INPUT"]':
			return stationId
		case '["repair-lab.inspect-diagnostics","refused","DOMAIN_PRECONDITION_UNMET"]':
			return stationId
		case '["repair-lab.repair-retry","refused","DOMAIN_PRECONDITION_UNMET"]':
			return stationId
		case '["repair-lab.repair","refused","TRANSIENT_NOT_STARTED"]':
			return stationId
		case '["repair-lab.repair-retry","refused","TRANSIENT_NOT_STARTED"]':
			return stationId
		case '["repair-lab.apply","failed","INTERNAL_EFFECT_NOT_OBSERVED"]':
			return stationId
		case '["repair-lab.recover","success","SUCCESS_UNCHANGED"]':
			return stationId
		case '["repair-lab.inspect-diagnostics","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.repair-retry","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.status","failed","INTERNAL_UNEXPECTED"]':
			return stationId
		case '["repair-lab.inspect","failed","INTERNAL_UNEXPECTED"]':
			return stationId
		case '["repair-lab.inspect-diagnostics","failed","INTERNAL_UNEXPECTED"]':
			return stationId
		case '["repair-lab.preview","failed","INTERNAL_UNEXPECTED"]':
			return stationId
		case '["repair-lab.apply","failed","INTERNAL_UNEXPECTED"]':
			return stationId
		case '["repair-lab.repair","failed","INTERNAL_UNEXPECTED"]':
			return stationId
		case '["repair-lab.repair-retry","failed","INTERNAL_UNEXPECTED"]':
			return stationId
		case '["repair-lab.recover","failed","INTERNAL_UNEXPECTED"]':
			return stationId
		case '["repair-lab.repair","failed","INTERNAL_EFFECT_OUTCOME_UNKNOWN"]':
			return stationId
		case '["repair-lab.repair-retry","failed","INTERNAL_EFFECT_OUTCOME_UNKNOWN"]':
			return stationId
		case '["repair-lab.status","refused","DOMAIN_PRECONDITION_UNMET"]':
			return stationId
		case '["repair-lab.status","refused","SCHEMA_INVALID_INPUT"]':
			return stationId
		case '["repair-lab.inspect-diagnostics","refused","SCHEMA_INVALID_INPUT"]':
			return stationId
		case '["repair-lab.preview","refused","DOMAIN_PRECONDITION_UNMET"]':
			return stationId
		case '["repair-lab.preview","refused","SCHEMA_INVALID_INPUT"]':
			return stationId
		case '["repair-lab.apply","refused","SCHEMA_INVALID_INPUT"]':
			return stationId
		case '["repair-lab.repair","refused","SCHEMA_INVALID_INPUT"]':
			return stationId
		case '["repair-lab.repair-retry","refused","SCHEMA_INVALID_INPUT"]':
			return stationId
		case '["repair-lab.recover","refused","DOMAIN_PRECONDITION_UNMET"]':
			return stationId
		case '["repair-lab.recover","refused","SCHEMA_INVALID_INPUT"]':
			return stationId
		case '["repair-lab.repair","refused","DOMAIN_AUTHORITY_REQUIRED"]':
			return stationId
		case '["repair-lab.repair-retry","refused","DOMAIN_AUTHORITY_REQUIRED"]':
			return stationId
		case '["repair-lab.apply","refused","TRANSIENT_NOT_STARTED"]':
			return stationId
		case '["repair-lab.apply","refused","DOMAIN_DEADLINE_BEFORE_START"]':
			return stationId
		case '["repair-lab.apply","failed","DOMAIN_DEADLINE_UNCHANGED"]':
			return stationId
		case '["repair-lab.apply","failed","DOMAIN_DEADLINE_COMPLETED"]':
			return stationId
		case '["repair-lab.apply","failed","DOMAIN_DEADLINE_PARTIAL"]':
			return stationId
		case '["repair-lab.apply","failed","DOMAIN_DEADLINE_UNKNOWN"]':
			return stationId
		case '["repair-lab.repair","refused","DOMAIN_DEADLINE_BEFORE_START"]':
			return stationId
		case '["repair-lab.repair","failed","DOMAIN_DEADLINE_UNCHANGED"]':
			return stationId
		case '["repair-lab.repair","failed","DOMAIN_DEADLINE_COMPLETED"]':
			return stationId
		case '["repair-lab.repair","failed","DOMAIN_DEADLINE_PARTIAL"]':
			return stationId
		case '["repair-lab.repair","failed","DOMAIN_DEADLINE_UNKNOWN"]':
			return stationId
		case '["repair-lab.repair-retry","refused","DOMAIN_DEADLINE_BEFORE_START"]':
			return stationId
		case '["repair-lab.repair-retry","failed","DOMAIN_DEADLINE_UNCHANGED"]':
			return stationId
		case '["repair-lab.repair-retry","failed","DOMAIN_DEADLINE_COMPLETED"]':
			return stationId
		case '["repair-lab.repair-retry","failed","DOMAIN_DEADLINE_PARTIAL"]':
			return stationId
		case '["repair-lab.repair-retry","failed","DOMAIN_DEADLINE_UNKNOWN"]':
			return stationId
		case '["repair-lab.repair","failed","INTERNAL_EFFECT_NOT_OBSERVED"]':
			return stationId
		case '["repair-lab.repair-retry","failed","INTERNAL_EFFECT_NOT_OBSERVED"]':
			return stationId
		case '["repair-lab.help","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.discovery","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.discovery","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.status","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.status","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.inspect","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.inspect","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.inspect-diagnostics","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.inspect-diagnostics","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.preview","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.preview","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.apply","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.apply","failed","INTERNAL_RESULT_COMPLETED"]':
			return stationId
		case '["repair-lab.apply","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.apply","failed","INTERNAL_RESULT_UNKNOWN"]':
			return stationId
		case '["repair-lab.repair","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.repair","failed","INTERNAL_RESULT_COMPLETED"]':
			return stationId
		case '["repair-lab.repair","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.repair","failed","INTERNAL_RESULT_UNKNOWN"]':
			return stationId
		case '["repair-lab.repair-retry","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.repair-retry","failed","INTERNAL_RESULT_COMPLETED"]':
			return stationId
		case '["repair-lab.repair-retry","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.repair-retry","failed","INTERNAL_RESULT_UNKNOWN"]':
			return stationId
		case '["repair-lab.recover","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.recover","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.recover","failed","INTERNAL_RESULT_UNKNOWN"]':
			return stationId
		case '["repair-lab.command-discovery","success","SUCCESS_UNCHANGED"]':
			return stationId
		case '["repair-lab.command-discovery","refused","USAGE_UNKNOWN_COMMAND"]':
			return stationId
		case '["repair-lab.command-discovery","refused","USAGE_INVALID_INVOCATION"]':
			return stationId
		case '["repair-lab.command-discovery","failed","INTERNAL_RESULT_UNCHANGED"]':
			return stationId
		case '["repair-lab.command-discovery","refused","INTERNAL_PREPARATION"]':
			return stationId
		case '["repair-lab.preview","refused","DOMAIN_JOURNAL_LIMIT_REACHED"]':
			return stationId
		case '["repair-lab.apply","refused","DOMAIN_JOURNAL_LIMIT_REACHED"]':
			return stationId
		case '["repair-lab.repair","refused","DOMAIN_JOURNAL_LIMIT_REACHED"]':
			return stationId
		case '["repair-lab.repair-retry","refused","DOMAIN_JOURNAL_LIMIT_REACHED"]':
			return stationId
		case '["repair-lab.preview","refused","DOMAIN_PRIOR_RUN_PENDING"]':
			return stationId
		case '["repair-lab.apply","refused","DOMAIN_PRIOR_RUN_PENDING"]':
			return stationId
		case '["repair-lab.repair","refused","DOMAIN_PRIOR_RUN_PENDING"]':
			return stationId
		case '["repair-lab.repair-retry","refused","DOMAIN_PRIOR_RUN_PENDING"]':
			return stationId
		case '["repair-lab.recover","failed","DOMAIN_RECOVERY_PARTIAL_HANDOFF"]':
			return stationId
		case '["repair-lab.recover","failed","INTERNAL_RESULT_PARTIAL"]':
			return stationId
		case '["repair-lab.preview","refused","DOMAIN_JOURNAL_LOCK_HELD"]':
			return stationId
		case '["repair-lab.apply","refused","DOMAIN_JOURNAL_LOCK_HELD"]':
			return stationId
		case '["repair-lab.repair","refused","DOMAIN_JOURNAL_LOCK_HELD"]':
			return stationId
		case '["repair-lab.repair-retry","refused","DOMAIN_JOURNAL_LOCK_HELD"]':
			return stationId
		default: {
			const impossible: never = stationId
			return impossible
		}
	}
}
