import {
  AC_SOURCE_VALUES,
  type AcSource,
  RUNBOOK_VERSION,
} from "./contract";
import { sha256Digest } from "./digest";
import { renderScaffold } from "./scaffolds";
import { quoteYamlScalar } from "./yaml-scalar";

export const LEDGER_INIT_SECTION_ORDER = [
  "Acceptance criteria",
  "Batches",
  "Findings data",
  "Findings",
  "Notes",
  "Workflow Learnings",
] as const;

export type LedgerInitInput = {
  issueNumber: number;
  issueTitle: string;
  issueUrl: string;
  targetRepo: string;
  startedAt: string;
  acSource: AcSource;
  acceptanceCriteria: string[];
};

export type LedgerInitResult = {
  ledger_markdown: string;
  metadata: {
    runbook_version: typeof RUNBOOK_VERSION;
    ac_digest: string;
    acceptance_criteria_count: number;
    section_order: readonly (typeof LEDGER_INIT_SECTION_ORDER)[number][];
  };
};

export class LedgerInitRenderError extends Error {
  readonly code: LedgerInitErrorCode;

  constructor(code: LedgerInitErrorCode, message: string) {
    super(message);
    this.name = "LedgerInitRenderError";
    this.code = code;
  }
}

export function isAcSource(value: string): value is AcSource {
  return (AC_SOURCE_VALUES as readonly string[]).includes(value);
}

export function renderLedgerInit(input: LedgerInitInput): LedgerInitResult {
  validateInput(input);

  const acBlock = input.acceptanceCriteria
    .map((criterion) => `- [ ] ${criterion.trim()}`)
    .join("\n");
  const acDigest = sha256Digest(acBlock);
  const ledgerMarkdown = [
    "---",
    `issue_number: ${input.issueNumber}`,
    `issue_title: ${quoteYamlScalar(input.issueTitle)}`,
    `issue_url: ${quoteYamlScalar(input.issueUrl)}`,
    `target_repo: ${quoteYamlScalar(input.targetRepo)}`,
    "plan_path: null",
    `started_at: ${quoteYamlScalar(input.startedAt)}`,
    'status: "in-progress"',
    `runbook_version: ${quoteYamlScalar(RUNBOOK_VERSION)}`,
    `ac_source: ${quoteYamlScalar(input.acSource)}`,
    'ac_confirmation_status: "confirmed"',
    `ac_confirmed_at: ${quoteYamlScalar(input.startedAt)}`,
    'batch_contract_confirmation_status: "pending"',
    "batch_contract_confirmed_at: null",
    "blocked_reason: null",
    "pr_url: null",
    'ship_mode: "standard"',
    "final_reviewed_at: null",
    "plan_digest: null",
    "batch_contract_digest: null",
    `ac_digest: ${quoteYamlScalar(acDigest)}`,
    "---",
    "",
    `# Issue ${input.issueNumber} - ${input.issueTitle}`,
    "",
    "Generated by `cli.ts ledger-init --json`. Runtime owns this starting document.",
    "Format and protocol live in `references/ledger-and-helper.md`.",
    "",
    "## Acceptance criteria",
    "",
    acBlock,
    "",
    "## Batches",
    "",
    fencedYaml(renderScaffold("ledger-empty-batches").body),
    "",
    "## Findings data",
    "",
    fencedYaml(renderScaffold("ledger-empty-findings-data").body),
    "",
    "## Findings",
    "",
    "| id | batch_id | signature | persona | severity | status | summary | resolution |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    "",
    "## Notes",
    "",
    "<append-only log of decisions, blocker overrides, host/build failures, implementation checkpoints, Validator waves, findings checkpoints, reachable commit refs, and dirty/staged path summaries>",
    "",
    "## Workflow Learnings",
    "",
    fencedYaml(renderScaffold("workflow-learnings-empty").body),
    "",
  ].join("\n");

  return {
    ledger_markdown: ledgerMarkdown,
    metadata: {
      runbook_version: RUNBOOK_VERSION,
      ac_digest: acDigest,
      acceptance_criteria_count: input.acceptanceCriteria.length,
      section_order: LEDGER_INIT_SECTION_ORDER,
    },
  };
}

/**
 * Public LedgerInitRenderError codes. Keeping this list pinned at the
 * type level lets the CLI error envelope mapping in `cli.ts` stay
 * exhaustive without restating the strings.
 */
export const LEDGER_INIT_ERROR_CODES = [
  "invalid-issue-number",
  "missing-required-input",
  "invalid-control-characters",
  "invalid-started-at",
  "invalid-ac-source",
  "missing-acceptance-criteria",
  "empty-acceptance-criterion",
] as const;
export type LedgerInitErrorCode = (typeof LEDGER_INIT_ERROR_CODES)[number];

function hasControlCharacters(value: string): boolean {
  for (const ch of value) {
    const code = ch.codePointAt(0) ?? 0;
    if (code < 0x20 || code === 0x7f) return true;
  }
  return false;
}

const ISO_8601_TIMESTAMP_PATTERN =
  /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(Z|[+-](\d{2}):(\d{2}))$/;

const DAYS_IN_MONTH = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

function isLeapYear(year: number): boolean {
  return year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
}

function daysInMonth(year: number, month: number): number {
  if (month === 2 && isLeapYear(year)) return 29;
  return DAYS_IN_MONTH[month - 1] ?? 0;
}

function isIso8601Timestamp(value: string): boolean {
  const match = ISO_8601_TIMESTAMP_PATTERN.exec(value);
  if (!match) return false;

  const [
    ,
    yearText,
    monthText,
    dayText,
    hourText,
    minuteText,
    secondText,
    zoneText,
    offsetHourText,
    offsetMinuteText,
  ] = match;

  const year = Number(yearText);
  const month = Number(monthText);
  const day = Number(dayText);
  const hour = Number(hourText);
  const minute = Number(minuteText);
  const second = Number(secondText);

  if (month < 1 || month > 12) return false;
  if (day < 1 || day > daysInMonth(year, month)) return false;
  if (hour > 23 || minute > 59 || second > 59) return false;

  if (zoneText !== "Z") {
    const offsetHour = Number(offsetHourText);
    const offsetMinute = Number(offsetMinuteText);

    if (offsetHour > 23 || offsetMinute > 59) return false;
  }

  return true;
}

function validateInput(input: LedgerInitInput): void {
  if (!Number.isInteger(input.issueNumber) || input.issueNumber <= 0) {
    throw new LedgerInitRenderError(
      "invalid-issue-number",
      "ledger-init requires a positive integer issue number",
    );
  }
  for (const [label, value] of [
    ["issue title", input.issueTitle],
    ["issue url", input.issueUrl],
    ["target repo", input.targetRepo],
    ["started_at", input.startedAt],
  ] as const) {
    if (value.trim().length === 0) {
      throw new LedgerInitRenderError(
        "missing-required-input",
        `ledger-init requires non-empty ${label}`,
      );
    }
    if (hasControlCharacters(value)) {
      throw new LedgerInitRenderError(
        "invalid-control-characters",
        `ledger-init ${label} must not contain embedded newlines or control characters`,
      );
    }
  }
  if (!isIso8601Timestamp(input.startedAt)) {
    throw new LedgerInitRenderError(
      "invalid-started-at",
      "ledger-init started_at must be an ISO-8601 timestamp (e.g. 2026-05-27T07:00:00+10:00 or 2026-05-27T07:00:00Z)",
    );
  }
  if (!isAcSource(input.acSource)) {
    throw new LedgerInitRenderError(
      "invalid-ac-source",
      `ledger-init ac_source must be one of: ${AC_SOURCE_VALUES.join(", ")}`,
    );
  }
  if (input.acceptanceCriteria.length === 0) {
    throw new LedgerInitRenderError(
      "missing-acceptance-criteria",
      "ledger-init requires at least one --ac value",
    );
  }
  for (const criterion of input.acceptanceCriteria) {
    if (criterion.trim().length === 0) {
      throw new LedgerInitRenderError(
        "empty-acceptance-criterion",
        "ledger-init --ac values must be non-empty",
      );
    }
    if (hasControlCharacters(criterion)) {
      throw new LedgerInitRenderError(
        "invalid-control-characters",
        "ledger-init --ac values must not contain embedded newlines or control characters",
      );
    }
  }
}

function fencedYaml(body: string): string {
  return ["```yaml", body.trimEnd(), "```"].join("\n");
}
