import type { StationRow } from "./command-contract.ts"

// Catalogue leaf: the literal station declarations (CDS-PE-4). Derivation lives in
// branch-station-catalog.ts; the contract module owns STATIONS by re-exporting this table.
// Sources: fixture station_catalog, PE revision 3 (six routed identities, D6-c mapping),
// brief 12 sections 3.3, 3.4 and 5. Guidance kind: "next-action" or "handoff".

type Row = readonly [
	StationRow["commandIdentity"],
	StationRow["outcome"],
	StationRow["causeCode"],
	StationRow["effectClass"],
	StationRow["transactionState"],
	boolean,
	number | null,
	StationRow["guidance"],
	boolean,
	number,
	string | null,
]

const ROWS: readonly Row[] = [
	// Fixture scenarios (section 3.3)
	["repair-lab.status", "success", null, "inspect", "unchanged", true, null, "next-action", false, 0, "repair-lab.healthy"],
	["repair-lab.inspect", "success", null, "inspect", "unchanged", true, null, "next-action", false, 0, "repair-lab.inspect"],
	["repair-lab.preview", "success", null, "repository-local", "unchanged", false, null, "next-action", false, 0, "repair-lab.preview"],
	["repair-lab.apply", "success", null, "repository-local", "completed", false, null, "next-action", false, 0, "repair-lab.authorized-apply"],
	["repair-lab.apply", "refused", "DOMAIN_PREVIEW_STALE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.stale-preview"],
	["repair-lab.apply", "unknown", "INTERNAL_EFFECT_OUTCOME_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.partial-unknown"],
	["repair-lab.apply", "refused", "DOMAIN_AUTHORITY_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.prohibited-automation"],
	["repair-lab.repair", "refused", "DOMAIN_REPAIR_REQUIRED", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.repairable-precondition"],
	["repair-lab.repair", "success", null, "repository-local", "completed", false, null, "next-action", false, 0, "repair-lab.authorized-repair"],
	["repair-lab.repair-retry", "success", null, "repository-local", "completed", false, null, "next-action", false, 0, "repair-lab.permitted-transient-retry"],
	["repair-lab.recover", "unknown", "DOMAIN_RECOVERY_HANDOFF_REQUIRED", "repository-local", "unknown", false, null, "handoff", false, 3, "repair-lab.required-handoff"],
	["repair-lab.inspect", "refused", "DOMAIN_PATH_ESCAPE", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.hostile-input"],
	["repair-lab.inspect-diagnostics", "success", null, "inspect", "unchanged", true, null, "next-action", false, 0, "repair-lab.secret-marker"],
	// Auxiliary routes (section 3.4)
	["repair-lab.help", "success", null, "inspect", "unchanged", false, null, "next-action", false, 0, null],
	["repair-lab.discover", "success", null, "inspect", "unchanged", false, null, "next-action", false, 0, null],
	["repair-lab.help", "refused", "USAGE_COMMAND_REQUIRED", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.help", "refused", "USAGE_UNKNOWN_COMMAND", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.help", "refused", "USAGE_UNKNOWN_OPTION", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.status", "refused", "USAGE_UNKNOWN_OPTION", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.discover", "refused", "USAGE_UNKNOWN_OPTION", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.help", "refused", "USAGE_INVALID_ARGUMENTS", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.discover", "refused", "USAGE_INVALID_ARGUMENTS", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.inspect", "refused", "USAGE_UNKNOWN_OPTION", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.preview", "refused", "USAGE_UNKNOWN_OPTION", "repository-local", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.apply", "refused", "USAGE_UNKNOWN_OPTION", "repository-local", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.repair", "refused", "USAGE_UNKNOWN_OPTION", "repository-local", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.recover", "refused", "USAGE_UNKNOWN_OPTION", "repository-local", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.inspect", "refused", "USAGE_INVALID_ARGUMENTS", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.inspect", "refused", "DOMAIN_INPUT_MISSING", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-missing"],
	["repair-lab.inspect", "refused", "DOMAIN_INPUT_MALFORMED", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-malformed"],
	["repair-lab.inspect", "refused", "DOMAIN_INPUT_UNREADABLE", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-unreadable"],
	["repair-lab.inspect", "refused", "SCHEMA_STATE_INVALID", "inspect", "unchanged", false, null, "next-action", true, 4, "repair-lab.state-schema-invalid"],
	["repair-lab.inspect-diagnostics", "refused", "DOMAIN_INPUT_MISSING", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-missing"],
	["repair-lab.apply", "refused", "DOMAIN_PREVIEW_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, null],
	["repair-lab.repair", "refused", "DOMAIN_PREVIEW_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, null],
	["repair-lab.repair-retry", "refused", "DOMAIN_PREVIEW_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, null],
	["repair-lab.apply", "refused", "DOMAIN_PREVIEW_CONSUMED", "repository-local", "unchanged", false, null, "next-action", true, 3, null],
	["repair-lab.repair", "refused", "DOMAIN_PREVIEW_CONSUMED", "repository-local", "unchanged", false, null, "next-action", true, 3, null],
	["repair-lab.repair-retry", "refused", "DOMAIN_PREVIEW_CONSUMED", "repository-local", "unchanged", false, null, "next-action", true, 3, null],
	["repair-lab.repair", "refused", "DOMAIN_REPAIR_NOT_REQUIRED", "repository-local", "unchanged", false, null, "next-action", false, 3, null],
	["repair-lab.repair", "refused", "UNAVAILABLE_STORAGE_BUSY", "repository-local", "unchanged", true, 25, "next-action", true, 75, null],
	["repair-lab.repair-retry", "refused", "UNAVAILABLE_STORAGE_BUSY", "repository-local", "unchanged", true, 25, "next-action", true, 75, null],
	["repair-lab.apply", "failed", "INTERNAL_EFFECT_NOT_OBSERVED", "repository-local", "unknown", false, null, "next-action", true, 1, null],
	["repair-lab.recover", "success", null, "repository-local", "unchanged", true, null, "next-action", false, 0, null],
	// Usage refusals keep the routed identity (section 3.4): unknown option and invalid arguments per routed command.
	["repair-lab.inspect-diagnostics", "refused", "USAGE_UNKNOWN_OPTION", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.repair-retry", "refused", "USAGE_UNKNOWN_OPTION", "repository-local", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.status", "refused", "USAGE_INVALID_ARGUMENTS", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.inspect-diagnostics", "refused", "USAGE_INVALID_ARGUMENTS", "inspect", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.preview", "refused", "USAGE_INVALID_ARGUMENTS", "repository-local", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.apply", "refused", "USAGE_INVALID_ARGUMENTS", "repository-local", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.repair", "refused", "USAGE_INVALID_ARGUMENTS", "repository-local", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.repair-retry", "refused", "USAGE_INVALID_ARGUMENTS", "repository-local", "unchanged", false, null, "next-action", true, 2, null],
	["repair-lab.recover", "refused", "USAGE_INVALID_ARGUMENTS", "repository-local", "unchanged", false, null, "next-action", true, 2, null],
	// Stale previews on the repair routes (3.5 step 6 with a repair preview at an older revision).
	["repair-lab.repair", "refused", "DOMAIN_PREVIEW_STALE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.stale-preview"],
	["repair-lab.repair-retry", "refused", "DOMAIN_PREVIEW_STALE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.stale-preview"],
	// W1: an unexpected exception before any durable write, on every routed command (section 5).
	["repair-lab.status", "failed", "INTERNAL_UNEXPECTED", "inspect", "unchanged", false, null, "next-action", true, 1, null],
	["repair-lab.inspect", "failed", "INTERNAL_UNEXPECTED", "inspect", "unchanged", false, null, "next-action", true, 1, null],
	["repair-lab.inspect-diagnostics", "failed", "INTERNAL_UNEXPECTED", "inspect", "unchanged", false, null, "next-action", true, 1, null],
	["repair-lab.preview", "failed", "INTERNAL_UNEXPECTED", "repository-local", "unchanged", false, null, "next-action", true, 1, null],
	["repair-lab.apply", "failed", "INTERNAL_UNEXPECTED", "repository-local", "unchanged", false, null, "next-action", true, 1, null],
	["repair-lab.repair", "failed", "INTERNAL_UNEXPECTED", "repository-local", "unchanged", false, null, "next-action", true, 1, null],
	["repair-lab.repair-retry", "failed", "INTERNAL_UNEXPECTED", "repository-local", "unchanged", false, null, "next-action", true, 1, null],
	["repair-lab.recover", "failed", "INTERNAL_UNEXPECTED", "repository-local", "unchanged", false, null, "next-action", true, 1, null],
	// W2: a durable write was attempted and nothing established its outcome (section 5, 8.1). Coordinator ruling
	// (implementation01/w2-owner-resolution.md): outcome failed with the existing cause INTERNAL_EFFECT_OUTCOME_UNKNOWN,
	// a tuple distinct from W1's failed|INTERNAL_UNEXPECTED|unchanged and from row 6's unknown|INTERNAL_EFFECT_OUTCOME_UNKNOWN.
	["repair-lab.apply", "failed", "INTERNAL_EFFECT_OUTCOME_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.write-outcome-unknown"],
	["repair-lab.repair", "failed", "INTERNAL_EFFECT_OUTCOME_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.write-outcome-unknown"],
	["repair-lab.repair-retry", "failed", "INTERNAL_EFFECT_OUTCOME_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.write-outcome-unknown"],
	// Input refusals reach every resource-reading identity (F3): the resource is read before any route policy runs.
	["repair-lab.status", "refused", "DOMAIN_INPUT_MISSING", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-missing"],
	["repair-lab.status", "refused", "DOMAIN_INPUT_MALFORMED", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-malformed"],
	["repair-lab.status", "refused", "DOMAIN_INPUT_UNREADABLE", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-unreadable"],
	["repair-lab.status", "refused", "SCHEMA_STATE_INVALID", "inspect", "unchanged", false, null, "next-action", true, 4, "repair-lab.state-schema-invalid"],
	["repair-lab.inspect-diagnostics", "refused", "DOMAIN_INPUT_MALFORMED", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-malformed"],
	["repair-lab.inspect-diagnostics", "refused", "DOMAIN_INPUT_UNREADABLE", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-unreadable"],
	["repair-lab.inspect-diagnostics", "refused", "SCHEMA_STATE_INVALID", "inspect", "unchanged", false, null, "next-action", true, 4, "repair-lab.state-schema-invalid"],
	["repair-lab.preview", "refused", "DOMAIN_INPUT_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-missing"],
	["repair-lab.preview", "refused", "DOMAIN_INPUT_MALFORMED", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-malformed"],
	["repair-lab.preview", "refused", "DOMAIN_INPUT_UNREADABLE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-unreadable"],
	["repair-lab.preview", "refused", "SCHEMA_STATE_INVALID", "repository-local", "unchanged", false, null, "next-action", true, 4, "repair-lab.state-schema-invalid"],
	["repair-lab.apply", "refused", "DOMAIN_INPUT_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-missing"],
	["repair-lab.apply", "refused", "DOMAIN_INPUT_MALFORMED", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-malformed"],
	["repair-lab.apply", "refused", "DOMAIN_INPUT_UNREADABLE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-unreadable"],
	["repair-lab.apply", "refused", "SCHEMA_STATE_INVALID", "repository-local", "unchanged", false, null, "next-action", true, 4, "repair-lab.state-schema-invalid"],
	["repair-lab.repair", "refused", "DOMAIN_INPUT_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-missing"],
	["repair-lab.repair", "refused", "DOMAIN_INPUT_MALFORMED", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-malformed"],
	["repair-lab.repair", "refused", "DOMAIN_INPUT_UNREADABLE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-unreadable"],
	["repair-lab.repair", "refused", "SCHEMA_STATE_INVALID", "repository-local", "unchanged", false, null, "next-action", true, 4, "repair-lab.state-schema-invalid"],
	["repair-lab.repair-retry", "refused", "DOMAIN_INPUT_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-missing"],
	["repair-lab.repair-retry", "refused", "DOMAIN_INPUT_MALFORMED", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-malformed"],
	["repair-lab.repair-retry", "refused", "DOMAIN_INPUT_UNREADABLE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-unreadable"],
	["repair-lab.repair-retry", "refused", "SCHEMA_STATE_INVALID", "repository-local", "unchanged", false, null, "next-action", true, 4, "repair-lab.state-schema-invalid"],
	["repair-lab.recover", "refused", "DOMAIN_INPUT_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-missing"],
	["repair-lab.recover", "refused", "DOMAIN_INPUT_MALFORMED", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-malformed"],
	["repair-lab.recover", "refused", "DOMAIN_INPUT_UNREADABLE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.input-unreadable"],
	["repair-lab.recover", "refused", "SCHEMA_STATE_INVALID", "repository-local", "unchanged", false, null, "next-action", true, 4, "repair-lab.state-schema-invalid"],
	["repair-lab.inspect-diagnostics", "refused", "DOMAIN_PATH_ESCAPE", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.hostile-input"],
	// Admission refusals on the repair identities (F3): authority precedes every preview lookup; the retry plan shares step 8.
	["repair-lab.repair", "refused", "DOMAIN_AUTHORITY_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.prohibited-automation"],
	["repair-lab.repair-retry", "refused", "DOMAIN_AUTHORITY_MISSING", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.prohibited-automation"],
	["repair-lab.repair-retry", "refused", "DOMAIN_REPAIR_NOT_REQUIRED", "repository-local", "unchanged", false, null, "next-action", false, 3, null],
	["repair-lab.apply", "refused", "UNAVAILABLE_STORAGE_BUSY", "repository-local", "unchanged", true, 25, "next-action", true, 75, null],
	// W3 on the repair identities: effect.write-journal is in the repair plan too.
	["repair-lab.repair", "unknown", "INTERNAL_EFFECT_OUTCOME_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.partial-unknown"],
	["repair-lab.repair-retry", "unknown", "INTERNAL_EFFECT_OUTCOME_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.partial-unknown"],
	// W4: an effect returned but read-back showed no change, on every effect-executing route.
	["repair-lab.repair", "failed", "INTERNAL_EFFECT_NOT_OBSERVED", "repository-local", "unknown", false, null, "next-action", true, 1, null],
	["repair-lab.repair-retry", "failed", "INTERNAL_EFFECT_NOT_OBSERVED", "repository-local", "unknown", false, null, "next-action", true, 1, null],
	// Egress fallback rows under the accepted D6-c mapping (section 5): the brief's 28 rows plus the two
	// unknown|INTERNAL_RESULT_UNKNOWN rows of the repair identities that W3 makes reachable (F3).
	["repair-lab.repair", "unknown", "INTERNAL_RESULT_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.repair-retry", "unknown", "INTERNAL_RESULT_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.help", "failed", "INTERNAL_RESULT_UNCHANGED", "inspect", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.help", "refused", "INTERNAL_PREPARATION", "inspect", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.discover", "failed", "INTERNAL_RESULT_UNCHANGED", "inspect", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.discover", "refused", "INTERNAL_PREPARATION", "inspect", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.status", "failed", "INTERNAL_RESULT_UNCHANGED", "inspect", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.status", "refused", "INTERNAL_PREPARATION", "inspect", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.inspect", "failed", "INTERNAL_RESULT_UNCHANGED", "inspect", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.inspect", "refused", "INTERNAL_PREPARATION", "inspect", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.inspect-diagnostics", "failed", "INTERNAL_RESULT_UNCHANGED", "inspect", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.inspect-diagnostics", "refused", "INTERNAL_PREPARATION", "inspect", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.preview", "failed", "INTERNAL_RESULT_UNCHANGED", "repository-local", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.preview", "refused", "INTERNAL_PREPARATION", "repository-local", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.apply", "refused", "INTERNAL_PREPARATION", "repository-local", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.apply", "unknown", "INTERNAL_RESULT_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.apply", "failed", "INTERNAL_RESULT_COMPLETED", "repository-local", "completed", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.apply", "failed", "INTERNAL_RESULT_UNCHANGED", "repository-local", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.apply", "failed", "INTERNAL_RESULT_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.repair", "refused", "INTERNAL_PREPARATION", "repository-local", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.repair", "failed", "INTERNAL_RESULT_COMPLETED", "repository-local", "completed", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.repair", "failed", "INTERNAL_RESULT_UNCHANGED", "repository-local", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.repair", "failed", "INTERNAL_RESULT_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.repair-retry", "refused", "INTERNAL_PREPARATION", "repository-local", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.repair-retry", "failed", "INTERNAL_RESULT_COMPLETED", "repository-local", "completed", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.repair-retry", "failed", "INTERNAL_RESULT_UNCHANGED", "repository-local", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.repair-retry", "failed", "INTERNAL_RESULT_UNKNOWN", "repository-local", "unknown", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.recover", "failed", "INTERNAL_RESULT_UNCHANGED", "repository-local", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.recover", "refused", "INTERNAL_PREPARATION", "repository-local", "unchanged", false, null, "next-action", true, 1, "repair-lab.envelope-invalid"],
	["repair-lab.recover", "unknown", "INTERNAL_RESULT_UNKNOWN", "repository-local", "unknown", false, null, "handoff", false, 1, "repair-lab.envelope-invalid"],
	// Internal state containment (PR 184, thread 4003813337): a symlinked preview, journal or resource file is refused on
	// every routed identity that reads it, with the fixture's hostile-input station; the inspect rows above already exist.
	["repair-lab.status", "refused", "DOMAIN_PATH_ESCAPE", "inspect", "unchanged", false, null, "next-action", true, 3, "repair-lab.hostile-input"],
	["repair-lab.preview", "refused", "DOMAIN_PATH_ESCAPE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.hostile-input"],
	["repair-lab.apply", "refused", "DOMAIN_PATH_ESCAPE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.hostile-input"],
	["repair-lab.repair", "refused", "DOMAIN_PATH_ESCAPE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.hostile-input"],
	["repair-lab.repair-retry", "refused", "DOMAIN_PATH_ESCAPE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.hostile-input"],
	["repair-lab.recover", "refused", "DOMAIN_PATH_ESCAPE", "repository-local", "unchanged", false, null, "next-action", true, 3, "repair-lab.hostile-input"],
]

export const STATION_ROWS: readonly StationRow[] = ROWS.map(
	([commandIdentity, outcome, causeCode, effectClass, transactionState, retryable, retryDelayMilliseconds, guidance, repairAction, exit, fixtureLabel]) => ({
		commandIdentity,
		outcome,
		causeCode,
		effectClass,
		transactionState,
		retryable,
		retryDelayMilliseconds,
		guidance,
		repairAction,
		exit,
		fixtureLabel,
	}),
)
