// Resources Index: each project's `resources.md`, which lists every note the project owns plus a human-curated
// shared block. One analysis serves both consumers: `check` reads its findings, and `vault-notes resources` reads its
// proposed file content. Ownership and roles come from Vault Catalogue placement; this module never parses a path to
// decide who owns a note. It reads only the notes it is given and never writes.
import path from "node:path";
import type { MarkdownNote } from "./vault-catalogue";
import type { VaultContract } from "./vault-contract";

/** Stable machine-readable identifiers of the resources rules. Consumers match on these, never on message text. */
export const RESOURCES_FINDING_IDS = [
  "resources-contract-invalid",
  "resources-route-missing",
  "resources-index-missing",
  "resources-block-invalid",
  "resources-entry-missing",
  "resources-entry-stale",
  "resources-entry-foreign",
  "resources-entry-duplicate",
] as const;

type ResourcesFindingId = (typeof RESOURCES_FINDING_IDS)[number];

/** One resources finding, shaped like every other check finding. */
export interface ResourcesFinding {
  id: (typeof RESOURCES_FINDING_IDS)[number];
  file: string;
  message: string;
  detail: Record<string, string>;
}

/** The contract's `projectResources` key: absent (rules inactive, default index file), active, or invalid. */
export type ResourcesPolicy =
  | { state: "inactive" | "active"; indexFile: string }
  | { state: "invalid"; reason: string };

/** One project's proposal: its entry set, what regeneration would write, and the findings the check reports. */
export interface ResourcesProposal {
  project: string;
  indexPath: string;
  /** Vault-relative paths of the project-owned notes the generated block lists. */
  notes: string[];
  /** Vault-relative paths of the folder maps (nested and governed-folder READMEs) the generated block links. */
  folderMaps: string[];
  /** How the proposed content relates to the current index file; blocked means its markers need a hand repair. */
  state: "create" | "update" | "current" | "blocked";
  /** The complete proposed index file; null when the current file's block markers must be repaired by hand. */
  content: string | null;
  findings: ResourcesFinding[];
}

const DEFAULT_INDEX_FILE = "resources.md";
const CONTRACT_FILE = "schemas/frontmatter-contract.json";
const GENERATED = { name: "generated", start: "<!-- project-resources:generated:start -->", end: "<!-- project-resources:generated:end -->" };
const SHARED = { name: "shared", start: "<!-- project-resources:shared:start -->", end: "<!-- project-resources:shared:end -->" };
const GENERATED_NOTICE =
  "<!-- Generated by vault-notes resources from each note's frontmatter. Regeneration replaces this block; curate shared notes above. -->";
const EMPTY_BLOCK = "_No project-owned reference or decision notes yet._";
const HISTORICAL_STATUSES = new Set(["archived", "superseded"]);

/** Read and validate the contract's activation key. Unknown or malformed values are invalid, never ignored. */
export function readResourcesPolicy(contract: VaultContract): ResourcesPolicy {
  const raw = contract.projectResources;
  if (raw === undefined) return { state: "inactive", indexFile: DEFAULT_INDEX_FILE };
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) return { state: "invalid", reason: "it must be an object" };
  const unknownKey = Object.keys(raw).find((key) => key !== "indexFile");
  if (unknownKey !== undefined) return { state: "invalid", reason: `remove unknown key '${unknownKey}'` };
  const { indexFile } = raw as { indexFile?: unknown };
  if (typeof indexFile !== "string" || !/^[a-z0-9][a-z0-9._-]*\.md$/.test(indexFile)) {
    return { state: "invalid", reason: "'indexFile' must be a lowercase Markdown file name such as 'resources.md'" };
  }
  if (Object.hasOwn(contract.routing.projectFiles, indexFile)) {
    return { state: "invalid", reason: `'indexFile' must not be the project packet file '${indexFile}'` };
  }
  return { state: "active", indexFile };
}

/** Findings for `check`: none while the key is absent; the whole-vault resources rules once it is present. */
export function resourcesFindings(notes: readonly MarkdownNote[], contract: VaultContract): ResourcesFinding[] {
  const policy = readResourcesPolicy(contract);
  if (policy.state === "inactive") return [];
  if (policy.state === "invalid") {
    return [
      {
        id: "resources-contract-invalid",
        file: CONTRACT_FILE,
        message: `fix 'projectResources': ${policy.reason}`,
        detail: { field: "projectResources" },
      },
    ];
  }
  return projectsOf(notes).flatMap((project) => analyseProject(notes, project, policy.indexFile).findings);
}

/** Every project that holds at least one note, sorted by slug. */
export function projectsOf(notes: readonly MarkdownNote[]): string[] {
  return [...new Set(notes.flatMap((note) => (note.placement.project === null ? [] : [note.placement.project])))].sort();
}

/**
 * Propose each named project's index. `updated` dates a newly created index only; regenerating an existing index
 * rewrites nothing outside its generated block, frontmatter included.
 */
export function proposeResources(
  notes: readonly MarkdownNote[],
  projects: readonly string[],
  indexFile: string,
  updated: string,
): ResourcesProposal[] {
  return projects.map((project) => {
    const analysis = analyseProject(notes, project, indexFile);
    const { content, state } = proposeContent(analysis, updated);
    return {
      project,
      indexPath: analysis.indexPath,
      notes: analysis.owned.map((note) => note.relativePath),
      folderMaps: analysis.maps.map((note) => note.relativePath),
      state,
      content,
      findings: analysis.findings,
    };
  });
}

// ---- analysis ----

interface ProjectAnalysis {
  project: string;
  indexPath: string;
  readme: MarkdownNote | undefined;
  owned: MarkdownNote[];
  maps: MarkdownNote[];
  index: IndexDocument | null;
  findings: ResourcesFinding[];
}

/** A marked block as the zero-based line numbers of its two marker lines. */
interface Block {
  start: number;
  end: number;
}

interface IndexDocument {
  lines: string[];
  generated: Block | null;
  /** First marker problem; the generator refuses to rewrite a document that has one. */
  invalid: string | null;
}

function analyseProject(notes: readonly MarkdownNote[], project: string, indexFile: string): ProjectAnalysis {
  const inProject = notes.filter((note) => note.placement.project === project);
  const indexNote = inProject.find((note) => note.placement.projectPath === indexFile);
  const analysis: ProjectAnalysis = {
    project,
    indexPath: `projects/${project}/${indexFile}`,
    readme: inProject.find((note) => note.placement.projectRole === "packet" && note.placement.projectPath === "README.md"),
    owned: inProject.filter((note) => note.placement.projectRole === "note" && note !== indexNote),
    maps: inProject.filter((note) => note.placement.projectRole === "folder-map"),
    index: indexNote === undefined ? null : parseIndex(indexNote.content),
    findings: [],
  };
  analysis.findings = [...routeFindings(analysis, indexFile), ...indexFindings(analysis)];
  return analysis;
}

function routeFindings({ project, readme }: ProjectAnalysis, indexFile: string): ResourcesFinding[] {
  if (readme !== undefined && localTargets(readme.content).some((target) => target === indexFile)) return [];
  return [
    {
      id: "resources-route-missing",
      file: `projects/${project}/README.md`,
      message: `link the Resources Index from this README, for example '- [Resources index](${indexFile})'`,
      detail: { project, target: indexFile },
    },
  ];
}

function indexFindings(analysis: ProjectAnalysis): ResourcesFinding[] {
  const { project, indexPath, index } = analysis;
  const regenerate = `regenerate with 'vault-notes resources --project ${project}'`;
  if (index === null) {
    return [{ id: "resources-index-missing", file: indexPath, message: `create this Resources Index; ${regenerate}`, detail: { project } }];
  }
  if (index.invalid !== null || index.generated === null) {
    const reason = index.invalid ?? `add the generated block: one '${GENERATED.start}' line followed by one '${GENERATED.end}' line`;
    return [{ id: "resources-block-invalid", file: indexPath, message: `${reason}; ${regenerate}`, detail: { project } }];
  }
  return entryFindings(analysis, index.lines.slice(index.generated.start + 1, index.generated.end), regenerate);
}

/** Compare the generated block's entries with the expected set: every owned note and folder map, each once. */
function entryFindings(analysis: ProjectAnalysis, blockLines: string[], regenerate: string): ResourcesFinding[] {
  const { project, indexPath } = analysis;
  const expected = new Set([...analysis.owned, ...analysis.maps].map((note) => note.placement.projectPath ?? note.relativePath));
  const seen = new Set<string>();
  const findings: ResourcesFinding[] = [];
  const add = (id: ResourcesFindingId, message: string, detail: Record<string, string>) =>
    findings.push({ id, file: indexPath, message: `${message}; ${regenerate}`, detail: { project, ...detail } });

  for (const target of blockLines.flatMap(entryTarget)) {
    const projectPath = resolveInProject(target);
    if (projectPath === null) {
      add("resources-entry-foreign", `move the entry '${target}' to the shared block: the generated block lists only notes this project owns`, { target });
    } else if (!expected.has(projectPath)) {
      add("resources-entry-stale", `remove the entry '${target}': it is not a reference or decision note or folder map this project owns`, { target });
    } else if (seen.has(projectPath)) {
      add("resources-entry-duplicate", `list '${projectPath}' once in the generated block`, { target });
    }
    if (projectPath !== null) seen.add(projectPath);
  }
  for (const projectPath of expected) {
    if (!seen.has(projectPath)) add("resources-entry-missing", `add the entry for '${projectPath}'`, { path: projectPath });
  }
  return findings;
}

// ---- document parsing ----

function parseIndex(content: string): IndexDocument {
  const lines = content.split("\n");
  const generated = findBlock(lines, GENERATED);
  const shared = findBlock(lines, SHARED);
  const separate = !(isBlock(generated) && isBlock(shared) && overlaps(generated, shared));
  const invalid =
    [generated, shared].find((parse): parse is string => typeof parse === "string") ??
    (separate ? null : "keep the shared and generated blocks separate: neither block may contain the other's markers");
  return { lines, generated: isBlock(generated) ? generated : null, invalid };
}

/** A block: absent (null), present exactly once and in order, or a repair message when its markers are malformed. */
function findBlock(lines: string[], markers: typeof GENERATED): Block | null | string {
  const starts = lines.flatMap((line, index) => (line.trim() === markers.start ? [index] : []));
  const ends = lines.flatMap((line, index) => (line.trim() === markers.end ? [index] : []));
  if (starts.length === 0 && ends.length === 0) return null;
  const [start] = starts;
  const [end] = ends;
  if (starts.length !== 1 || ends.length !== 1 || start === undefined || end === undefined || end < start) {
    return `keep exactly one '${markers.start}' line followed by one '${markers.end}' line in the ${markers.name} block`;
  }
  return { start, end };
}

function isBlock(value: Block | null | string): value is Block {
  return typeof value === "object" && value !== null;
}

function overlaps(left: Block, right: Block): boolean {
  return left.start < right.end && right.start < left.end;
}

/** The link target of a list-item entry: the first inline link on a `- ` or `* ` line. */
function entryTarget(line: string): string[] {
  const target = /^\s*[-*+]\s+\[(?:\\.|[^\]\\])*\]\(([^)]*)\)/.exec(line)?.[1];
  return target === undefined ? [] : [linkPath(target)];
}

/** Every inline local link target in a note, resolved against the note's own folder and stripped of any fragment. */
function localTargets(content: string): string[] {
  return [...content.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)].flatMap((match) => {
    const resolved = resolveInProject(linkPath(match[1] ?? ""));
    return resolved === null ? [] : [resolved];
  });
}

/** The destination of a raw Markdown link target: unwrapped from `<>` and without any title. */
function linkPath(raw: string): string {
  const trimmed = raw.trim();
  if (trimmed.startsWith("<")) return trimmed.slice(1, trimmed.indexOf(">") < 0 ? undefined : trimmed.indexOf(">"));
  return trimmed.split(/\s+/, 1)[0] ?? "";
}

/**
 * A link target written in a note at the project root, as a normalised path inside the project; null when it names
 * a URL, an anchor, an absolute path, or anything outside the project folder.
 */
function resolveInProject(target: string): string | null {
  if (target === "" || /^[a-z][a-z0-9+.-]*:|^[#/]/i.test(target)) return null;
  const withoutFragment = target.split("#", 1)[0] ?? "";
  const normalised = path.posix.normalize(safeDecode(withoutFragment));
  if (normalised === "." || normalised === ".." || normalised.startsWith("../") || normalised.startsWith("/")) return null;
  return normalised;
}

function safeDecode(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

// ---- rendering ----

function proposeContent(analysis: ProjectAnalysis, updated: string): Pick<ResourcesProposal, "content" | "state"> {
  const body = renderGeneratedBody(analysis.owned, analysis.maps);
  const { index } = analysis;
  if (index === null) return { content: renderNewIndex(analysis, body, updated), state: "create" };
  if (index.invalid !== null) return { content: null, state: "blocked" };
  const current = index.lines.join("\n");
  const content = index.generated === null ? appendGeneratedBlock(current, body) : replaceBlock(index.lines, index.generated, body);
  return { content, state: content === current ? "current" : "update" };
}

function replaceBlock(lines: string[], block: Block, body: string[]): string {
  return [...lines.slice(0, block.start + 1), ...body, ...lines.slice(block.end)].join("\n");
}

function appendGeneratedBlock(content: string, body: string[]): string {
  const base = content.endsWith("\n") ? content : `${content}\n`;
  return `${base}\n## Project-owned notes\n\n${[GENERATED.start, ...body, GENERATED.end].join("\n")}\n`;
}

/** Folder maps first, then owned notes grouped by folder: the project root first, then folders in path order. */
function renderGeneratedBody(owned: MarkdownNote[], maps: MarkdownNote[]): string[] {
  if (owned.length === 0 && maps.length === 0) return [GENERATED_NOTICE, "", EMPTY_BLOCK];
  const groups = new Map<string, MarkdownNote[]>();
  if (maps.length > 0) groups.set("Folder maps", maps);
  const folders = [...new Set(owned.map((note) => note.placement.projectFolder ?? ""))].sort();
  for (const folder of folders) {
    groups.set(folder === "" ? "Project root" : folder, owned.filter((note) => (note.placement.projectFolder ?? "") === folder));
  }
  const lines = [GENERATED_NOTICE];
  for (const [heading, notes] of groups) lines.push("", `### ${heading}`, "", ...notes.map(renderEntry));
  return lines;
}

/** `- [Title](path)`, a status mark for historical notes, then `: summary`, all from the note's frontmatter. */
function renderEntry(note: MarkdownNote): string {
  const projectPath = note.placement.projectPath ?? note.relativePath;
  const title = frontmatterText(note, "title") || path.posix.basename(projectPath, ".md");
  const status = frontmatterText(note, "status");
  const summary = frontmatterText(note, "summary");
  const mark = HISTORICAL_STATUSES.has(status) ? ` _(${status})_` : "";
  return `- [${title.replace(/[[\]\\]/g, "\\$&")}](${encodePath(projectPath)})${mark}${summary === "" ? "" : `: ${summary}`}`;
}

function frontmatterText(note: MarkdownNote, field: string): string {
  const value = note.frontmatter?.[field];
  return typeof value === "string" ? value.replace(/\s+/g, " ").trim() : "";
}

function encodePath(projectPath: string): string {
  return projectPath
    .split("/")
    .map((segment) => encodeURIComponent(segment).replace(/[()]/g, (character) => `%${character.charCodeAt(0).toString(16).toUpperCase()}`))
    .join("/");
}

function renderNewIndex(analysis: ProjectAnalysis, body: string[], updated: string): string {
  const name = (analysis.readme === undefined ? "" : frontmatterText(analysis.readme, "title")) || analysis.project;
  return [
    "---",
    `title: ${JSON.stringify(`${name} resources`)}`,
    "type: reference",
    "status: active",
    `updated: ${updated}`,
    `summary: ${JSON.stringify(`Resources Index for ${name}: every reference and decision note the project owns, plus curated shared resources.`)}`,
    "related:",
    "  - README.md",
    "---",
    "",
    `# ${name} resources`,
    "",
    "Back to the [project packet](README.md).",
    "",
    "## Shared resources",
    "",
    "Notes owned elsewhere appear here only by explicit, curated association. Regeneration never adds or removes them.",
    "",
    SHARED.start,
    SHARED.end,
    "",
    "## Project-owned notes",
    "",
    GENERATED.start,
    ...body,
    GENERATED.end,
    "",
  ].join("\n");
}
