import { describe, expect, test } from 'bun:test'
import { compileSpecificationCandidate } from '../src/index.ts'
import { readCandidate } from './support/candidates.ts'
import { emitAmended } from './support/emission.ts'

/**
 * Every generated module carries the banner naming the generator and the
 * specification digest it derives from. Regeneration-and-compare cannot catch
 * a dropped banner, because it compares a regeneration to itself; only an
 * assertion on the emitted bytes holds this line.
 *
 * The digest oracle is an independent compile of the same candidate text, and
 * the digest string appearing in the emitted bytes is the positive control
 * that the banner really reached the artifact.
 */

/**
 * Deliberate independent oracle: the version literal each candidate text
 * declares under `spec_meta.input_schema_version`, restated here rather than
 * read back from the IR the banner is rendered from. The two candidates are on
 * different Input Schema Versions, so one shared literal would assert the
 * wrong identity for one of them.
 */
const DECLARED_SCHEMA_VERSIONS = {
	'vault-git': '2',
	fallow: 'spike-draft-1',
} as const

describe('every generated artifact carries the banner', () => {
	for (const product of ['vault-git', 'fallow'] as const) {
		test(`${product} modules open with the generator banner and its digest`, async () => {
			const compiled = compileSpecificationCandidate(
				await readCandidate(product),
			)
			expect(compiled.ok).toBe(true)
			if (!compiled.ok) return

			const { emission } = await emitAmended(product)
			const tsModules = emission.modules.filter((module) =>
				module.path.endsWith('.ts'),
			)
			expect(tsModules.length).toBeGreaterThan(0)

			for (const module of tsModules) {
				expect({
					path: module.path,
					opensWithBanner: module.contents.startsWith(
						'// Generated by the Agent-Native State Machine Generator. Do not edit.\n',
					),
					carriesDigest: module.contents.includes(
						`// specification digest: ${compiled.digest.specificationDigest}\n`,
					),
					carriesSchemaVersion: module.contents.includes(
						`// input schema version: ${DECLARED_SCHEMA_VERSIONS[product]}\n`,
					),
				}).toEqual({
					path: module.path,
					opensWithBanner: true,
					carriesDigest: true,
					carriesSchemaVersion: true,
				})
			}
		})
	}
})
