/**
 * Rendering for the pilot's generated Projection Composer selection code.
 *
 * The issue 55 YAGNI ruling generates the Projection Composer's data tables
 * for every product and its selection code only for greenfield products. The
 * pilot is greenfield, so this renderer emits the selection module beside the
 * other generated artifacts. Like every emitter input, it is pure: identical
 * inputs produce identical bytes, and nothing here reads a clock, a random
 * value, or an absolute path.
 *
 * The selection is a total lookup from Branch Station id to the complete
 * State Projection meaning, each row carrying exactly one Next Safe Action.
 * Mapping Observed Facts to the observed station stays with the front door:
 * Input Schema v1 declares no fact-to-branch surface, and inventing one here
 * would publish policy the candidate never admitted (recorded in the
 * candidate's unresolved_decisions for stage 5).
 */
import type {
	SemanticExpectationRow,
	SpecificationIr,
} from '../../src/index.ts'
import { NEXT_SAFE_ACTION_KINDS, RETRY_POSTURES } from '../../src/index.ts'
import { renderProjectionCoreFields } from '../../src/render.ts'
import { PILOT_CONSTANT_PREFIX, PILOT_TYPE_PREFIX } from './pilot-naming.ts'

/** JSON string literal; generated text carries double quotes throughout. */
function lit(value: string): string {
	return JSON.stringify(value)
}

function union(values: readonly string[]): string {
	return [...values]
		.sort()
		.map((value) => lit(value))
		.join(' | ')
}

function header(ir: SpecificationIr, digest: string): string {
	return [
		'// Generated by the Agent-Native State Machine Generator. Do not edit.',
		'//',
		'// This file is one artifact of a disposable Generated Artifact Set derived',
		`// from the Admitted State-Machine Specification for ${ir.specMeta.product}.`,
		'// Edit the specification and regenerate; a hand edit is Generated Artifact',
		'// Drift and will be refused.',
		'//',
		`// specification digest: ${digest}`,
		`// input schema version: ${ir.specMeta.inputSchemaVersion}`,
		'',
	].join('\n')
}

/** One projection literal, keys in a fixed order so rendering is deterministic. */
function renderRow(row: SemanticExpectationRow): string {
	const parts = [
		`\t\tactionId: ${lit(row.expectedActionId)},`,
		`\t\tstate: ${lit(row.state)},`,
		`\t\texitMeaning: ${lit(row.exitMeaning)},`,
	]
	if (row.blocker !== undefined) {
		parts.push(`\t\tblocker: ${lit(row.blocker)},`)
	}
	parts.push(...renderProjectionCoreFields(row))
	return [`\t${lit(row.stationId)}: {`, ...parts, '\t},'].join('\n')
}

/**
 * Renders the Projection Composer selection module.
 *
 * Rows are emitted in codepoint order of their station ids, matching the
 * canonical station order the other artifacts use, and the table satisfies a
 * record over the station id tuple so a missing or extra row fails typecheck
 * rather than review.
 */
export function renderProjectionComposer(input: {
	readonly ir: SpecificationIr
	readonly digest: string
	readonly rows: readonly SemanticExpectationRow[]
}): string {
	const { ir, digest, rows } = input
	const sorted = [...rows].sort((a, b) =>
		a.stationId < b.stationId ? -1 : a.stationId > b.stationId ? 1 : 0,
	)
	const stationIdType = `${PILOT_TYPE_PREFIX}StationId`
	const tableName = `${PILOT_CONSTANT_PREFIX}_PROJECTION_TABLE`

	return [
		header(ir, digest),
		'/**',
		' * Generated Projection Composer selection code.',
		' *',
		" * The issue 55 ruling generates the Projection Composer's data tables for",
		' * every product and its selection code only for greenfield products; this',
		' * pilot is greenfield. Selection is total over the Branch Station ids and',
		' * every State Projection carries exactly one Next Safe Action. The front',
		' * door supplies the observed station id and never assembles a projection',
		' * by hand.',
		' */',
		`import type { ${stationIdType} } from './branch-station-catalog.ts'`,
		'',
		'/** The complete State Projection meaning selected for one station. */',
		`export const ${tableName} = {`,
		...sorted.map((row) => renderRow(row)),
		'} as const satisfies Record<',
		`\t${stationIdType},`,
		'\t{',
		'\t\treadonly actionId: string',
		'\t\treadonly state: string',
		'\t\treadonly exitMeaning: string',
		'\t\treadonly blocker?: string',
		// Custody: restates the authority vocabulary owned by
		// src/derivation-facts.ts (BRANCH_FACTS authority column) and
		// src/expectations.ts (SemanticExpectationRow.authority). src exports
		// neither and is out of stage-4 scope; the export is on the stage-5
		// worklist. Delete this restatement when src owns an exported constant.
		`\t\treadonly authority: ${union(['granted', 'denied'])}`,
		`\t\treadonly retrySafety: ${union(RETRY_POSTURES)}`,
		// Custody: restates the Projection Completeness vocabulary owned as
		// inline type unions by src/derivation-facts.ts and
		// src/expectations.ts (SemanticExpectationRow.projectionCompleteness).
		// Same forced restatement and stage-5 record as authority above.
		`\t\treadonly projectionCompleteness: ${union(['complete', 'incomplete'])}`,
		`\t\treadonly nextSafeAction: ${union(NEXT_SAFE_ACTION_KINDS)}`,
		// Custody: restates the Stop Scope vocabulary owned by the unexported
		// STOP_SCOPES const in src/schema.ts. Same forced restatement and
		// stage-5 record as authority above.
		`\t\treadonly stopScope?: ${union(['domain_terminal', 'agent_terminal'])}`,
		'\t}',
		'>',
		'',
		`export type ${PILOT_TYPE_PREFIX}StateProjection =`,
		`\t(typeof ${tableName})[${stationIdType}]`,
		'',
		'/** Select the State Projection for one observed Branch Station. */',
		`export function select${PILOT_TYPE_PREFIX}Projection(`,
		`\tstationId: ${stationIdType},`,
		`): ${PILOT_TYPE_PREFIX}StateProjection {`,
		`\treturn ${tableName}[stationId]`,
		'}',
		'',
	].join('\n')
}
