/**
 * Stable result-contract identity for WorkTree render and shared lifecycle envelopes.
 *
 * Carried in every facade success/error envelope so agents can pin the
 * package that produced the result. Mirrors the record-decision contract-id
 * convention.
 */
export const WORKTREE_CONTRACT_ID = "worktree.workspace" as const;

/**
 * Schema version for package-owned WorkTree result data.
 *
 * Bump when the shape of the result data or {@link DriftRecord} changes in a
 * way downstream parsers must notice.
 */
export const WORKTREE_SCHEMA_VERSION = "1" as const;

/**
 * Fixed named color palette assigned to worktree windows.
 *
 * Closed, stable set: each name maps to a VS Code color block at render time
 * (see worktree-engine). Auto-assignment hashes the branch name into this list so a
 * given branch always lands on the same color across re-renders. A plain
 * lookup, not a Strategy registry -- the variants share behavior.
 *
 * @see assignColor in worktree-engine.ts
 */
export const WORKTREE_COLOR_PALETTE = [
	"blue",
	"green",
	"amber",
	"purple",
	"red",
	"teal",
	"pink",
	"slate",
] as const;

/**
 * One color name drawn from {@link WORKTREE_COLOR_PALETTE}.
 */
export type WorkTreeColor = (typeof WORKTREE_COLOR_PALETTE)[number];

/**
 * Per-branch preferences held in the registry, keyed by branch name.
 *
 * Both fields are optional: an unset `focus` is guessed from the branch name
 * at render time, and an unset `color` is auto-assigned by branch hash. Keying
 * on branch (not worktree path) lets prefs survive worktree delete/recreate.
 */
export interface BranchPrefs {
	/** Repo-relative subfolder to pin as the focused folder. Guessed when absent. */
	focus?: string;
	/** Window color. Auto-assigned from the palette when absent. */
	color?: WorkTreeColor;
}

/**
 * Repo-wide render defaults shared across every worktree pair.
 *
 * @example
 * ```json
 * {
 *   "wip": "~/code/_wip",
 *   "excludes": ["node_modules", "dist", "*.tsbuildinfo"],
 *   "codeBin": "/usr/local/bin/code",
 *   "ignoredWorktrees": ["**\/fallow-audit-base-cache-*"]
 * }
 * ```
 */
export interface RepoDefaults {
	/** Absolute or ~-rooted path pinned as the top WIP scratch folder. Omitted → no WIP folder. */
	wip?: string;
	/** Glob patterns hidden via files.exclude and mirrored into search.exclude. */
	excludes?: readonly string[];
	/** Explicit `code` binary path. Falls back to PATH lookup when absent. */
	codeBin?: string;
	/** Worktree path globs hidden from daily WorkTree views such as clean and render. */
	ignoredWorktrees?: readonly string[];
}

/**
 * The branch-keyed registry: the source of truth worktree renders from.
 *
 * Persisted as a gitignored `worktree.config.json` at repo root. The rendered
 * `.code-workspace` is generated output, never hand-edited.
 */
export interface Registry {
	/** Per-branch preferences, keyed by full branch name (e.g. `codex/browser-use-refactor`). */
	branches: Record<string, BranchPrefs>;
	/** Repo-wide render defaults. */
	defaults?: RepoDefaults;
}

/**
 * One live worktree as discovered through `agent-worktree`.
 *
 * Detached entries and configured ignore path globs are filtered before the
 * engine sees them, so this only ever represents real daily work.
 */
export interface Worktree {
	/** Absolute path to the worktree root on disk. */
	path: string;
	/** Branch checked out in this worktree (e.g. `codex/harden-test-runner`). */
	branch: string;
	/** True when this entry is the main durable worktree for the repo. */
	isMain?: boolean;
}

/**
 * One folder entry in the rendered multi-root workspace.
 *
 * A worktree renders as a pair: a focused subfolder entry plus a full-repo
 * entry. The WIP scratch folder renders as a single pinned entry at the top.
 */
export interface WorkspaceFolder {
	/** Display name shown in the Explorer (may carry an emoji prefix). */
	name: string;
	/** Absolute path the folder roots at. */
	path: string;
}

/**
 * The fully rendered workspace, ready to serialize to `.code-workspace`.
 *
 * `settings` is left loosely typed: it carries VS Code keys
 * (files.exclude, search.exclude, explorer.fileNesting, colorCustomizations,
 * window.title) whose exact shape is VS Code's contract, not worktree's.
 */
export interface RenderedWorkspace {
	/** Ordered folder list: WIP first, then focus+full-repo pairs per worktree. */
	folders: WorkspaceFolder[];
	/** VS Code workspace settings block. */
	settings: Record<string, unknown>;
}

/**
 * Drift-detection record extracted from a generated workspace file's header.
 *
 * WorkTree stamps a `// GENERATED by worktree … hash:<bodyHash>` comment atop the file.
 * On the next sync it recomputes the body hash and compares: a mismatch means
 * the file was edited by hand (or by VS Code) since the last render.
 */
export interface DriftRecord {
	/** Hash recorded in the file header at last render, or null if unstamped. */
	headerHash: string | null;
	/** Hash recomputed from the current file body. */
	bodyHash: string;
	/** True when the body no longer matches the header hash. */
	drifted: boolean;
}
