import {
	type BranchPrefs,
	type Registry,
	type RenderedWorkspace,
	type RepoDefaults,
	type Worktree,
	type WorkspaceFolder,
	WORKTREE_COLOR_PALETTE,
	type WorkTreeColor,
} from "./model.ts";

/**
 * Marker line that opens every generated workspace file.
 *
 * The hash of the body is appended after `hash:` so the next render can detect
 * manual edits. VS Code tolerates `//` comments in `.code-workspace` (JSONC).
 */
const GENERATED_HEADER_PREFIX = "// GENERATED by worktree from worktree.config.json — edits here are overwritten on sync. hash:";

/**
 * Default noise patterns hidden when a repo sets no `excludes`.
 *
 * Regenerated/build artifacts the user never edits; kept here so a bare
 * registry still produces a clean tree.
 */
const DEFAULT_EXCLUDES = [
	"**/node_modules",
	"**/dist",
	"**/build",
	"**/.turbo",
	"**/coverage",
	"**/*.tsbuildinfo",
	"**/.DS_Store",
] as const;

/**
 * VS Code color-customization block for each palette name.
 *
 * Tints the title bar and activity badge so each worktree window is visually
 * distinct. Plain lookup, not a Strategy registry -- the entries share shape.
 */
const PALETTE_COLORS: Record<WorkTreeColor, Record<string, string>> = {
	blue: { "titleBar.activeBackground": "#1e3a8a", "activityBar.background": "#1e3a8a" },
	green: { "titleBar.activeBackground": "#14532d", "activityBar.background": "#14532d" },
	amber: { "titleBar.activeBackground": "#92400e", "activityBar.background": "#92400e" },
	purple: { "titleBar.activeBackground": "#581c87", "activityBar.background": "#581c87" },
	red: { "titleBar.activeBackground": "#7f1d1d", "activityBar.background": "#7f1d1d" },
	teal: { "titleBar.activeBackground": "#134e4a", "activityBar.background": "#134e4a" },
	pink: { "titleBar.activeBackground": "#831843", "activityBar.background": "#831843" },
	slate: { "titleBar.activeBackground": "#334155", "activityBar.background": "#334155" },
};

/**
 * Hash a branch name to a stable index into {@link WORKTREE_COLOR_PALETTE}.
 *
 * Uses the djb2 string hash so a given branch always lands on the same color
 * across re-renders, with no external dependency. Two different branches may
 * collide on a color -- acceptable, since color is a hint not an identity.
 *
 * @param branch - Full branch name (e.g. `codex/browser-use-refactor`)
 * @returns Index in `[0, WORKTREE_COLOR_PALETTE.length)`
 * @internal
 */
function paletteIndex(branch: string): number {
	let hash = 5381;
	for (let i = 0; i < branch.length; i += 1) {
		hash = (hash * 33) ^ branch.charCodeAt(i);
	}
	return Math.abs(hash) % WORKTREE_COLOR_PALETTE.length;
}

/**
 * Resolve a branch's window color: explicit pref, else deterministic from hash.
 *
 * @param branch - Full branch name
 * @param prefs - Registry prefs for this branch (may be undefined)
 * @returns The chosen palette color
 *
 * @example
 * ```typescript
 * assignColor("codex/x", { color: "teal" }) // → "teal"
 * assignColor("codex/x", undefined)          // → stable palette color for "codex/x"
 * ```
 */
export function assignColor(branch: string, prefs?: BranchPrefs): WorkTreeColor {
	if (prefs?.color) {
		return prefs.color;
	}
	return WORKTREE_COLOR_PALETTE[paletteIndex(branch)] as WorkTreeColor;
}

/**
 * Resolve a branch's focus subfolder: explicit pref, else a branch-name guess.
 *
 * Strips a leading `type/` prefix, then a trailing role token
 * (`-refactor`, `-harden`, `harden-`), and probes for `skills/<remainder>`.
 * Falls back to the repo root (empty string) when the probe finds nothing.
 *
 * @param branch - Full branch name (e.g. `codex/harden-test-runner`)
 * @param prefs - Registry prefs for this branch (may be undefined)
 * @param probe - Returns true when a candidate repo-relative subfolder exists
 * @returns Repo-relative focus subfolder, or "" for the repo root
 *
 * @example
 * ```typescript
 * guessFocus("codex/harden-test-runner", undefined, (p) => p === "skills/test-runner")
 * // → "skills/test-runner"
 * ```
 */
export function guessFocus(
	branch: string,
	prefs: BranchPrefs | undefined,
	probe: (subfolder: string) => boolean,
): string {
	if (prefs?.focus) {
		return prefs.focus;
	}
	const withoutType = branch.includes("/") ? branch.slice(branch.indexOf("/") + 1) : branch;
	const stem = withoutType
		.replace(/^harden-/, "")
		.replace(/-(refactor|harden|fix|feat|wip)$/, "");
	const candidate = `skills/${stem}`;
	return probe(candidate) ? candidate : "";
}

/**
 * Build the ordered folder list: pinned WIP folder, then focus+full-repo pairs.
 *
 * @param worktrees - Live worktrees (already filtered of throwaway entries)
 * @param registry - Branch-keyed prefs
 * @param defaults - Repo-wide defaults (WIP path, etc.)
 * @param probe - Subfolder-existence check passed through to {@link guessFocus}
 * @returns Folder entries in display order
 * @internal
 */
function buildFolders(
	worktrees: readonly Worktree[],
	registry: Registry,
	defaults: RepoDefaults,
	probe: (worktreePath: string, subfolder: string) => boolean,
): WorkspaceFolder[] {
	const folders: WorkspaceFolder[] = [];
	if (defaults.wip) {
		folders.push({ name: "📌 WIP", path: defaults.wip });
	}
	for (const worktree of worktrees) {
		const prefs = registry.branches[worktree.branch];
		const focus = guessFocus(worktree.branch, prefs, (sub) => probe(worktree.path, sub));
		const shortName = worktree.branch.includes("/")
			? worktree.branch.slice(worktree.branch.indexOf("/") + 1)
			: worktree.branch;
		if (focus) {
			folders.push({ name: `🌐 ${shortName}`, path: `${worktree.path}/${focus}` });
			folders.push({ name: `📁 ${shortName} repo`, path: worktree.path });
		} else {
			folders.push({ name: `📁 ${shortName}`, path: worktree.path });
		}
	}
	return folders;
}

/**
 * Render the full workspace settings block: excludes, search, nesting, color.
 *
 * @param worktrees - Live worktrees
 * @param registry - Branch-keyed prefs (for per-worktree color)
 * @param defaults - Repo-wide defaults (exclude patterns)
 * @returns A VS Code workspace `settings` object
 * @internal
 */
function buildSettings(
	worktrees: readonly Worktree[],
	registry: Registry,
	defaults: RepoDefaults,
): Record<string, unknown> {
	const patterns = defaults.excludes ?? DEFAULT_EXCLUDES;
	const exclude: Record<string, boolean> = {};
	for (const pattern of patterns) {
		exclude[pattern] = true;
	}
	const colorCustomizations: Record<string, string> = {};
	for (const worktree of worktrees) {
		const color = assignColor(worktree.branch, registry.branches[worktree.branch]);
		Object.assign(colorCustomizations, PALETTE_COLORS[color]);
	}
	return {
		"files.exclude": exclude,
		"search.exclude": { ...exclude },
		"explorer.fileNesting.enabled": true,
		"explorer.fileNesting.patterns": {
			// biome-ignore lint/suspicious/noTemplateCurlyInString: VS Code fileNesting uses literal ${capture} syntax.
			"*.ts": "${capture}.test.ts, ${capture}.js, ${capture}.d.ts",
		},
		"explorer.sortOrder": "type",
		"workbench.colorCustomizations": colorCustomizations,
		// biome-ignore lint/suspicious/noTemplateCurlyInString: VS Code window.title uses literal ${...} variables.
		"window.title": "${rootName}${separator}${activeEditorShort}",
	};
}

/**
 * Render a registry plus live worktrees into a workspace, with no side effects.
 *
 * The pure core of worktree: identical inputs always produce an identical workspace,
 * which is what makes the drift hash meaningful and the engine testable without
 * a filesystem.
 *
 * @param registry - Branch-keyed prefs and repo defaults
 * @param worktrees - Live worktrees, already filtered of throwaway entries
 * @param probe - Returns true when `<worktreePath>/<subfolder>` exists on disk;
 *   injected so the engine stays pure (the caller owns the fs check)
 * @returns The rendered workspace ready to serialize
 *
 * @example
 * ```typescript
 * const ws = renderWorkspace(
 *   { branches: { "codex/x": { color: "blue" } } },
 *   [{ path: "/repo", branch: "codex/x" }],
 *   () => false,
 * )
 * ```
 */
export function renderWorkspace(
	registry: Registry,
	worktrees: readonly Worktree[],
	probe: (worktreePath: string, subfolder: string) => boolean,
): RenderedWorkspace {
	const defaults = registry.defaults ?? {};
	return {
		folders: buildFolders(worktrees, registry, defaults, probe),
		settings: buildSettings(worktrees, registry, defaults),
	};
}

/**
 * Compute a stable content hash for a workspace body.
 *
 * Same djb2 hash as the color index, rendered hex. Identical bodies hash
 * identically; any folder/settings change shifts the hash, which is what the
 * drift gate keys on.
 *
 * @param body - Serialized workspace JSON (without the header line)
 * @returns Lowercase hex hash string
 */
export function computeHash(body: string): string {
	let hash = 5381;
	for (let i = 0; i < body.length; i += 1) {
		hash = (hash * 33) ^ body.charCodeAt(i);
	}
	return (hash >>> 0).toString(16);
}

/**
 * Serialize a workspace and prepend the generated-header line with its hash.
 *
 * @param workspace - The rendered workspace to serialize
 * @returns Full file contents: header comment line, then pretty JSON body
 *
 * @example
 * ```typescript
 * const text = stampHeader(renderWorkspace(registry, worktrees, probe))
 * // "// GENERATED by worktree … hash:1a2b3c\n{ … }"
 * ```
 */
export function stampHeader(workspace: RenderedWorkspace): string {
	const body = `${JSON.stringify(workspace, null, "\t")}\n`;
	return `${GENERATED_HEADER_PREFIX}${computeHash(body)}\n${body}`;
}

/**
 * Read the hash recorded in a generated file's header line.
 *
 * @param fileContents - Full contents of an existing `.code-workspace`
 * @returns The recorded hash, or null when the file has no WorkTree header
 */
export function readHeaderHash(fileContents: string): string | null {
	const firstLine = fileContents.slice(0, fileContents.indexOf("\n"));
	if (!firstLine.startsWith(GENERATED_HEADER_PREFIX)) {
		return null;
	}
	return firstLine.slice(GENERATED_HEADER_PREFIX.length).trim();
}

/**
 * Strip the header line off a generated file, leaving the JSON body.
 *
 * @param fileContents - Full contents of an existing `.code-workspace`
 * @returns The body after the first newline, or the whole input if unstamped
 * @internal
 */
function bodyOf(fileContents: string): string {
	if (!fileContents.startsWith(GENERATED_HEADER_PREFIX)) {
		return fileContents;
	}
	return fileContents.slice(fileContents.indexOf("\n") + 1);
}

/**
 * Detect whether an existing workspace file was edited since the last render.
 *
 * Recomputes the body hash and compares it to the hash stored in the header.
 * A file with no WorkTree header is treated as drifted (it was not produced by worktree),
 * so the caller will not silently overwrite a hand-authored workspace.
 *
 * @param fileContents - Full contents of an existing `.code-workspace`
 * @returns True when the body no longer matches the recorded header hash
 *
 * @example
 * ```typescript
 * if (isDrift(await readFile(path))) { // show diff, require --force }
 * ```
 */
export function isDrift(fileContents: string): boolean {
	const recorded = readHeaderHash(fileContents);
	if (recorded === null) {
		return true;
	}
	return computeHash(bodyOf(fileContents)) !== recorded;
}
